// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/jschady/pulumi-mailslurp/sdk/go/mailslurp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The MailSlurp API key. The provider reads `MAILSLURP_API_KEY` when you
// do not set this property. The key is a secret, and Pulumi encrypts it
// in the state.
func GetApiKey(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "mailslurp:apiKey")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "MAILSLURP_API_KEY"); d != nil {
		value = d.(string)
	}
	return value
}

// The base URL of the MailSlurp API. The default is
// `https://api.mailslurp.com`. Set this property only when you test
// against a different endpoint.
func GetEndpoint(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "mailslurp:endpoint")
	if err == nil {
		return v
	}
	var value string
	value = "https://api.mailslurp.com"
	return value
}
