// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mailslurp

import (
	"context"
	"reflect"

	"github.com/jschady/pulumi-mailslurp/sdk/go/mailslurp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The function reads one MailSlurp custom domain by its identifier. The
// result carries the DNS records that the domain needs, so a stack can
// create them with a DNS provider. The function reads the domain and
// changes nothing.
func GetDomain(ctx *pulumi.Context, args *GetDomainArgs, opts ...pulumi.InvokeOption) (*GetDomainResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDomainResult
	err := ctx.Invoke("mailslurp:index:getDomain", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetDomainArgs struct {
	// If you set this property, MailSlurp checks the domain for DNS record
	// problems. The default is `false`.
	CheckForErrors *bool `pulumi:"checkForErrors"`
	// The identifier of the domain to read. MailSlurp assigns this value when
	// it creates the domain.
	DomainId string `pulumi:"domainId"`
}

type GetDomainResult struct {
	// The identifier of the inbox that receives the email of every unmatched
	// address.
	CatchAllInboxId *string `pulumi:"catchAllInboxId"`
	// The time when MailSlurp created the domain.
	CreatedAt string `pulumi:"createdAt"`
	// The DKIM values of the domain. Add one CNAME record for each value.
	DkimTokens []string `pulumi:"dkimTokens"`
	// The custom domain name.
	Domain string `pulumi:"domain"`
	// The identifier of the domain.
	DomainId string `pulumi:"domainId"`
	// The DNS records that the domain needs. Loop over this list to create the
	// records with a DNS provider.
	DomainNameRecords []DomainNameRecordResult `pulumi:"domainNameRecords"`
	// The domain type.
	DomainType DomainType `pulumi:"domainType"`
	// The message that names the duplicate DNS records.
	DuplicateRecordsMessage *string `pulumi:"duplicateRecordsMessage"`
	// MailSlurp reports whether the domain has a duplicate DNS record.
	HasDuplicateRecords bool `pulumi:"hasDuplicateRecords"`
	// MailSlurp reports whether the domain misses a required DNS record.
	HasMissingRecords bool `pulumi:"hasMissingRecords"`
	// MailSlurp reports whether the domain passed the DNS checks.
	IsVerified bool `pulumi:"isVerified"`
	// The message that names the missing DNS records.
	MissingRecordsMessage *string `pulumi:"missingRecordsMessage"`
	// The time when MailSlurp last changed the domain.
	UpdatedAt string `pulumi:"updatedAt"`
	// The value that proves you own the domain. Add it to the DNS records of
	// the domain.
	VerificationToken string `pulumi:"verificationToken"`
}

func GetDomainOutput(ctx *pulumi.Context, args GetDomainOutputArgs, opts ...pulumi.InvokeOption) GetDomainResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("mailslurp:index:getDomain", args, GetDomainResultOutput{}, options).(GetDomainResultOutput)
}

type GetDomainOutputArgs struct {
	// If you set this property, MailSlurp checks the domain for DNS record
	// problems. The default is `false`.
	CheckForErrors pulumi.BoolPtrInput `pulumi:"checkForErrors"`
	// The identifier of the domain to read. MailSlurp assigns this value when
	// it creates the domain.
	DomainId pulumi.StringInput `pulumi:"domainId"`
}

func (GetDomainOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainArgs)(nil)).Elem()
}

type GetDomainResultOutput struct{ *pulumi.OutputState }

func (GetDomainResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainResult)(nil)).Elem()
}

func (o GetDomainResultOutput) ToGetDomainResultOutput() GetDomainResultOutput {
	return o
}

func (o GetDomainResultOutput) ToGetDomainResultOutputWithContext(ctx context.Context) GetDomainResultOutput {
	return o
}

// The identifier of the inbox that receives the email of every unmatched
// address.
func (o GetDomainResultOutput) CatchAllInboxId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetDomainResult) *string { return v.CatchAllInboxId }).(pulumi.StringPtrOutput)
}

// The time when MailSlurp created the domain.
func (o GetDomainResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The DKIM values of the domain. Add one CNAME record for each value.
func (o GetDomainResultOutput) DkimTokens() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetDomainResult) []string { return v.DkimTokens }).(pulumi.StringArrayOutput)
}

// The custom domain name.
func (o GetDomainResultOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainResult) string { return v.Domain }).(pulumi.StringOutput)
}

// The identifier of the domain.
func (o GetDomainResultOutput) DomainId() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainResult) string { return v.DomainId }).(pulumi.StringOutput)
}

// The DNS records that the domain needs. Loop over this list to create the
// records with a DNS provider.
func (o GetDomainResultOutput) DomainNameRecords() DomainNameRecordResultArrayOutput {
	return o.ApplyT(func(v GetDomainResult) []DomainNameRecordResult { return v.DomainNameRecords }).(DomainNameRecordResultArrayOutput)
}

// The domain type.
func (o GetDomainResultOutput) DomainType() DomainTypeOutput {
	return o.ApplyT(func(v GetDomainResult) DomainType { return v.DomainType }).(DomainTypeOutput)
}

// The message that names the duplicate DNS records.
func (o GetDomainResultOutput) DuplicateRecordsMessage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetDomainResult) *string { return v.DuplicateRecordsMessage }).(pulumi.StringPtrOutput)
}

// MailSlurp reports whether the domain has a duplicate DNS record.
func (o GetDomainResultOutput) HasDuplicateRecords() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDomainResult) bool { return v.HasDuplicateRecords }).(pulumi.BoolOutput)
}

// MailSlurp reports whether the domain misses a required DNS record.
func (o GetDomainResultOutput) HasMissingRecords() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDomainResult) bool { return v.HasMissingRecords }).(pulumi.BoolOutput)
}

// MailSlurp reports whether the domain passed the DNS checks.
func (o GetDomainResultOutput) IsVerified() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDomainResult) bool { return v.IsVerified }).(pulumi.BoolOutput)
}

// The message that names the missing DNS records.
func (o GetDomainResultOutput) MissingRecordsMessage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetDomainResult) *string { return v.MissingRecordsMessage }).(pulumi.StringPtrOutput)
}

// The time when MailSlurp last changed the domain.
func (o GetDomainResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

// The value that proves you own the domain. Add it to the DNS records of
// the domain.
func (o GetDomainResultOutput) VerificationToken() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainResult) string { return v.VerificationToken }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDomainResultOutput{})
}
