// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mailslurp

import (
	"context"
	"reflect"

	"github.com/jschady/pulumi-mailslurp/sdk/go/mailslurp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The function reads one MailSlurp inbox by its identifier. Use it when a
// stack must reference an inbox that Pulumi does not manage. The function
// reads the inbox and changes nothing.
func LookupInbox(ctx *pulumi.Context, args *LookupInboxArgs, opts ...pulumi.InvokeOption) (*LookupInboxResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupInboxResult
	err := ctx.Invoke("mailslurp:index:getInbox", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupInboxArgs struct {
	// The identifier of the inbox to read. MailSlurp assigns this value when
	// it creates the inbox.
	InboxId string `pulumi:"inboxId"`
}

type LookupInboxResult struct {
	// The region of the account that holds the inbox.
	AccountRegion *string `pulumi:"accountRegion"`
	// The time when MailSlurp created the inbox.
	CreatedAt string `pulumi:"createdAt"`
	// The free-text description of the inbox.
	Description *string `pulumi:"description"`
	// The domain part of the inbox email address.
	Domain *string `pulumi:"domain"`
	// The identifier of the custom domain that provides the inbox address.
	DomainId *string `pulumi:"domainId"`
	// The full email address of the inbox.
	EmailAddress string `pulumi:"emailAddress"`
	// The time when MailSlurp expires the inbox, in RFC 3339 format.
	ExpiresAt *string `pulumi:"expiresAt"`
	// MailSlurp reports whether the inbox is a favourite in the dashboard.
	Favourite bool `pulumi:"favourite"`
	// The special function of the inbox, for example an alias or a catch-all.
	FunctionsAs *string `pulumi:"functionsAs"`
	// The identifier of the inbox.
	InboxId string `pulumi:"inboxId"`
	// The inbox type.
	InboxType *InboxType `pulumi:"inboxType"`
	// The local part of the inbox email address.
	LocalPart *string `pulumi:"localPart"`
	// The display name of the inbox.
	Name *string `pulumi:"name"`
	// MailSlurp reports whether the inbox is read-only.
	ReadOnly bool `pulumi:"readOnly"`
	// The tags on the inbox.
	Tags []string `pulumi:"tags"`
	// MailSlurp reports whether the inbox is virtual. A virtual inbox never sends email to real recipients.
	VirtualInbox bool `pulumi:"virtualInbox"`
}

func LookupInboxOutput(ctx *pulumi.Context, args LookupInboxOutputArgs, opts ...pulumi.InvokeOption) LookupInboxResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("mailslurp:index:getInbox", args, LookupInboxResultOutput{}, options).(LookupInboxResultOutput)
}

type LookupInboxOutputArgs struct {
	// The identifier of the inbox to read. MailSlurp assigns this value when
	// it creates the inbox.
	InboxId pulumi.StringInput `pulumi:"inboxId"`
}

func (LookupInboxOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInboxArgs)(nil)).Elem()
}

type LookupInboxResultOutput struct{ *pulumi.OutputState }

func (LookupInboxResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInboxResult)(nil)).Elem()
}

func (o LookupInboxResultOutput) ToLookupInboxResultOutput() LookupInboxResultOutput {
	return o
}

func (o LookupInboxResultOutput) ToLookupInboxResultOutputWithContext(ctx context.Context) LookupInboxResultOutput {
	return o
}

// The region of the account that holds the inbox.
func (o LookupInboxResultOutput) AccountRegion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInboxResult) *string { return v.AccountRegion }).(pulumi.StringPtrOutput)
}

// The time when MailSlurp created the inbox.
func (o LookupInboxResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInboxResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The free-text description of the inbox.
func (o LookupInboxResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInboxResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The domain part of the inbox email address.
func (o LookupInboxResultOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInboxResult) *string { return v.Domain }).(pulumi.StringPtrOutput)
}

// The identifier of the custom domain that provides the inbox address.
func (o LookupInboxResultOutput) DomainId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInboxResult) *string { return v.DomainId }).(pulumi.StringPtrOutput)
}

// The full email address of the inbox.
func (o LookupInboxResultOutput) EmailAddress() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInboxResult) string { return v.EmailAddress }).(pulumi.StringOutput)
}

// The time when MailSlurp expires the inbox, in RFC 3339 format.
func (o LookupInboxResultOutput) ExpiresAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInboxResult) *string { return v.ExpiresAt }).(pulumi.StringPtrOutput)
}

// MailSlurp reports whether the inbox is a favourite in the dashboard.
func (o LookupInboxResultOutput) Favourite() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupInboxResult) bool { return v.Favourite }).(pulumi.BoolOutput)
}

// The special function of the inbox, for example an alias or a catch-all.
func (o LookupInboxResultOutput) FunctionsAs() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInboxResult) *string { return v.FunctionsAs }).(pulumi.StringPtrOutput)
}

// The identifier of the inbox.
func (o LookupInboxResultOutput) InboxId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInboxResult) string { return v.InboxId }).(pulumi.StringOutput)
}

// The inbox type.
func (o LookupInboxResultOutput) InboxType() InboxTypePtrOutput {
	return o.ApplyT(func(v LookupInboxResult) *InboxType { return v.InboxType }).(InboxTypePtrOutput)
}

// The local part of the inbox email address.
func (o LookupInboxResultOutput) LocalPart() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInboxResult) *string { return v.LocalPart }).(pulumi.StringPtrOutput)
}

// The display name of the inbox.
func (o LookupInboxResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInboxResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// MailSlurp reports whether the inbox is read-only.
func (o LookupInboxResultOutput) ReadOnly() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupInboxResult) bool { return v.ReadOnly }).(pulumi.BoolOutput)
}

// The tags on the inbox.
func (o LookupInboxResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupInboxResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

// MailSlurp reports whether the inbox is virtual. A virtual inbox never sends email to real recipients.
func (o LookupInboxResultOutput) VirtualInbox() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupInboxResult) bool { return v.VirtualInbox }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupInboxResultOutput{})
}
