// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mailslurp

import (
	"context"
	"reflect"

	"errors"
	"github.com/jschady/pulumi-mailslurp/sdk/go/mailslurp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// An inbox ruleset that blocks or allows email for one inbox. MailSlurp
// applies the ruleset when the inbox sends or receives email.
//
// You cannot update a ruleset. The API offers no update call, so Pulumi
// replaces the ruleset when you change any property. Pulumi creates the new
// ruleset, and then it deletes the old one. A ruleset is free, and it never
// counts against the inbox creation quota.
//
// ## Example Usage
// ### A ruleset that blocks the email of one domain
// ```go
// package main
//
// import (
//
//	"github.com/jschady/pulumi-mailslurp/sdk/go/mailslurp"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			supportInbox, err := mailslurp.NewInbox(ctx, "support-inbox", &mailslurp.InboxArgs{
//				Name: pulumi.String("support-inbox"),
//			})
//			if err != nil {
//				return err
//			}
//			blockOneDomain, err := mailslurp.NewInboxRuleset(ctx, "block-one-domain", &mailslurp.InboxRulesetArgs{
//				Action:  mailslurp.RulesetActionBlock,
//				InboxId: supportInbox.ID().ToIDOutput().ToStringOutput(),
//				Scope:   mailslurp.RulesetScopeReceivingEmails,
//				Target:  pulumi.String("*@blocked.example.com"),
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("rulesetId", blockOneDomain.ID())
//			return nil
//		})
//	}
//
// ```
type InboxRuleset struct {
	pulumi.CustomResourceState

	// The action that MailSlurp takes when the target matches.
	Action RulesetActionOutput `pulumi:"action"`
	// The time when MailSlurp created the ruleset.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The handler that MailSlurp runs for the ruleset. The API reports one value, `EXCEPTION`.
	Handler pulumi.StringOutput `pulumi:"handler"`
	// The inbox that the ruleset applies to.
	InboxId pulumi.StringOutput `pulumi:"inboxId"`
	// The phone number that the ruleset applies to. This resource always names
	// an inbox, so MailSlurp reports no phone number.
	PhoneId pulumi.StringPtrOutput `pulumi:"phoneId"`
	// The activity that the ruleset applies to.
	Scope RulesetScopeOutput `pulumi:"scope"`
	// The email address or the pattern that MailSlurp matches.
	Target pulumi.StringOutput `pulumi:"target"`
}

// NewInboxRuleset registers a new resource with the given unique name, arguments, and options.
func NewInboxRuleset(ctx *pulumi.Context,
	name string, args *InboxRulesetArgs, opts ...pulumi.ResourceOption) (*InboxRuleset, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Action == nil {
		return nil, errors.New("invalid value for required argument 'Action'")
	}
	if args.InboxId == nil {
		return nil, errors.New("invalid value for required argument 'InboxId'")
	}
	if args.Scope == nil {
		return nil, errors.New("invalid value for required argument 'Scope'")
	}
	if args.Target == nil {
		return nil, errors.New("invalid value for required argument 'Target'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource InboxRuleset
	err := ctx.RegisterResource("mailslurp:index:InboxRuleset", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInboxRuleset gets an existing InboxRuleset resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInboxRuleset(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InboxRulesetState, opts ...pulumi.ResourceOption) (*InboxRuleset, error) {
	var resource InboxRuleset
	err := ctx.ReadResource("mailslurp:index:InboxRuleset", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering InboxRuleset resources.
type inboxRulesetState struct {
}

type InboxRulesetState struct {
}

func (InboxRulesetState) ElementType() reflect.Type {
	return reflect.TypeOf((*inboxRulesetState)(nil)).Elem()
}

type inboxRulesetArgs struct {
	// The action that MailSlurp takes when the target matches. The `ALLOW`
	// action wins over the `BLOCK` action. The `FILTER_REMOVE` action removes
	// the matched address and keeps the rest of the email. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
	Action RulesetAction `pulumi:"action"`
	// The inbox that the ruleset applies to. MailSlurp matches the email of the
	// inbox against the target. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
	InboxId string `pulumi:"inboxId"`
	// The activity that the ruleset applies to. Use `RECEIVING_EMAILS` for the
	// email the inbox receives. Use `SENDING_EMAILS` for the email the inbox
	// sends. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
	Scope RulesetScope `pulumi:"scope"`
	// The email address or the pattern that MailSlurp matches. Use
	// `*@example.com` to match every address of a domain. Use one full address
	// to match that address alone. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
	Target string `pulumi:"target"`
}

// The set of arguments for constructing a InboxRuleset resource.
type InboxRulesetArgs struct {
	// The action that MailSlurp takes when the target matches. The `ALLOW`
	// action wins over the `BLOCK` action. The `FILTER_REMOVE` action removes
	// the matched address and keeps the rest of the email. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
	Action RulesetActionInput
	// The inbox that the ruleset applies to. MailSlurp matches the email of the
	// inbox against the target. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
	InboxId pulumi.StringInput
	// The activity that the ruleset applies to. Use `RECEIVING_EMAILS` for the
	// email the inbox receives. Use `SENDING_EMAILS` for the email the inbox
	// sends. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
	Scope RulesetScopeInput
	// The email address or the pattern that MailSlurp matches. Use
	// `*@example.com` to match every address of a domain. Use one full address
	// to match that address alone. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
	Target pulumi.StringInput
}

func (InboxRulesetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*inboxRulesetArgs)(nil)).Elem()
}

type InboxRulesetInput interface {
	pulumi.Input

	ToInboxRulesetOutput() InboxRulesetOutput
	ToInboxRulesetOutputWithContext(ctx context.Context) InboxRulesetOutput
}

func (*InboxRuleset) ElementType() reflect.Type {
	return reflect.TypeOf((**InboxRuleset)(nil)).Elem()
}

func (i *InboxRuleset) ToInboxRulesetOutput() InboxRulesetOutput {
	return i.ToInboxRulesetOutputWithContext(context.Background())
}

func (i *InboxRuleset) ToInboxRulesetOutputWithContext(ctx context.Context) InboxRulesetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InboxRulesetOutput)
}

// InboxRulesetArrayInput is an input type that accepts InboxRulesetArray and InboxRulesetArrayOutput values.
// You can construct a concrete instance of `InboxRulesetArrayInput` via:
//
//	InboxRulesetArray{ InboxRulesetArgs{...} }
type InboxRulesetArrayInput interface {
	pulumi.Input

	ToInboxRulesetArrayOutput() InboxRulesetArrayOutput
	ToInboxRulesetArrayOutputWithContext(context.Context) InboxRulesetArrayOutput
}

type InboxRulesetArray []InboxRulesetInput

func (InboxRulesetArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*InboxRuleset)(nil)).Elem()
}

func (i InboxRulesetArray) ToInboxRulesetArrayOutput() InboxRulesetArrayOutput {
	return i.ToInboxRulesetArrayOutputWithContext(context.Background())
}

func (i InboxRulesetArray) ToInboxRulesetArrayOutputWithContext(ctx context.Context) InboxRulesetArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InboxRulesetArrayOutput)
}

// InboxRulesetMapInput is an input type that accepts InboxRulesetMap and InboxRulesetMapOutput values.
// You can construct a concrete instance of `InboxRulesetMapInput` via:
//
//	InboxRulesetMap{ "key": InboxRulesetArgs{...} }
type InboxRulesetMapInput interface {
	pulumi.Input

	ToInboxRulesetMapOutput() InboxRulesetMapOutput
	ToInboxRulesetMapOutputWithContext(context.Context) InboxRulesetMapOutput
}

type InboxRulesetMap map[string]InboxRulesetInput

func (InboxRulesetMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*InboxRuleset)(nil)).Elem()
}

func (i InboxRulesetMap) ToInboxRulesetMapOutput() InboxRulesetMapOutput {
	return i.ToInboxRulesetMapOutputWithContext(context.Background())
}

func (i InboxRulesetMap) ToInboxRulesetMapOutputWithContext(ctx context.Context) InboxRulesetMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InboxRulesetMapOutput)
}

type InboxRulesetOutput struct{ *pulumi.OutputState }

func (InboxRulesetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**InboxRuleset)(nil)).Elem()
}

func (o InboxRulesetOutput) ToInboxRulesetOutput() InboxRulesetOutput {
	return o
}

func (o InboxRulesetOutput) ToInboxRulesetOutputWithContext(ctx context.Context) InboxRulesetOutput {
	return o
}

// The action that MailSlurp takes when the target matches.
func (o InboxRulesetOutput) Action() RulesetActionOutput {
	return o.ApplyT(func(v *InboxRuleset) RulesetActionOutput { return v.Action }).(RulesetActionOutput)
}

// The time when MailSlurp created the ruleset.
func (o InboxRulesetOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *InboxRuleset) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The handler that MailSlurp runs for the ruleset. The API reports one value, `EXCEPTION`.
func (o InboxRulesetOutput) Handler() pulumi.StringOutput {
	return o.ApplyT(func(v *InboxRuleset) pulumi.StringOutput { return v.Handler }).(pulumi.StringOutput)
}

// The inbox that the ruleset applies to.
func (o InboxRulesetOutput) InboxId() pulumi.StringOutput {
	return o.ApplyT(func(v *InboxRuleset) pulumi.StringOutput { return v.InboxId }).(pulumi.StringOutput)
}

// The phone number that the ruleset applies to. This resource always names
// an inbox, so MailSlurp reports no phone number.
func (o InboxRulesetOutput) PhoneId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *InboxRuleset) pulumi.StringPtrOutput { return v.PhoneId }).(pulumi.StringPtrOutput)
}

// The activity that the ruleset applies to.
func (o InboxRulesetOutput) Scope() RulesetScopeOutput {
	return o.ApplyT(func(v *InboxRuleset) RulesetScopeOutput { return v.Scope }).(RulesetScopeOutput)
}

// The email address or the pattern that MailSlurp matches.
func (o InboxRulesetOutput) Target() pulumi.StringOutput {
	return o.ApplyT(func(v *InboxRuleset) pulumi.StringOutput { return v.Target }).(pulumi.StringOutput)
}

type InboxRulesetArrayOutput struct{ *pulumi.OutputState }

func (InboxRulesetArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*InboxRuleset)(nil)).Elem()
}

func (o InboxRulesetArrayOutput) ToInboxRulesetArrayOutput() InboxRulesetArrayOutput {
	return o
}

func (o InboxRulesetArrayOutput) ToInboxRulesetArrayOutputWithContext(ctx context.Context) InboxRulesetArrayOutput {
	return o
}

func (o InboxRulesetArrayOutput) Index(i pulumi.IntInput) InboxRulesetOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *InboxRuleset {
		return vs[0].([]*InboxRuleset)[vs[1].(int)]
	}).(InboxRulesetOutput)
}

type InboxRulesetMapOutput struct{ *pulumi.OutputState }

func (InboxRulesetMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*InboxRuleset)(nil)).Elem()
}

func (o InboxRulesetMapOutput) ToInboxRulesetMapOutput() InboxRulesetMapOutput {
	return o
}

func (o InboxRulesetMapOutput) ToInboxRulesetMapOutputWithContext(ctx context.Context) InboxRulesetMapOutput {
	return o
}

func (o InboxRulesetMapOutput) MapIndex(k pulumi.StringInput) InboxRulesetOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *InboxRuleset {
		return vs[0].(map[string]*InboxRuleset)[vs[1].(string)]
	}).(InboxRulesetOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InboxRulesetInput)(nil)).Elem(), &InboxRuleset{})
	pulumi.RegisterInputType(reflect.TypeOf((*InboxRulesetArrayInput)(nil)).Elem(), InboxRulesetArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*InboxRulesetMapInput)(nil)).Elem(), InboxRulesetMap{})
	pulumi.RegisterOutputType(InboxRulesetOutput{})
	pulumi.RegisterOutputType(InboxRulesetArrayOutput{})
	pulumi.RegisterOutputType(InboxRulesetMapOutput{})
}
