// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mailslurp

import (
	"context"
	"reflect"

	"github.com/jschady/pulumi-mailslurp/sdk/go/mailslurp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Provider struct {
	pulumi.ProviderResourceState

	// The MailSlurp API key. The provider reads `MAILSLURP_API_KEY` when you
	// do not set this property. The key is a secret, and Pulumi encrypts it
	// in the state.
	ApiKey pulumi.StringPtrOutput `pulumi:"apiKey"`
	// The base URL of the MailSlurp API. The default is
	// `https://api.mailslurp.com`. Set this property only when you test
	// against a different endpoint.
	Endpoint pulumi.StringPtrOutput `pulumi:"endpoint"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.ApiKey == nil {
		if d := internal.GetEnvOrDefault("", nil, "MAILSLURP_API_KEY"); d != nil {
			args.ApiKey = pulumi.StringPtr(d.(string))
		}
	}
	if args.Endpoint == nil {
		args.Endpoint = pulumi.StringPtr("https://api.mailslurp.com")
	}
	if args.ApiKey != nil {
		args.ApiKey = pulumi.ToSecret(args.ApiKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:mailslurp", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The MailSlurp API key. The provider reads `MAILSLURP_API_KEY` when you
	// do not set this property. The key is a secret, and Pulumi encrypts it
	// in the state.
	ApiKey *string `pulumi:"apiKey"`
	// The base URL of the MailSlurp API. The default is
	// `https://api.mailslurp.com`. Set this property only when you test
	// against a different endpoint.
	Endpoint *string `pulumi:"endpoint"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The MailSlurp API key. The provider reads `MAILSLURP_API_KEY` when you
	// do not set this property. The key is a secret, and Pulumi encrypts it
	// in the state.
	ApiKey pulumi.StringPtrInput
	// The base URL of the MailSlurp API. The default is
	// `https://api.mailslurp.com`. Set this property only when you test
	// against a different endpoint.
	Endpoint pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// The MailSlurp API key. The provider reads `MAILSLURP_API_KEY` when you
// do not set this property. The key is a secret, and Pulumi encrypts it
// in the state.
func (o ProviderOutput) ApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiKey }).(pulumi.StringPtrOutput)
}

// The base URL of the MailSlurp API. The default is
// `https://api.mailslurp.com`. Set this property only when you test
// against a different endpoint.
func (o ProviderOutput) Endpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Endpoint }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
