// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mailslurp

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type DomainType string

const (
	// The domain serves inboxes that store email with HTTP endpoints.
	DomainTypeHttpInbox = DomainType("HTTP_INBOX")
	// The domain serves inboxes that receive email on a real SMTP mail server.
	DomainTypeSmtpDomain = DomainType("SMTP_DOMAIN")
)

type DomainTypeOutput struct{ *pulumi.OutputState }

func (DomainTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainType)(nil)).Elem()
}

func (o DomainTypeOutput) ToDomainTypeOutput() DomainTypeOutput {
	return o
}

func (o DomainTypeOutput) ToDomainTypeOutputWithContext(ctx context.Context) DomainTypeOutput {
	return o
}

func (o DomainTypeOutput) ToDomainTypePtrOutput() DomainTypePtrOutput {
	return o.ToDomainTypePtrOutputWithContext(context.Background())
}

func (o DomainTypeOutput) ToDomainTypePtrOutputWithContext(ctx context.Context) DomainTypePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DomainType) *DomainType {
		return &v
	}).(DomainTypePtrOutput)
}

func (o DomainTypeOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o DomainTypeOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e DomainType) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o DomainTypeOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o DomainTypeOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e DomainType) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type DomainTypePtrOutput struct{ *pulumi.OutputState }

func (DomainTypePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainType)(nil)).Elem()
}

func (o DomainTypePtrOutput) ToDomainTypePtrOutput() DomainTypePtrOutput {
	return o
}

func (o DomainTypePtrOutput) ToDomainTypePtrOutputWithContext(ctx context.Context) DomainTypePtrOutput {
	return o
}

func (o DomainTypePtrOutput) Elem() DomainTypeOutput {
	return o.ApplyT(func(v *DomainType) DomainType {
		if v != nil {
			return *v
		}
		var ret DomainType
		return ret
	}).(DomainTypeOutput)
}

func (o DomainTypePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o DomainTypePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *DomainType) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type ForwarderField string

const (
	// MailSlurp compares the addresses that the email went to.
	ForwarderFieldRecipients = ForwarderField("RECIPIENTS")
	// MailSlurp compares the address that sent the email.
	ForwarderFieldSender = ForwarderField("SENDER")
	// MailSlurp compares the subject of the email.
	ForwarderFieldSubject = ForwarderField("SUBJECT")
	// MailSlurp compares the attachments of the email.
	ForwarderFieldAttachments = ForwarderField("ATTACHMENTS")
	// MailSlurp compares the file name of each attachment.
	ForwarderFieldAttachmentFilename = ForwarderField("ATTACHMENT_FILENAME")
	// MailSlurp compares the text inside each attachment.
	ForwarderFieldAttachmentText = ForwarderField("ATTACHMENT_TEXT")
)

func (ForwarderField) ElementType() reflect.Type {
	return reflect.TypeOf((*ForwarderField)(nil)).Elem()
}

func (e ForwarderField) ToForwarderFieldOutput() ForwarderFieldOutput {
	return pulumi.ToOutput(e).(ForwarderFieldOutput)
}

func (e ForwarderField) ToForwarderFieldOutputWithContext(ctx context.Context) ForwarderFieldOutput {
	return pulumi.ToOutputWithContext(ctx, e).(ForwarderFieldOutput)
}

func (e ForwarderField) ToForwarderFieldPtrOutput() ForwarderFieldPtrOutput {
	return e.ToForwarderFieldPtrOutputWithContext(context.Background())
}

func (e ForwarderField) ToForwarderFieldPtrOutputWithContext(ctx context.Context) ForwarderFieldPtrOutput {
	return ForwarderField(e).ToForwarderFieldOutputWithContext(ctx).ToForwarderFieldPtrOutputWithContext(ctx)
}

func (e ForwarderField) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e ForwarderField) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e ForwarderField) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e ForwarderField) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type ForwarderFieldOutput struct{ *pulumi.OutputState }

func (ForwarderFieldOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ForwarderField)(nil)).Elem()
}

func (o ForwarderFieldOutput) ToForwarderFieldOutput() ForwarderFieldOutput {
	return o
}

func (o ForwarderFieldOutput) ToForwarderFieldOutputWithContext(ctx context.Context) ForwarderFieldOutput {
	return o
}

func (o ForwarderFieldOutput) ToForwarderFieldPtrOutput() ForwarderFieldPtrOutput {
	return o.ToForwarderFieldPtrOutputWithContext(context.Background())
}

func (o ForwarderFieldOutput) ToForwarderFieldPtrOutputWithContext(ctx context.Context) ForwarderFieldPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ForwarderField) *ForwarderField {
		return &v
	}).(ForwarderFieldPtrOutput)
}

func (o ForwarderFieldOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ForwarderFieldOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ForwarderField) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o ForwarderFieldOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ForwarderFieldOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ForwarderField) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type ForwarderFieldPtrOutput struct{ *pulumi.OutputState }

func (ForwarderFieldPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ForwarderField)(nil)).Elem()
}

func (o ForwarderFieldPtrOutput) ToForwarderFieldPtrOutput() ForwarderFieldPtrOutput {
	return o
}

func (o ForwarderFieldPtrOutput) ToForwarderFieldPtrOutputWithContext(ctx context.Context) ForwarderFieldPtrOutput {
	return o
}

func (o ForwarderFieldPtrOutput) Elem() ForwarderFieldOutput {
	return o.ApplyT(func(v *ForwarderField) ForwarderField {
		if v != nil {
			return *v
		}
		var ret ForwarderField
		return ret
	}).(ForwarderFieldOutput)
}

func (o ForwarderFieldPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ForwarderFieldPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *ForwarderField) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// ForwarderFieldInput is an input type that accepts values of the ForwarderField enum
// A concrete instance of `ForwarderFieldInput` can be one of the following:
//
//	ForwarderFieldRecipients
//	ForwarderFieldSender
//	ForwarderFieldSubject
//	ForwarderFieldAttachments
//	ForwarderFieldAttachmentFilename
//	ForwarderFieldAttachmentText
type ForwarderFieldInput interface {
	pulumi.Input

	ToForwarderFieldOutput() ForwarderFieldOutput
	ToForwarderFieldOutputWithContext(context.Context) ForwarderFieldOutput
}

var forwarderFieldPtrType = reflect.TypeOf((**ForwarderField)(nil)).Elem()

type ForwarderFieldPtrInput interface {
	pulumi.Input

	ToForwarderFieldPtrOutput() ForwarderFieldPtrOutput
	ToForwarderFieldPtrOutputWithContext(context.Context) ForwarderFieldPtrOutput
}

type forwarderFieldPtr string

func ForwarderFieldPtr(v string) ForwarderFieldPtrInput {
	return (*forwarderFieldPtr)(&v)
}

func (*forwarderFieldPtr) ElementType() reflect.Type {
	return forwarderFieldPtrType
}

func (in *forwarderFieldPtr) ToForwarderFieldPtrOutput() ForwarderFieldPtrOutput {
	return pulumi.ToOutput(in).(ForwarderFieldPtrOutput)
}

func (in *forwarderFieldPtr) ToForwarderFieldPtrOutputWithContext(ctx context.Context) ForwarderFieldPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(ForwarderFieldPtrOutput)
}

type ForwarderMatchOperator string

const (
	// MailSlurp forwards the email when every rule of the group matches.
	ForwarderMatchOperatorAnd = ForwarderMatchOperator("AND")
	// MailSlurp forwards the email when one rule of the group matches.
	ForwarderMatchOperatorOr = ForwarderMatchOperator("OR")
)

func (ForwarderMatchOperator) ElementType() reflect.Type {
	return reflect.TypeOf((*ForwarderMatchOperator)(nil)).Elem()
}

func (e ForwarderMatchOperator) ToForwarderMatchOperatorOutput() ForwarderMatchOperatorOutput {
	return pulumi.ToOutput(e).(ForwarderMatchOperatorOutput)
}

func (e ForwarderMatchOperator) ToForwarderMatchOperatorOutputWithContext(ctx context.Context) ForwarderMatchOperatorOutput {
	return pulumi.ToOutputWithContext(ctx, e).(ForwarderMatchOperatorOutput)
}

func (e ForwarderMatchOperator) ToForwarderMatchOperatorPtrOutput() ForwarderMatchOperatorPtrOutput {
	return e.ToForwarderMatchOperatorPtrOutputWithContext(context.Background())
}

func (e ForwarderMatchOperator) ToForwarderMatchOperatorPtrOutputWithContext(ctx context.Context) ForwarderMatchOperatorPtrOutput {
	return ForwarderMatchOperator(e).ToForwarderMatchOperatorOutputWithContext(ctx).ToForwarderMatchOperatorPtrOutputWithContext(ctx)
}

func (e ForwarderMatchOperator) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e ForwarderMatchOperator) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e ForwarderMatchOperator) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e ForwarderMatchOperator) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type ForwarderMatchOperatorOutput struct{ *pulumi.OutputState }

func (ForwarderMatchOperatorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ForwarderMatchOperator)(nil)).Elem()
}

func (o ForwarderMatchOperatorOutput) ToForwarderMatchOperatorOutput() ForwarderMatchOperatorOutput {
	return o
}

func (o ForwarderMatchOperatorOutput) ToForwarderMatchOperatorOutputWithContext(ctx context.Context) ForwarderMatchOperatorOutput {
	return o
}

func (o ForwarderMatchOperatorOutput) ToForwarderMatchOperatorPtrOutput() ForwarderMatchOperatorPtrOutput {
	return o.ToForwarderMatchOperatorPtrOutputWithContext(context.Background())
}

func (o ForwarderMatchOperatorOutput) ToForwarderMatchOperatorPtrOutputWithContext(ctx context.Context) ForwarderMatchOperatorPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ForwarderMatchOperator) *ForwarderMatchOperator {
		return &v
	}).(ForwarderMatchOperatorPtrOutput)
}

func (o ForwarderMatchOperatorOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ForwarderMatchOperatorOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ForwarderMatchOperator) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o ForwarderMatchOperatorOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ForwarderMatchOperatorOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ForwarderMatchOperator) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type ForwarderMatchOperatorPtrOutput struct{ *pulumi.OutputState }

func (ForwarderMatchOperatorPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ForwarderMatchOperator)(nil)).Elem()
}

func (o ForwarderMatchOperatorPtrOutput) ToForwarderMatchOperatorPtrOutput() ForwarderMatchOperatorPtrOutput {
	return o
}

func (o ForwarderMatchOperatorPtrOutput) ToForwarderMatchOperatorPtrOutputWithContext(ctx context.Context) ForwarderMatchOperatorPtrOutput {
	return o
}

func (o ForwarderMatchOperatorPtrOutput) Elem() ForwarderMatchOperatorOutput {
	return o.ApplyT(func(v *ForwarderMatchOperator) ForwarderMatchOperator {
		if v != nil {
			return *v
		}
		var ret ForwarderMatchOperator
		return ret
	}).(ForwarderMatchOperatorOutput)
}

func (o ForwarderMatchOperatorPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ForwarderMatchOperatorPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *ForwarderMatchOperator) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// ForwarderMatchOperatorInput is an input type that accepts values of the ForwarderMatchOperator enum
// A concrete instance of `ForwarderMatchOperatorInput` can be one of the following:
//
//	ForwarderMatchOperatorAnd
//	ForwarderMatchOperatorOr
type ForwarderMatchOperatorInput interface {
	pulumi.Input

	ToForwarderMatchOperatorOutput() ForwarderMatchOperatorOutput
	ToForwarderMatchOperatorOutputWithContext(context.Context) ForwarderMatchOperatorOutput
}

var forwarderMatchOperatorPtrType = reflect.TypeOf((**ForwarderMatchOperator)(nil)).Elem()

type ForwarderMatchOperatorPtrInput interface {
	pulumi.Input

	ToForwarderMatchOperatorPtrOutput() ForwarderMatchOperatorPtrOutput
	ToForwarderMatchOperatorPtrOutputWithContext(context.Context) ForwarderMatchOperatorPtrOutput
}

type forwarderMatchOperatorPtr string

func ForwarderMatchOperatorPtr(v string) ForwarderMatchOperatorPtrInput {
	return (*forwarderMatchOperatorPtr)(&v)
}

func (*forwarderMatchOperatorPtr) ElementType() reflect.Type {
	return forwarderMatchOperatorPtrType
}

func (in *forwarderMatchOperatorPtr) ToForwarderMatchOperatorPtrOutput() ForwarderMatchOperatorPtrOutput {
	return pulumi.ToOutput(in).(ForwarderMatchOperatorPtrOutput)
}

func (in *forwarderMatchOperatorPtr) ToForwarderMatchOperatorPtrOutputWithContext(ctx context.Context) ForwarderMatchOperatorPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(ForwarderMatchOperatorPtrOutput)
}

type ForwarderShould string

const (
	// MailSlurp reads the match value as a pattern. A star matches every character.
	ForwarderShouldWildcard = ForwarderShould("WILDCARD")
	// MailSlurp compares the part with the whole match value. The API does not state how this mode differs from `EQUAL`.
	ForwarderShouldMatch = ForwarderShould("MATCH")
	// MailSlurp forwards the email when the part holds the match value inside it.
	ForwarderShouldContain = ForwarderShould("CONTAIN")
	// MailSlurp forwards the email when the part and the match value are the same.
	ForwarderShouldEqual = ForwarderShould("EQUAL")
)

func (ForwarderShould) ElementType() reflect.Type {
	return reflect.TypeOf((*ForwarderShould)(nil)).Elem()
}

func (e ForwarderShould) ToForwarderShouldOutput() ForwarderShouldOutput {
	return pulumi.ToOutput(e).(ForwarderShouldOutput)
}

func (e ForwarderShould) ToForwarderShouldOutputWithContext(ctx context.Context) ForwarderShouldOutput {
	return pulumi.ToOutputWithContext(ctx, e).(ForwarderShouldOutput)
}

func (e ForwarderShould) ToForwarderShouldPtrOutput() ForwarderShouldPtrOutput {
	return e.ToForwarderShouldPtrOutputWithContext(context.Background())
}

func (e ForwarderShould) ToForwarderShouldPtrOutputWithContext(ctx context.Context) ForwarderShouldPtrOutput {
	return ForwarderShould(e).ToForwarderShouldOutputWithContext(ctx).ToForwarderShouldPtrOutputWithContext(ctx)
}

func (e ForwarderShould) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e ForwarderShould) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e ForwarderShould) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e ForwarderShould) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type ForwarderShouldOutput struct{ *pulumi.OutputState }

func (ForwarderShouldOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ForwarderShould)(nil)).Elem()
}

func (o ForwarderShouldOutput) ToForwarderShouldOutput() ForwarderShouldOutput {
	return o
}

func (o ForwarderShouldOutput) ToForwarderShouldOutputWithContext(ctx context.Context) ForwarderShouldOutput {
	return o
}

func (o ForwarderShouldOutput) ToForwarderShouldPtrOutput() ForwarderShouldPtrOutput {
	return o.ToForwarderShouldPtrOutputWithContext(context.Background())
}

func (o ForwarderShouldOutput) ToForwarderShouldPtrOutputWithContext(ctx context.Context) ForwarderShouldPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ForwarderShould) *ForwarderShould {
		return &v
	}).(ForwarderShouldPtrOutput)
}

func (o ForwarderShouldOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ForwarderShouldOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ForwarderShould) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o ForwarderShouldOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ForwarderShouldOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ForwarderShould) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type ForwarderShouldPtrOutput struct{ *pulumi.OutputState }

func (ForwarderShouldPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ForwarderShould)(nil)).Elem()
}

func (o ForwarderShouldPtrOutput) ToForwarderShouldPtrOutput() ForwarderShouldPtrOutput {
	return o
}

func (o ForwarderShouldPtrOutput) ToForwarderShouldPtrOutputWithContext(ctx context.Context) ForwarderShouldPtrOutput {
	return o
}

func (o ForwarderShouldPtrOutput) Elem() ForwarderShouldOutput {
	return o.ApplyT(func(v *ForwarderShould) ForwarderShould {
		if v != nil {
			return *v
		}
		var ret ForwarderShould
		return ret
	}).(ForwarderShouldOutput)
}

func (o ForwarderShouldPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ForwarderShouldPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *ForwarderShould) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// ForwarderShouldInput is an input type that accepts values of the ForwarderShould enum
// A concrete instance of `ForwarderShouldInput` can be one of the following:
//
//	ForwarderShouldWildcard
//	ForwarderShouldMatch
//	ForwarderShouldContain
//	ForwarderShouldEqual
type ForwarderShouldInput interface {
	pulumi.Input

	ToForwarderShouldOutput() ForwarderShouldOutput
	ToForwarderShouldOutputWithContext(context.Context) ForwarderShouldOutput
}

var forwarderShouldPtrType = reflect.TypeOf((**ForwarderShould)(nil)).Elem()

type ForwarderShouldPtrInput interface {
	pulumi.Input

	ToForwarderShouldPtrOutput() ForwarderShouldPtrOutput
	ToForwarderShouldPtrOutputWithContext(context.Context) ForwarderShouldPtrOutput
}

type forwarderShouldPtr string

func ForwarderShouldPtr(v string) ForwarderShouldPtrInput {
	return (*forwarderShouldPtr)(&v)
}

func (*forwarderShouldPtr) ElementType() reflect.Type {
	return forwarderShouldPtrType
}

func (in *forwarderShouldPtr) ToForwarderShouldPtrOutput() ForwarderShouldPtrOutput {
	return pulumi.ToOutput(in).(ForwarderShouldPtrOutput)
}

func (in *forwarderShouldPtr) ToForwarderShouldPtrOutputWithContext(ctx context.Context) ForwarderShouldPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(ForwarderShouldPtrOutput)
}

type InboxType string

const (
	// The inbox stores email with HTTP endpoints. Use this type for tests and webhooks.
	InboxTypeHttpInbox = InboxType("HTTP_INBOX")
	// The inbox receives email on a real SMTP mail server. Use this type for external senders.
	InboxTypeSmtpInbox = InboxType("SMTP_INBOX")
)

func (InboxType) ElementType() reflect.Type {
	return reflect.TypeOf((*InboxType)(nil)).Elem()
}

func (e InboxType) ToInboxTypeOutput() InboxTypeOutput {
	return pulumi.ToOutput(e).(InboxTypeOutput)
}

func (e InboxType) ToInboxTypeOutputWithContext(ctx context.Context) InboxTypeOutput {
	return pulumi.ToOutputWithContext(ctx, e).(InboxTypeOutput)
}

func (e InboxType) ToInboxTypePtrOutput() InboxTypePtrOutput {
	return e.ToInboxTypePtrOutputWithContext(context.Background())
}

func (e InboxType) ToInboxTypePtrOutputWithContext(ctx context.Context) InboxTypePtrOutput {
	return InboxType(e).ToInboxTypeOutputWithContext(ctx).ToInboxTypePtrOutputWithContext(ctx)
}

func (e InboxType) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e InboxType) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e InboxType) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e InboxType) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type InboxTypeOutput struct{ *pulumi.OutputState }

func (InboxTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*InboxType)(nil)).Elem()
}

func (o InboxTypeOutput) ToInboxTypeOutput() InboxTypeOutput {
	return o
}

func (o InboxTypeOutput) ToInboxTypeOutputWithContext(ctx context.Context) InboxTypeOutput {
	return o
}

func (o InboxTypeOutput) ToInboxTypePtrOutput() InboxTypePtrOutput {
	return o.ToInboxTypePtrOutputWithContext(context.Background())
}

func (o InboxTypeOutput) ToInboxTypePtrOutputWithContext(ctx context.Context) InboxTypePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v InboxType) *InboxType {
		return &v
	}).(InboxTypePtrOutput)
}

func (o InboxTypeOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o InboxTypeOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e InboxType) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o InboxTypeOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o InboxTypeOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e InboxType) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type InboxTypePtrOutput struct{ *pulumi.OutputState }

func (InboxTypePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**InboxType)(nil)).Elem()
}

func (o InboxTypePtrOutput) ToInboxTypePtrOutput() InboxTypePtrOutput {
	return o
}

func (o InboxTypePtrOutput) ToInboxTypePtrOutputWithContext(ctx context.Context) InboxTypePtrOutput {
	return o
}

func (o InboxTypePtrOutput) Elem() InboxTypeOutput {
	return o.ApplyT(func(v *InboxType) InboxType {
		if v != nil {
			return *v
		}
		var ret InboxType
		return ret
	}).(InboxTypeOutput)
}

func (o InboxTypePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o InboxTypePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *InboxType) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// InboxTypeInput is an input type that accepts values of the InboxType enum
// A concrete instance of `InboxTypeInput` can be one of the following:
//
//	InboxTypeHttpInbox
//	InboxTypeSmtpInbox
type InboxTypeInput interface {
	pulumi.Input

	ToInboxTypeOutput() InboxTypeOutput
	ToInboxTypeOutputWithContext(context.Context) InboxTypeOutput
}

var inboxTypePtrType = reflect.TypeOf((**InboxType)(nil)).Elem()

type InboxTypePtrInput interface {
	pulumi.Input

	ToInboxTypePtrOutput() InboxTypePtrOutput
	ToInboxTypePtrOutputWithContext(context.Context) InboxTypePtrOutput
}

type inboxTypePtr string

func InboxTypePtr(v string) InboxTypePtrInput {
	return (*inboxTypePtr)(&v)
}

func (*inboxTypePtr) ElementType() reflect.Type {
	return inboxTypePtrType
}

func (in *inboxTypePtr) ToInboxTypePtrOutput() InboxTypePtrOutput {
	return pulumi.ToOutput(in).(InboxTypePtrOutput)
}

func (in *inboxTypePtr) ToInboxTypePtrOutputWithContext(ctx context.Context) InboxTypePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(InboxTypePtrOutput)
}

type RulesetAction string

const (
	// MailSlurp stops the email when the target matches.
	RulesetActionBlock = RulesetAction("BLOCK")
	// MailSlurp permits the email when the target matches, and this action wins over a block.
	RulesetActionAllow = RulesetAction("ALLOW")
	// MailSlurp removes the matched address from the email, and the rest of the email continues.
	RulesetActionFilterRemove = RulesetAction("FILTER_REMOVE")
	// MailSlurp answers the sender with a soft bounce, which states a temporary failure.
	RulesetActionBounceSoft = RulesetAction("BOUNCE_SOFT")
	// MailSlurp answers the sender with a hard bounce, which states a permanent failure.
	RulesetActionBounceHard = RulesetAction("BOUNCE_HARD")
)

func (RulesetAction) ElementType() reflect.Type {
	return reflect.TypeOf((*RulesetAction)(nil)).Elem()
}

func (e RulesetAction) ToRulesetActionOutput() RulesetActionOutput {
	return pulumi.ToOutput(e).(RulesetActionOutput)
}

func (e RulesetAction) ToRulesetActionOutputWithContext(ctx context.Context) RulesetActionOutput {
	return pulumi.ToOutputWithContext(ctx, e).(RulesetActionOutput)
}

func (e RulesetAction) ToRulesetActionPtrOutput() RulesetActionPtrOutput {
	return e.ToRulesetActionPtrOutputWithContext(context.Background())
}

func (e RulesetAction) ToRulesetActionPtrOutputWithContext(ctx context.Context) RulesetActionPtrOutput {
	return RulesetAction(e).ToRulesetActionOutputWithContext(ctx).ToRulesetActionPtrOutputWithContext(ctx)
}

func (e RulesetAction) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e RulesetAction) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e RulesetAction) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e RulesetAction) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type RulesetActionOutput struct{ *pulumi.OutputState }

func (RulesetActionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RulesetAction)(nil)).Elem()
}

func (o RulesetActionOutput) ToRulesetActionOutput() RulesetActionOutput {
	return o
}

func (o RulesetActionOutput) ToRulesetActionOutputWithContext(ctx context.Context) RulesetActionOutput {
	return o
}

func (o RulesetActionOutput) ToRulesetActionPtrOutput() RulesetActionPtrOutput {
	return o.ToRulesetActionPtrOutputWithContext(context.Background())
}

func (o RulesetActionOutput) ToRulesetActionPtrOutputWithContext(ctx context.Context) RulesetActionPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RulesetAction) *RulesetAction {
		return &v
	}).(RulesetActionPtrOutput)
}

func (o RulesetActionOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o RulesetActionOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RulesetAction) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o RulesetActionOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RulesetActionOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RulesetAction) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type RulesetActionPtrOutput struct{ *pulumi.OutputState }

func (RulesetActionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RulesetAction)(nil)).Elem()
}

func (o RulesetActionPtrOutput) ToRulesetActionPtrOutput() RulesetActionPtrOutput {
	return o
}

func (o RulesetActionPtrOutput) ToRulesetActionPtrOutputWithContext(ctx context.Context) RulesetActionPtrOutput {
	return o
}

func (o RulesetActionPtrOutput) Elem() RulesetActionOutput {
	return o.ApplyT(func(v *RulesetAction) RulesetAction {
		if v != nil {
			return *v
		}
		var ret RulesetAction
		return ret
	}).(RulesetActionOutput)
}

func (o RulesetActionPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RulesetActionPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *RulesetAction) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// RulesetActionInput is an input type that accepts values of the RulesetAction enum
// A concrete instance of `RulesetActionInput` can be one of the following:
//
//	RulesetActionBlock
//	RulesetActionAllow
//	RulesetActionFilterRemove
//	RulesetActionBounceSoft
//	RulesetActionBounceHard
type RulesetActionInput interface {
	pulumi.Input

	ToRulesetActionOutput() RulesetActionOutput
	ToRulesetActionOutputWithContext(context.Context) RulesetActionOutput
}

var rulesetActionPtrType = reflect.TypeOf((**RulesetAction)(nil)).Elem()

type RulesetActionPtrInput interface {
	pulumi.Input

	ToRulesetActionPtrOutput() RulesetActionPtrOutput
	ToRulesetActionPtrOutputWithContext(context.Context) RulesetActionPtrOutput
}

type rulesetActionPtr string

func RulesetActionPtr(v string) RulesetActionPtrInput {
	return (*rulesetActionPtr)(&v)
}

func (*rulesetActionPtr) ElementType() reflect.Type {
	return rulesetActionPtrType
}

func (in *rulesetActionPtr) ToRulesetActionPtrOutput() RulesetActionPtrOutput {
	return pulumi.ToOutput(in).(RulesetActionPtrOutput)
}

func (in *rulesetActionPtr) ToRulesetActionPtrOutputWithContext(ctx context.Context) RulesetActionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(RulesetActionPtrOutput)
}

type RulesetScope string

const (
	// MailSlurp applies the ruleset to every email that the inbox receives.
	RulesetScopeReceivingEmails = RulesetScope("RECEIVING_EMAILS")
	// MailSlurp applies the ruleset to every email that the inbox sends.
	RulesetScopeSendingEmails = RulesetScope("SENDING_EMAILS")
	// MailSlurp applies the ruleset to every SMS message that a phone number receives.
	RulesetScopeReceivingSms = RulesetScope("RECEIVING_SMS")
	// MailSlurp applies the ruleset to every SMS message that a phone number sends.
	RulesetScopeSendingSms = RulesetScope("SENDING_SMS")
)

func (RulesetScope) ElementType() reflect.Type {
	return reflect.TypeOf((*RulesetScope)(nil)).Elem()
}

func (e RulesetScope) ToRulesetScopeOutput() RulesetScopeOutput {
	return pulumi.ToOutput(e).(RulesetScopeOutput)
}

func (e RulesetScope) ToRulesetScopeOutputWithContext(ctx context.Context) RulesetScopeOutput {
	return pulumi.ToOutputWithContext(ctx, e).(RulesetScopeOutput)
}

func (e RulesetScope) ToRulesetScopePtrOutput() RulesetScopePtrOutput {
	return e.ToRulesetScopePtrOutputWithContext(context.Background())
}

func (e RulesetScope) ToRulesetScopePtrOutputWithContext(ctx context.Context) RulesetScopePtrOutput {
	return RulesetScope(e).ToRulesetScopeOutputWithContext(ctx).ToRulesetScopePtrOutputWithContext(ctx)
}

func (e RulesetScope) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e RulesetScope) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e RulesetScope) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e RulesetScope) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type RulesetScopeOutput struct{ *pulumi.OutputState }

func (RulesetScopeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RulesetScope)(nil)).Elem()
}

func (o RulesetScopeOutput) ToRulesetScopeOutput() RulesetScopeOutput {
	return o
}

func (o RulesetScopeOutput) ToRulesetScopeOutputWithContext(ctx context.Context) RulesetScopeOutput {
	return o
}

func (o RulesetScopeOutput) ToRulesetScopePtrOutput() RulesetScopePtrOutput {
	return o.ToRulesetScopePtrOutputWithContext(context.Background())
}

func (o RulesetScopeOutput) ToRulesetScopePtrOutputWithContext(ctx context.Context) RulesetScopePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RulesetScope) *RulesetScope {
		return &v
	}).(RulesetScopePtrOutput)
}

func (o RulesetScopeOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o RulesetScopeOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RulesetScope) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o RulesetScopeOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RulesetScopeOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RulesetScope) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type RulesetScopePtrOutput struct{ *pulumi.OutputState }

func (RulesetScopePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RulesetScope)(nil)).Elem()
}

func (o RulesetScopePtrOutput) ToRulesetScopePtrOutput() RulesetScopePtrOutput {
	return o
}

func (o RulesetScopePtrOutput) ToRulesetScopePtrOutputWithContext(ctx context.Context) RulesetScopePtrOutput {
	return o
}

func (o RulesetScopePtrOutput) Elem() RulesetScopeOutput {
	return o.ApplyT(func(v *RulesetScope) RulesetScope {
		if v != nil {
			return *v
		}
		var ret RulesetScope
		return ret
	}).(RulesetScopeOutput)
}

func (o RulesetScopePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RulesetScopePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *RulesetScope) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// RulesetScopeInput is an input type that accepts values of the RulesetScope enum
// A concrete instance of `RulesetScopeInput` can be one of the following:
//
//	RulesetScopeReceivingEmails
//	RulesetScopeSendingEmails
//	RulesetScopeReceivingSms
//	RulesetScopeSendingSms
type RulesetScopeInput interface {
	pulumi.Input

	ToRulesetScopeOutput() RulesetScopeOutput
	ToRulesetScopeOutputWithContext(context.Context) RulesetScopeOutput
}

var rulesetScopePtrType = reflect.TypeOf((**RulesetScope)(nil)).Elem()

type RulesetScopePtrInput interface {
	pulumi.Input

	ToRulesetScopePtrOutput() RulesetScopePtrOutput
	ToRulesetScopePtrOutputWithContext(context.Context) RulesetScopePtrOutput
}

type rulesetScopePtr string

func RulesetScopePtr(v string) RulesetScopePtrInput {
	return (*rulesetScopePtr)(&v)
}

func (*rulesetScopePtr) ElementType() reflect.Type {
	return rulesetScopePtrType
}

func (in *rulesetScopePtr) ToRulesetScopePtrOutput() RulesetScopePtrOutput {
	return pulumi.ToOutput(in).(RulesetScopePtrOutput)
}

func (in *rulesetScopePtr) ToRulesetScopePtrOutputWithContext(ctx context.Context) RulesetScopePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(RulesetScopePtrOutput)
}

type WebhookEventName string

const (
	// MailSlurp sends the event when an inbox receives an email payload.
	WebhookEventNameEmailReceived = WebhookEventName("EMAIL_RECEIVED")
	// MailSlurp sends the event when an AI transformer produces a new extraction result.
	WebhookEventNameNewAiTransformResult = WebhookEventName("NEW_AI_TRANSFORM_RESULT")
	// MailSlurp sends the event when an inbox receives a new email.
	WebhookEventNameNewEmail = WebhookEventName("NEW_EMAIL")
	// MailSlurp sends the event when it creates a contact from inbound email activity.
	WebhookEventNameNewContact = WebhookEventName("NEW_CONTACT")
	// MailSlurp sends the event when it detects an attachment on a received email.
	WebhookEventNameNewAttachment = WebhookEventName("NEW_ATTACHMENT")
	// MailSlurp sends the event when it tracks an email open.
	WebhookEventNameEmailOpened = WebhookEventName("EMAIL_OPENED")
	// MailSlurp sends the event when a recipient reads an email.
	WebhookEventNameEmailRead = WebhookEventName("EMAIL_READ")
	// MailSlurp sends the event when the delivery status of a sent email changes.
	WebhookEventNameDeliveryStatus = WebhookEventName("DELIVERY_STATUS")
	// MailSlurp sends the event when an email bounces at the account level.
	WebhookEventNameBounce = WebhookEventName("BOUNCE")
	// MailSlurp sends the event when an email address bounces.
	WebhookEventNameBounceRecipient = WebhookEventName("BOUNCE_RECIPIENT")
	// MailSlurp sends the event when a phone number receives an SMS message.
	WebhookEventNameNewSms = WebhookEventName("NEW_SMS")
	// MailSlurp sends the event for a guest user.
	WebhookEventNameNewGuestUser = WebhookEventName("NEW_GUEST_USER")
)

func (WebhookEventName) ElementType() reflect.Type {
	return reflect.TypeOf((*WebhookEventName)(nil)).Elem()
}

func (e WebhookEventName) ToWebhookEventNameOutput() WebhookEventNameOutput {
	return pulumi.ToOutput(e).(WebhookEventNameOutput)
}

func (e WebhookEventName) ToWebhookEventNameOutputWithContext(ctx context.Context) WebhookEventNameOutput {
	return pulumi.ToOutputWithContext(ctx, e).(WebhookEventNameOutput)
}

func (e WebhookEventName) ToWebhookEventNamePtrOutput() WebhookEventNamePtrOutput {
	return e.ToWebhookEventNamePtrOutputWithContext(context.Background())
}

func (e WebhookEventName) ToWebhookEventNamePtrOutputWithContext(ctx context.Context) WebhookEventNamePtrOutput {
	return WebhookEventName(e).ToWebhookEventNameOutputWithContext(ctx).ToWebhookEventNamePtrOutputWithContext(ctx)
}

func (e WebhookEventName) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e WebhookEventName) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e WebhookEventName) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e WebhookEventName) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type WebhookEventNameOutput struct{ *pulumi.OutputState }

func (WebhookEventNameOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WebhookEventName)(nil)).Elem()
}

func (o WebhookEventNameOutput) ToWebhookEventNameOutput() WebhookEventNameOutput {
	return o
}

func (o WebhookEventNameOutput) ToWebhookEventNameOutputWithContext(ctx context.Context) WebhookEventNameOutput {
	return o
}

func (o WebhookEventNameOutput) ToWebhookEventNamePtrOutput() WebhookEventNamePtrOutput {
	return o.ToWebhookEventNamePtrOutputWithContext(context.Background())
}

func (o WebhookEventNameOutput) ToWebhookEventNamePtrOutputWithContext(ctx context.Context) WebhookEventNamePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v WebhookEventName) *WebhookEventName {
		return &v
	}).(WebhookEventNamePtrOutput)
}

func (o WebhookEventNameOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o WebhookEventNameOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e WebhookEventName) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o WebhookEventNameOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o WebhookEventNameOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e WebhookEventName) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type WebhookEventNamePtrOutput struct{ *pulumi.OutputState }

func (WebhookEventNamePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WebhookEventName)(nil)).Elem()
}

func (o WebhookEventNamePtrOutput) ToWebhookEventNamePtrOutput() WebhookEventNamePtrOutput {
	return o
}

func (o WebhookEventNamePtrOutput) ToWebhookEventNamePtrOutputWithContext(ctx context.Context) WebhookEventNamePtrOutput {
	return o
}

func (o WebhookEventNamePtrOutput) Elem() WebhookEventNameOutput {
	return o.ApplyT(func(v *WebhookEventName) WebhookEventName {
		if v != nil {
			return *v
		}
		var ret WebhookEventName
		return ret
	}).(WebhookEventNameOutput)
}

func (o WebhookEventNamePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o WebhookEventNamePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *WebhookEventName) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// WebhookEventNameInput is an input type that accepts values of the WebhookEventName enum
// A concrete instance of `WebhookEventNameInput` can be one of the following:
//
//	WebhookEventNameEmailReceived
//	WebhookEventNameNewAiTransformResult
//	WebhookEventNameNewEmail
//	WebhookEventNameNewContact
//	WebhookEventNameNewAttachment
//	WebhookEventNameEmailOpened
//	WebhookEventNameEmailRead
//	WebhookEventNameDeliveryStatus
//	WebhookEventNameBounce
//	WebhookEventNameBounceRecipient
//	WebhookEventNameNewSms
//	WebhookEventNameNewGuestUser
type WebhookEventNameInput interface {
	pulumi.Input

	ToWebhookEventNameOutput() WebhookEventNameOutput
	ToWebhookEventNameOutputWithContext(context.Context) WebhookEventNameOutput
}

var webhookEventNamePtrType = reflect.TypeOf((**WebhookEventName)(nil)).Elem()

type WebhookEventNamePtrInput interface {
	pulumi.Input

	ToWebhookEventNamePtrOutput() WebhookEventNamePtrOutput
	ToWebhookEventNamePtrOutputWithContext(context.Context) WebhookEventNamePtrOutput
}

type webhookEventNamePtr string

func WebhookEventNamePtr(v string) WebhookEventNamePtrInput {
	return (*webhookEventNamePtr)(&v)
}

func (*webhookEventNamePtr) ElementType() reflect.Type {
	return webhookEventNamePtrType
}

func (in *webhookEventNamePtr) ToWebhookEventNamePtrOutput() WebhookEventNamePtrOutput {
	return pulumi.ToOutput(in).(WebhookEventNamePtrOutput)
}

func (in *webhookEventNamePtr) ToWebhookEventNamePtrOutputWithContext(ctx context.Context) WebhookEventNamePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(WebhookEventNamePtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ForwarderFieldInput)(nil)).Elem(), ForwarderField("RECIPIENTS"))
	pulumi.RegisterInputType(reflect.TypeOf((*ForwarderFieldPtrInput)(nil)).Elem(), ForwarderField("RECIPIENTS"))
	pulumi.RegisterInputType(reflect.TypeOf((*ForwarderMatchOperatorInput)(nil)).Elem(), ForwarderMatchOperator("AND"))
	pulumi.RegisterInputType(reflect.TypeOf((*ForwarderMatchOperatorPtrInput)(nil)).Elem(), ForwarderMatchOperator("AND"))
	pulumi.RegisterInputType(reflect.TypeOf((*ForwarderShouldInput)(nil)).Elem(), ForwarderShould("WILDCARD"))
	pulumi.RegisterInputType(reflect.TypeOf((*ForwarderShouldPtrInput)(nil)).Elem(), ForwarderShould("WILDCARD"))
	pulumi.RegisterInputType(reflect.TypeOf((*InboxTypeInput)(nil)).Elem(), InboxType("HTTP_INBOX"))
	pulumi.RegisterInputType(reflect.TypeOf((*InboxTypePtrInput)(nil)).Elem(), InboxType("HTTP_INBOX"))
	pulumi.RegisterInputType(reflect.TypeOf((*RulesetActionInput)(nil)).Elem(), RulesetAction("BLOCK"))
	pulumi.RegisterInputType(reflect.TypeOf((*RulesetActionPtrInput)(nil)).Elem(), RulesetAction("BLOCK"))
	pulumi.RegisterInputType(reflect.TypeOf((*RulesetScopeInput)(nil)).Elem(), RulesetScope("RECEIVING_EMAILS"))
	pulumi.RegisterInputType(reflect.TypeOf((*RulesetScopePtrInput)(nil)).Elem(), RulesetScope("RECEIVING_EMAILS"))
	pulumi.RegisterInputType(reflect.TypeOf((*WebhookEventNameInput)(nil)).Elem(), WebhookEventName("EMAIL_RECEIVED"))
	pulumi.RegisterInputType(reflect.TypeOf((*WebhookEventNamePtrInput)(nil)).Elem(), WebhookEventName("EMAIL_RECEIVED"))
	pulumi.RegisterOutputType(DomainTypeOutput{})
	pulumi.RegisterOutputType(DomainTypePtrOutput{})
	pulumi.RegisterOutputType(ForwarderFieldOutput{})
	pulumi.RegisterOutputType(ForwarderFieldPtrOutput{})
	pulumi.RegisterOutputType(ForwarderMatchOperatorOutput{})
	pulumi.RegisterOutputType(ForwarderMatchOperatorPtrOutput{})
	pulumi.RegisterOutputType(ForwarderShouldOutput{})
	pulumi.RegisterOutputType(ForwarderShouldPtrOutput{})
	pulumi.RegisterOutputType(InboxTypeOutput{})
	pulumi.RegisterOutputType(InboxTypePtrOutput{})
	pulumi.RegisterOutputType(RulesetActionOutput{})
	pulumi.RegisterOutputType(RulesetActionPtrOutput{})
	pulumi.RegisterOutputType(RulesetScopeOutput{})
	pulumi.RegisterOutputType(RulesetScopePtrOutput{})
	pulumi.RegisterOutputType(WebhookEventNameOutput{})
	pulumi.RegisterOutputType(WebhookEventNamePtrOutput{})
}
