// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mailslurp

import (
	"context"
	"reflect"

	"github.com/jschady/pulumi-mailslurp/sdk/go/mailslurp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type DomainNameRecordResult struct {
	// The values to use when your DNS provider rejects the main entries.
	AlternativeRecordEntries []string `pulumi:"alternativeRecordEntries"`
	// The role of the record, for example `VERIFICATION` or `DKIM`.
	Label string `pulumi:"label"`
	// The full DNS name of the record.
	Name string `pulumi:"name"`
	// The values of the record. Add one entry for each value.
	RecordEntries []string `pulumi:"recordEntries"`
	// The DNS record type, for example `TXT`, `MX`, or `CNAME`.
	RecordType string `pulumi:"recordType"`
	// MailSlurp reports whether the domain needs this record.
	Required bool `pulumi:"required"`
	// The time to live of the record, in seconds.
	Ttl int `pulumi:"ttl"`
}

type DomainNameRecordResultOutput struct{ *pulumi.OutputState }

func (DomainNameRecordResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainNameRecordResult)(nil)).Elem()
}

func (o DomainNameRecordResultOutput) ToDomainNameRecordResultOutput() DomainNameRecordResultOutput {
	return o
}

func (o DomainNameRecordResultOutput) ToDomainNameRecordResultOutputWithContext(ctx context.Context) DomainNameRecordResultOutput {
	return o
}

// The values to use when your DNS provider rejects the main entries.
func (o DomainNameRecordResultOutput) AlternativeRecordEntries() pulumi.StringArrayOutput {
	return o.ApplyT(func(v DomainNameRecordResult) []string { return v.AlternativeRecordEntries }).(pulumi.StringArrayOutput)
}

// The role of the record, for example `VERIFICATION` or `DKIM`.
func (o DomainNameRecordResultOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v DomainNameRecordResult) string { return v.Label }).(pulumi.StringOutput)
}

// The full DNS name of the record.
func (o DomainNameRecordResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v DomainNameRecordResult) string { return v.Name }).(pulumi.StringOutput)
}

// The values of the record. Add one entry for each value.
func (o DomainNameRecordResultOutput) RecordEntries() pulumi.StringArrayOutput {
	return o.ApplyT(func(v DomainNameRecordResult) []string { return v.RecordEntries }).(pulumi.StringArrayOutput)
}

// The DNS record type, for example `TXT`, `MX`, or `CNAME`.
func (o DomainNameRecordResultOutput) RecordType() pulumi.StringOutput {
	return o.ApplyT(func(v DomainNameRecordResult) string { return v.RecordType }).(pulumi.StringOutput)
}

// MailSlurp reports whether the domain needs this record.
func (o DomainNameRecordResultOutput) Required() pulumi.BoolOutput {
	return o.ApplyT(func(v DomainNameRecordResult) bool { return v.Required }).(pulumi.BoolOutput)
}

// The time to live of the record, in seconds.
func (o DomainNameRecordResultOutput) Ttl() pulumi.IntOutput {
	return o.ApplyT(func(v DomainNameRecordResult) int { return v.Ttl }).(pulumi.IntOutput)
}

type DomainNameRecordResultArrayOutput struct{ *pulumi.OutputState }

func (DomainNameRecordResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DomainNameRecordResult)(nil)).Elem()
}

func (o DomainNameRecordResultArrayOutput) ToDomainNameRecordResultArrayOutput() DomainNameRecordResultArrayOutput {
	return o
}

func (o DomainNameRecordResultArrayOutput) ToDomainNameRecordResultArrayOutputWithContext(ctx context.Context) DomainNameRecordResultArrayOutput {
	return o
}

func (o DomainNameRecordResultArrayOutput) Index(i pulumi.IntInput) DomainNameRecordResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DomainNameRecordResult {
		return vs[0].([]DomainNameRecordResult)[vs[1].(int)]
	}).(DomainNameRecordResultOutput)
}

type EmailTemplateVariable struct {
	// The name of the variable, without the moustache markers.
	Name string `pulumi:"name"`
	// The type of the variable. The API reports one value, `STRING`.
	VariableType string `pulumi:"variableType"`
}

type EmailTemplateVariableOutput struct{ *pulumi.OutputState }

func (EmailTemplateVariableOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*EmailTemplateVariable)(nil)).Elem()
}

func (o EmailTemplateVariableOutput) ToEmailTemplateVariableOutput() EmailTemplateVariableOutput {
	return o
}

func (o EmailTemplateVariableOutput) ToEmailTemplateVariableOutputWithContext(ctx context.Context) EmailTemplateVariableOutput {
	return o
}

// The name of the variable, without the moustache markers.
func (o EmailTemplateVariableOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v EmailTemplateVariable) string { return v.Name }).(pulumi.StringOutput)
}

// The type of the variable. The API reports one value, `STRING`.
func (o EmailTemplateVariableOutput) VariableType() pulumi.StringOutput {
	return o.ApplyT(func(v EmailTemplateVariable) string { return v.VariableType }).(pulumi.StringOutput)
}

type EmailTemplateVariableArrayOutput struct{ *pulumi.OutputState }

func (EmailTemplateVariableArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]EmailTemplateVariable)(nil)).Elem()
}

func (o EmailTemplateVariableArrayOutput) ToEmailTemplateVariableArrayOutput() EmailTemplateVariableArrayOutput {
	return o
}

func (o EmailTemplateVariableArrayOutput) ToEmailTemplateVariableArrayOutputWithContext(ctx context.Context) EmailTemplateVariableArrayOutput {
	return o
}

func (o EmailTemplateVariableArrayOutput) Index(i pulumi.IntInput) EmailTemplateVariableOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) EmailTemplateVariable {
		return vs[0].([]EmailTemplateVariable)[vs[1].(int)]
	}).(EmailTemplateVariableOutput)
}

type InboxForwarderMatchGroup struct {
	// The groups that this group holds. Put a group inside a group to build a
	// deeper tree.
	Groups []InboxForwarderMatchGroup `pulumi:"groups"`
	// The rules that MailSlurp applies to the email.
	Matches []InboxForwarderMatchRule `pulumi:"matches"`
	// The way that MailSlurp joins the rules of this group. Use `AND` when
	// every rule must match. Use `OR` when one rule is enough.
	Operator ForwarderMatchOperator `pulumi:"operator"`
}

// InboxForwarderMatchGroupInput is an input type that accepts InboxForwarderMatchGroupArgs and InboxForwarderMatchGroupOutput values.
// You can construct a concrete instance of `InboxForwarderMatchGroupInput` via:
//
//	InboxForwarderMatchGroupArgs{...}
type InboxForwarderMatchGroupInput interface {
	pulumi.Input

	ToInboxForwarderMatchGroupOutput() InboxForwarderMatchGroupOutput
	ToInboxForwarderMatchGroupOutputWithContext(context.Context) InboxForwarderMatchGroupOutput
}

type InboxForwarderMatchGroupArgs struct {
	// The groups that this group holds. Put a group inside a group to build a
	// deeper tree.
	Groups InboxForwarderMatchGroupArrayInput `pulumi:"groups"`
	// The rules that MailSlurp applies to the email.
	Matches InboxForwarderMatchRuleArrayInput `pulumi:"matches"`
	// The way that MailSlurp joins the rules of this group. Use `AND` when
	// every rule must match. Use `OR` when one rule is enough.
	Operator ForwarderMatchOperatorInput `pulumi:"operator"`
}

func (InboxForwarderMatchGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*InboxForwarderMatchGroup)(nil)).Elem()
}

func (i InboxForwarderMatchGroupArgs) ToInboxForwarderMatchGroupOutput() InboxForwarderMatchGroupOutput {
	return i.ToInboxForwarderMatchGroupOutputWithContext(context.Background())
}

func (i InboxForwarderMatchGroupArgs) ToInboxForwarderMatchGroupOutputWithContext(ctx context.Context) InboxForwarderMatchGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InboxForwarderMatchGroupOutput)
}

func (i InboxForwarderMatchGroupArgs) ToInboxForwarderMatchGroupPtrOutput() InboxForwarderMatchGroupPtrOutput {
	return i.ToInboxForwarderMatchGroupPtrOutputWithContext(context.Background())
}

func (i InboxForwarderMatchGroupArgs) ToInboxForwarderMatchGroupPtrOutputWithContext(ctx context.Context) InboxForwarderMatchGroupPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InboxForwarderMatchGroupOutput).ToInboxForwarderMatchGroupPtrOutputWithContext(ctx)
}

// InboxForwarderMatchGroupPtrInput is an input type that accepts InboxForwarderMatchGroupArgs, InboxForwarderMatchGroupPtr and InboxForwarderMatchGroupPtrOutput values.
// You can construct a concrete instance of `InboxForwarderMatchGroupPtrInput` via:
//
//	        InboxForwarderMatchGroupArgs{...}
//
//	or:
//
//	        nil
type InboxForwarderMatchGroupPtrInput interface {
	pulumi.Input

	ToInboxForwarderMatchGroupPtrOutput() InboxForwarderMatchGroupPtrOutput
	ToInboxForwarderMatchGroupPtrOutputWithContext(context.Context) InboxForwarderMatchGroupPtrOutput
}

type inboxForwarderMatchGroupPtrType InboxForwarderMatchGroupArgs

func InboxForwarderMatchGroupPtr(v *InboxForwarderMatchGroupArgs) InboxForwarderMatchGroupPtrInput {
	return (*inboxForwarderMatchGroupPtrType)(v)
}

func (*inboxForwarderMatchGroupPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**InboxForwarderMatchGroup)(nil)).Elem()
}

func (i *inboxForwarderMatchGroupPtrType) ToInboxForwarderMatchGroupPtrOutput() InboxForwarderMatchGroupPtrOutput {
	return i.ToInboxForwarderMatchGroupPtrOutputWithContext(context.Background())
}

func (i *inboxForwarderMatchGroupPtrType) ToInboxForwarderMatchGroupPtrOutputWithContext(ctx context.Context) InboxForwarderMatchGroupPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InboxForwarderMatchGroupPtrOutput)
}

// InboxForwarderMatchGroupArrayInput is an input type that accepts InboxForwarderMatchGroupArray and InboxForwarderMatchGroupArrayOutput values.
// You can construct a concrete instance of `InboxForwarderMatchGroupArrayInput` via:
//
//	InboxForwarderMatchGroupArray{ InboxForwarderMatchGroupArgs{...} }
type InboxForwarderMatchGroupArrayInput interface {
	pulumi.Input

	ToInboxForwarderMatchGroupArrayOutput() InboxForwarderMatchGroupArrayOutput
	ToInboxForwarderMatchGroupArrayOutputWithContext(context.Context) InboxForwarderMatchGroupArrayOutput
}

type InboxForwarderMatchGroupArray []InboxForwarderMatchGroupInput

func (InboxForwarderMatchGroupArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InboxForwarderMatchGroup)(nil)).Elem()
}

func (i InboxForwarderMatchGroupArray) ToInboxForwarderMatchGroupArrayOutput() InboxForwarderMatchGroupArrayOutput {
	return i.ToInboxForwarderMatchGroupArrayOutputWithContext(context.Background())
}

func (i InboxForwarderMatchGroupArray) ToInboxForwarderMatchGroupArrayOutputWithContext(ctx context.Context) InboxForwarderMatchGroupArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InboxForwarderMatchGroupArrayOutput)
}

type InboxForwarderMatchGroupOutput struct{ *pulumi.OutputState }

func (InboxForwarderMatchGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*InboxForwarderMatchGroup)(nil)).Elem()
}

func (o InboxForwarderMatchGroupOutput) ToInboxForwarderMatchGroupOutput() InboxForwarderMatchGroupOutput {
	return o
}

func (o InboxForwarderMatchGroupOutput) ToInboxForwarderMatchGroupOutputWithContext(ctx context.Context) InboxForwarderMatchGroupOutput {
	return o
}

func (o InboxForwarderMatchGroupOutput) ToInboxForwarderMatchGroupPtrOutput() InboxForwarderMatchGroupPtrOutput {
	return o.ToInboxForwarderMatchGroupPtrOutputWithContext(context.Background())
}

func (o InboxForwarderMatchGroupOutput) ToInboxForwarderMatchGroupPtrOutputWithContext(ctx context.Context) InboxForwarderMatchGroupPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v InboxForwarderMatchGroup) *InboxForwarderMatchGroup {
		return &v
	}).(InboxForwarderMatchGroupPtrOutput)
}

// The groups that this group holds. Put a group inside a group to build a
// deeper tree.
func (o InboxForwarderMatchGroupOutput) Groups() InboxForwarderMatchGroupArrayOutput {
	return o.ApplyT(func(v InboxForwarderMatchGroup) []InboxForwarderMatchGroup { return v.Groups }).(InboxForwarderMatchGroupArrayOutput)
}

// The rules that MailSlurp applies to the email.
func (o InboxForwarderMatchGroupOutput) Matches() InboxForwarderMatchRuleArrayOutput {
	return o.ApplyT(func(v InboxForwarderMatchGroup) []InboxForwarderMatchRule { return v.Matches }).(InboxForwarderMatchRuleArrayOutput)
}

// The way that MailSlurp joins the rules of this group. Use `AND` when
// every rule must match. Use `OR` when one rule is enough.
func (o InboxForwarderMatchGroupOutput) Operator() ForwarderMatchOperatorOutput {
	return o.ApplyT(func(v InboxForwarderMatchGroup) ForwarderMatchOperator { return v.Operator }).(ForwarderMatchOperatorOutput)
}

type InboxForwarderMatchGroupPtrOutput struct{ *pulumi.OutputState }

func (InboxForwarderMatchGroupPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**InboxForwarderMatchGroup)(nil)).Elem()
}

func (o InboxForwarderMatchGroupPtrOutput) ToInboxForwarderMatchGroupPtrOutput() InboxForwarderMatchGroupPtrOutput {
	return o
}

func (o InboxForwarderMatchGroupPtrOutput) ToInboxForwarderMatchGroupPtrOutputWithContext(ctx context.Context) InboxForwarderMatchGroupPtrOutput {
	return o
}

func (o InboxForwarderMatchGroupPtrOutput) Elem() InboxForwarderMatchGroupOutput {
	return o.ApplyT(func(v *InboxForwarderMatchGroup) InboxForwarderMatchGroup {
		if v != nil {
			return *v
		}
		var ret InboxForwarderMatchGroup
		return ret
	}).(InboxForwarderMatchGroupOutput)
}

// The groups that this group holds. Put a group inside a group to build a
// deeper tree.
func (o InboxForwarderMatchGroupPtrOutput) Groups() InboxForwarderMatchGroupArrayOutput {
	return o.ApplyT(func(v *InboxForwarderMatchGroup) []InboxForwarderMatchGroup {
		if v == nil {
			return nil
		}
		return v.Groups
	}).(InboxForwarderMatchGroupArrayOutput)
}

// The rules that MailSlurp applies to the email.
func (o InboxForwarderMatchGroupPtrOutput) Matches() InboxForwarderMatchRuleArrayOutput {
	return o.ApplyT(func(v *InboxForwarderMatchGroup) []InboxForwarderMatchRule {
		if v == nil {
			return nil
		}
		return v.Matches
	}).(InboxForwarderMatchRuleArrayOutput)
}

// The way that MailSlurp joins the rules of this group. Use `AND` when
// every rule must match. Use `OR` when one rule is enough.
func (o InboxForwarderMatchGroupPtrOutput) Operator() ForwarderMatchOperatorPtrOutput {
	return o.ApplyT(func(v *InboxForwarderMatchGroup) *ForwarderMatchOperator {
		if v == nil {
			return nil
		}
		return &v.Operator
	}).(ForwarderMatchOperatorPtrOutput)
}

type InboxForwarderMatchGroupArrayOutput struct{ *pulumi.OutputState }

func (InboxForwarderMatchGroupArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InboxForwarderMatchGroup)(nil)).Elem()
}

func (o InboxForwarderMatchGroupArrayOutput) ToInboxForwarderMatchGroupArrayOutput() InboxForwarderMatchGroupArrayOutput {
	return o
}

func (o InboxForwarderMatchGroupArrayOutput) ToInboxForwarderMatchGroupArrayOutputWithContext(ctx context.Context) InboxForwarderMatchGroupArrayOutput {
	return o
}

func (o InboxForwarderMatchGroupArrayOutput) Index(i pulumi.IntInput) InboxForwarderMatchGroupOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) InboxForwarderMatchGroup {
		return vs[0].([]InboxForwarderMatchGroup)[vs[1].(int)]
	}).(InboxForwarderMatchGroupOutput)
}

type InboxForwarderMatchRule struct {
	// The part of the email that MailSlurp compares against the `value` property.
	Field ForwarderField `pulumi:"field"`
	// The way that MailSlurp compares the `value` property.
	Should ForwarderShould `pulumi:"should"`
	// The value or the pattern that MailSlurp compares.
	Value string `pulumi:"value"`
}

// InboxForwarderMatchRuleInput is an input type that accepts InboxForwarderMatchRuleArgs and InboxForwarderMatchRuleOutput values.
// You can construct a concrete instance of `InboxForwarderMatchRuleInput` via:
//
//	InboxForwarderMatchRuleArgs{...}
type InboxForwarderMatchRuleInput interface {
	pulumi.Input

	ToInboxForwarderMatchRuleOutput() InboxForwarderMatchRuleOutput
	ToInboxForwarderMatchRuleOutputWithContext(context.Context) InboxForwarderMatchRuleOutput
}

type InboxForwarderMatchRuleArgs struct {
	// The part of the email that MailSlurp compares against the `value` property.
	Field ForwarderFieldInput `pulumi:"field"`
	// The way that MailSlurp compares the `value` property.
	Should ForwarderShouldInput `pulumi:"should"`
	// The value or the pattern that MailSlurp compares.
	Value pulumi.StringInput `pulumi:"value"`
}

func (InboxForwarderMatchRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*InboxForwarderMatchRule)(nil)).Elem()
}

func (i InboxForwarderMatchRuleArgs) ToInboxForwarderMatchRuleOutput() InboxForwarderMatchRuleOutput {
	return i.ToInboxForwarderMatchRuleOutputWithContext(context.Background())
}

func (i InboxForwarderMatchRuleArgs) ToInboxForwarderMatchRuleOutputWithContext(ctx context.Context) InboxForwarderMatchRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InboxForwarderMatchRuleOutput)
}

// InboxForwarderMatchRuleArrayInput is an input type that accepts InboxForwarderMatchRuleArray and InboxForwarderMatchRuleArrayOutput values.
// You can construct a concrete instance of `InboxForwarderMatchRuleArrayInput` via:
//
//	InboxForwarderMatchRuleArray{ InboxForwarderMatchRuleArgs{...} }
type InboxForwarderMatchRuleArrayInput interface {
	pulumi.Input

	ToInboxForwarderMatchRuleArrayOutput() InboxForwarderMatchRuleArrayOutput
	ToInboxForwarderMatchRuleArrayOutputWithContext(context.Context) InboxForwarderMatchRuleArrayOutput
}

type InboxForwarderMatchRuleArray []InboxForwarderMatchRuleInput

func (InboxForwarderMatchRuleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InboxForwarderMatchRule)(nil)).Elem()
}

func (i InboxForwarderMatchRuleArray) ToInboxForwarderMatchRuleArrayOutput() InboxForwarderMatchRuleArrayOutput {
	return i.ToInboxForwarderMatchRuleArrayOutputWithContext(context.Background())
}

func (i InboxForwarderMatchRuleArray) ToInboxForwarderMatchRuleArrayOutputWithContext(ctx context.Context) InboxForwarderMatchRuleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InboxForwarderMatchRuleArrayOutput)
}

type InboxForwarderMatchRuleOutput struct{ *pulumi.OutputState }

func (InboxForwarderMatchRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*InboxForwarderMatchRule)(nil)).Elem()
}

func (o InboxForwarderMatchRuleOutput) ToInboxForwarderMatchRuleOutput() InboxForwarderMatchRuleOutput {
	return o
}

func (o InboxForwarderMatchRuleOutput) ToInboxForwarderMatchRuleOutputWithContext(ctx context.Context) InboxForwarderMatchRuleOutput {
	return o
}

// The part of the email that MailSlurp compares against the `value` property.
func (o InboxForwarderMatchRuleOutput) Field() ForwarderFieldOutput {
	return o.ApplyT(func(v InboxForwarderMatchRule) ForwarderField { return v.Field }).(ForwarderFieldOutput)
}

// The way that MailSlurp compares the `value` property.
func (o InboxForwarderMatchRuleOutput) Should() ForwarderShouldOutput {
	return o.ApplyT(func(v InboxForwarderMatchRule) ForwarderShould { return v.Should }).(ForwarderShouldOutput)
}

// The value or the pattern that MailSlurp compares.
func (o InboxForwarderMatchRuleOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v InboxForwarderMatchRule) string { return v.Value }).(pulumi.StringOutput)
}

type InboxForwarderMatchRuleArrayOutput struct{ *pulumi.OutputState }

func (InboxForwarderMatchRuleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]InboxForwarderMatchRule)(nil)).Elem()
}

func (o InboxForwarderMatchRuleArrayOutput) ToInboxForwarderMatchRuleArrayOutput() InboxForwarderMatchRuleArrayOutput {
	return o
}

func (o InboxForwarderMatchRuleArrayOutput) ToInboxForwarderMatchRuleArrayOutputWithContext(ctx context.Context) InboxForwarderMatchRuleArrayOutput {
	return o
}

func (o InboxForwarderMatchRuleArrayOutput) Index(i pulumi.IntInput) InboxForwarderMatchRuleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) InboxForwarderMatchRule {
		return vs[0].([]InboxForwarderMatchRule)[vs[1].(int)]
	}).(InboxForwarderMatchRuleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InboxForwarderMatchGroupInput)(nil)).Elem(), InboxForwarderMatchGroupArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*InboxForwarderMatchGroupPtrInput)(nil)).Elem(), InboxForwarderMatchGroupArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*InboxForwarderMatchGroupArrayInput)(nil)).Elem(), InboxForwarderMatchGroupArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*InboxForwarderMatchRuleInput)(nil)).Elem(), InboxForwarderMatchRuleArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*InboxForwarderMatchRuleArrayInput)(nil)).Elem(), InboxForwarderMatchRuleArray{})
	pulumi.RegisterOutputType(DomainNameRecordResultOutput{})
	pulumi.RegisterOutputType(DomainNameRecordResultArrayOutput{})
	pulumi.RegisterOutputType(EmailTemplateVariableOutput{})
	pulumi.RegisterOutputType(EmailTemplateVariableArrayOutput{})
	pulumi.RegisterOutputType(InboxForwarderMatchGroupOutput{})
	pulumi.RegisterOutputType(InboxForwarderMatchGroupPtrOutput{})
	pulumi.RegisterOutputType(InboxForwarderMatchGroupArrayOutput{})
	pulumi.RegisterOutputType(InboxForwarderMatchRuleOutput{})
	pulumi.RegisterOutputType(InboxForwarderMatchRuleArrayOutput{})
}
