// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mailslurp

import (
	"context"
	"reflect"

	"errors"
	"github.com/jschady/pulumi-mailslurp/sdk/go/mailslurp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A webhook that MailSlurp calls when an event happens. MailSlurp posts the
// event payload to the URL that you set.
//
// You can update every property of the webhook in place. Pulumi never
// replaces a webhook. A webhook that names no inbox listens to every inbox
// in the account. If you set the `inboxId` property, the webhook listens to
// that one inbox.
//
// This resource does not carry the `basicAuth` property of the API. The API
// reports the property as a boolean, so Pulumi cannot compare the user name
// and the password that it sent. The webhook list of the API also reports
// both values as plain text. Use the `includeHeaders` property to
// authenticate the request.
//
// ## Example Usage
// ### A webhook that posts every new email of one inbox to your server
// ```go
// package main
//
// import (
//
//	"github.com/jschady/pulumi-mailslurp/sdk/go/mailslurp"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			alertInbox, err := mailslurp.NewInbox(ctx, "alert-inbox", &mailslurp.InboxArgs{
//				Name: pulumi.String("alert-inbox"),
//			})
//			if err != nil {
//				return err
//			}
//			newEmailHook, err := mailslurp.NewWebhook(ctx, "new-email-hook", &mailslurp.WebhookArgs{
//				EventName: mailslurp.WebhookEventNameNewEmail,
//				InboxId:   alertInbox.ID().ToIDOutput().ToStringOutput(),
//				Name:      pulumi.String("new-email-hook"),
//				Url:       pulumi.String("https://example.com/mailslurp/new-email"),
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("webhookId", newEmailHook.ID())
//			return nil
//		})
//	}
//
// ```
type Webhook struct {
	pulumi.CustomResourceState

	// The time when MailSlurp created the webhook.
	CreatedAt pulumi.StringPtrOutput `pulumi:"createdAt"`
	// MailSlurp reports whether the webhook is enabled. The API does not
	// document this property, and the value can be empty.
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// The event that triggers the webhook.
	EventName WebhookEventNameOutput `pulumi:"eventName"`
	// The health of the webhook, as MailSlurp computes it. The value is
	// `HEALTHY` or `UNHEALTHY`. The value changes often, so Pulumi never
	// compares it.
	HealthStatus pulumi.StringPtrOutput `pulumi:"healthStatus"`
	// MailSlurp reports whether it accepts an insecure SSL certificate on your server.
	IgnoreInsecureSslCertificates pulumi.BoolOutput `pulumi:"ignoreInsecureSslCertificates"`
	// The inbox that triggers the webhook. An empty value means that every
	// inbox in the account triggers the webhook.
	InboxId pulumi.StringPtrOutput `pulumi:"inboxId"`
	// The HTTP headers that MailSlurp sends with each webhook request. The API
	// names this value `requestHeaders` when it reports it.
	IncludeHeaders pulumi.StringMapOutput `pulumi:"includeHeaders"`
	// The HTTP method that your server must accept. MailSlurp sends `POST`.
	Method pulumi.StringOutput `pulumi:"method"`
	// The display name of the webhook.
	Name pulumi.StringPtrOutput `pulumi:"name"`
	// The template for the JSON body of the webhook request.
	RequestBodyTemplate pulumi.StringPtrOutput `pulumi:"requestBodyTemplate"`
	// The URL that MailSlurp posts the event payload to.
	Url pulumi.StringOutput `pulumi:"url"`
	// MailSlurp reports whether it calls your server from its static IP range.
	UseStaticIpRange pulumi.BoolOutput `pulumi:"useStaticIpRange"`
}

// NewWebhook registers a new resource with the given unique name, arguments, and options.
func NewWebhook(ctx *pulumi.Context,
	name string, args *WebhookArgs, opts ...pulumi.ResourceOption) (*Webhook, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Url == nil {
		return nil, errors.New("invalid value for required argument 'Url'")
	}
	if args.IncludeHeaders != nil {
		args.IncludeHeaders = pulumi.ToSecret(args.IncludeHeaders).(pulumi.StringMapInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"includeHeaders",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Webhook
	err := ctx.RegisterResource("mailslurp:index:Webhook", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWebhook gets an existing Webhook resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWebhook(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WebhookState, opts ...pulumi.ResourceOption) (*Webhook, error) {
	var resource Webhook
	err := ctx.ReadResource("mailslurp:index:Webhook", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Webhook resources.
type webhookState struct {
}

type WebhookState struct {
}

func (WebhookState) ElementType() reflect.Type {
	return reflect.TypeOf((*webhookState)(nil)).Elem()
}

type webhookArgs struct {
	// The event that triggers the webhook. If you do not set this property,
	// MailSlurp sends the `EMAIL_RECEIVED` event.
	EventName *WebhookEventName `pulumi:"eventName"`
	// If you set this property, MailSlurp accepts an insecure SSL certificate
	// on your server. Use it for a self-signed certificate. The default value
	// is false.
	IgnoreInsecureSslCertificates *bool `pulumi:"ignoreInsecureSslCertificates"`
	// The inbox that triggers the webhook. If you do not set this property,
	// every inbox in the account triggers the webhook. You can move the webhook
	// to another inbox in place. You cannot remove this property after you set
	// it, because the API has no value for the account.
	InboxId *string `pulumi:"inboxId"`
	// The HTTP headers that MailSlurp sends with each webhook request. Each key
	// is a header name, and each value is the header value. The provider marks
	// the values as secret. MailSlurp reports the values as plain text, so
	// anyone with the API key can read them.
	IncludeHeaders map[string]string `pulumi:"includeHeaders"`
	// The display name of the webhook. You can update this property in place.
	// Remove the property to clear the name.
	Name *string `pulumi:"name"`
	// A template for the JSON body of the webhook request. Use `{{variableName}}`
	// markers to insert values from the event payload.
	RequestBodyTemplate *string `pulumi:"requestBodyTemplate"`
	// The tags on the webhook. MailSlurp accepts the tags and never reports
	// them, so Pulumi cannot compare this property. A change to the tags alone
	// plans no update.
	Tags []string `pulumi:"tags"`
	// The URL that MailSlurp posts the event payload to. Your server must
	// accept the request. You can update this property in place.
	Url string `pulumi:"url"`
	// If you set this property, MailSlurp calls your server from its static IP
	// range. The default value is false.
	UseStaticIpRange *bool `pulumi:"useStaticIpRange"`
}

// The set of arguments for constructing a Webhook resource.
type WebhookArgs struct {
	// The event that triggers the webhook. If you do not set this property,
	// MailSlurp sends the `EMAIL_RECEIVED` event.
	EventName WebhookEventNamePtrInput
	// If you set this property, MailSlurp accepts an insecure SSL certificate
	// on your server. Use it for a self-signed certificate. The default value
	// is false.
	IgnoreInsecureSslCertificates pulumi.BoolPtrInput
	// The inbox that triggers the webhook. If you do not set this property,
	// every inbox in the account triggers the webhook. You can move the webhook
	// to another inbox in place. You cannot remove this property after you set
	// it, because the API has no value for the account.
	InboxId pulumi.StringPtrInput
	// The HTTP headers that MailSlurp sends with each webhook request. Each key
	// is a header name, and each value is the header value. The provider marks
	// the values as secret. MailSlurp reports the values as plain text, so
	// anyone with the API key can read them.
	IncludeHeaders pulumi.StringMapInput
	// The display name of the webhook. You can update this property in place.
	// Remove the property to clear the name.
	Name pulumi.StringPtrInput
	// A template for the JSON body of the webhook request. Use `{{variableName}}`
	// markers to insert values from the event payload.
	RequestBodyTemplate pulumi.StringPtrInput
	// The tags on the webhook. MailSlurp accepts the tags and never reports
	// them, so Pulumi cannot compare this property. A change to the tags alone
	// plans no update.
	Tags pulumi.StringArrayInput
	// The URL that MailSlurp posts the event payload to. Your server must
	// accept the request. You can update this property in place.
	Url pulumi.StringInput
	// If you set this property, MailSlurp calls your server from its static IP
	// range. The default value is false.
	UseStaticIpRange pulumi.BoolPtrInput
}

func (WebhookArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*webhookArgs)(nil)).Elem()
}

type WebhookInput interface {
	pulumi.Input

	ToWebhookOutput() WebhookOutput
	ToWebhookOutputWithContext(ctx context.Context) WebhookOutput
}

func (*Webhook) ElementType() reflect.Type {
	return reflect.TypeOf((**Webhook)(nil)).Elem()
}

func (i *Webhook) ToWebhookOutput() WebhookOutput {
	return i.ToWebhookOutputWithContext(context.Background())
}

func (i *Webhook) ToWebhookOutputWithContext(ctx context.Context) WebhookOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebhookOutput)
}

// WebhookArrayInput is an input type that accepts WebhookArray and WebhookArrayOutput values.
// You can construct a concrete instance of `WebhookArrayInput` via:
//
//	WebhookArray{ WebhookArgs{...} }
type WebhookArrayInput interface {
	pulumi.Input

	ToWebhookArrayOutput() WebhookArrayOutput
	ToWebhookArrayOutputWithContext(context.Context) WebhookArrayOutput
}

type WebhookArray []WebhookInput

func (WebhookArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Webhook)(nil)).Elem()
}

func (i WebhookArray) ToWebhookArrayOutput() WebhookArrayOutput {
	return i.ToWebhookArrayOutputWithContext(context.Background())
}

func (i WebhookArray) ToWebhookArrayOutputWithContext(ctx context.Context) WebhookArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebhookArrayOutput)
}

// WebhookMapInput is an input type that accepts WebhookMap and WebhookMapOutput values.
// You can construct a concrete instance of `WebhookMapInput` via:
//
//	WebhookMap{ "key": WebhookArgs{...} }
type WebhookMapInput interface {
	pulumi.Input

	ToWebhookMapOutput() WebhookMapOutput
	ToWebhookMapOutputWithContext(context.Context) WebhookMapOutput
}

type WebhookMap map[string]WebhookInput

func (WebhookMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Webhook)(nil)).Elem()
}

func (i WebhookMap) ToWebhookMapOutput() WebhookMapOutput {
	return i.ToWebhookMapOutputWithContext(context.Background())
}

func (i WebhookMap) ToWebhookMapOutputWithContext(ctx context.Context) WebhookMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebhookMapOutput)
}

type WebhookOutput struct{ *pulumi.OutputState }

func (WebhookOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Webhook)(nil)).Elem()
}

func (o WebhookOutput) ToWebhookOutput() WebhookOutput {
	return o
}

func (o WebhookOutput) ToWebhookOutputWithContext(ctx context.Context) WebhookOutput {
	return o
}

// The time when MailSlurp created the webhook.
func (o WebhookOutput) CreatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Webhook) pulumi.StringPtrOutput { return v.CreatedAt }).(pulumi.StringPtrOutput)
}

// MailSlurp reports whether the webhook is enabled. The API does not
// document this property, and the value can be empty.
func (o WebhookOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Webhook) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// The event that triggers the webhook.
func (o WebhookOutput) EventName() WebhookEventNameOutput {
	return o.ApplyT(func(v *Webhook) WebhookEventNameOutput { return v.EventName }).(WebhookEventNameOutput)
}

// The health of the webhook, as MailSlurp computes it. The value is
// `HEALTHY` or `UNHEALTHY`. The value changes often, so Pulumi never
// compares it.
func (o WebhookOutput) HealthStatus() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Webhook) pulumi.StringPtrOutput { return v.HealthStatus }).(pulumi.StringPtrOutput)
}

// MailSlurp reports whether it accepts an insecure SSL certificate on your server.
func (o WebhookOutput) IgnoreInsecureSslCertificates() pulumi.BoolOutput {
	return o.ApplyT(func(v *Webhook) pulumi.BoolOutput { return v.IgnoreInsecureSslCertificates }).(pulumi.BoolOutput)
}

// The inbox that triggers the webhook. An empty value means that every
// inbox in the account triggers the webhook.
func (o WebhookOutput) InboxId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Webhook) pulumi.StringPtrOutput { return v.InboxId }).(pulumi.StringPtrOutput)
}

// The HTTP headers that MailSlurp sends with each webhook request. The API
// names this value `requestHeaders` when it reports it.
func (o WebhookOutput) IncludeHeaders() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Webhook) pulumi.StringMapOutput { return v.IncludeHeaders }).(pulumi.StringMapOutput)
}

// The HTTP method that your server must accept. MailSlurp sends `POST`.
func (o WebhookOutput) Method() pulumi.StringOutput {
	return o.ApplyT(func(v *Webhook) pulumi.StringOutput { return v.Method }).(pulumi.StringOutput)
}

// The display name of the webhook.
func (o WebhookOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Webhook) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

// The template for the JSON body of the webhook request.
func (o WebhookOutput) RequestBodyTemplate() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Webhook) pulumi.StringPtrOutput { return v.RequestBodyTemplate }).(pulumi.StringPtrOutput)
}

// The URL that MailSlurp posts the event payload to.
func (o WebhookOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v *Webhook) pulumi.StringOutput { return v.Url }).(pulumi.StringOutput)
}

// MailSlurp reports whether it calls your server from its static IP range.
func (o WebhookOutput) UseStaticIpRange() pulumi.BoolOutput {
	return o.ApplyT(func(v *Webhook) pulumi.BoolOutput { return v.UseStaticIpRange }).(pulumi.BoolOutput)
}

type WebhookArrayOutput struct{ *pulumi.OutputState }

func (WebhookArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Webhook)(nil)).Elem()
}

func (o WebhookArrayOutput) ToWebhookArrayOutput() WebhookArrayOutput {
	return o
}

func (o WebhookArrayOutput) ToWebhookArrayOutputWithContext(ctx context.Context) WebhookArrayOutput {
	return o
}

func (o WebhookArrayOutput) Index(i pulumi.IntInput) WebhookOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Webhook {
		return vs[0].([]*Webhook)[vs[1].(int)]
	}).(WebhookOutput)
}

type WebhookMapOutput struct{ *pulumi.OutputState }

func (WebhookMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Webhook)(nil)).Elem()
}

func (o WebhookMapOutput) ToWebhookMapOutput() WebhookMapOutput {
	return o
}

func (o WebhookMapOutput) ToWebhookMapOutputWithContext(ctx context.Context) WebhookMapOutput {
	return o
}

func (o WebhookMapOutput) MapIndex(k pulumi.StringInput) WebhookOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Webhook {
		return vs[0].(map[string]*Webhook)[vs[1].(string)]
	}).(WebhookOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WebhookInput)(nil)).Elem(), &Webhook{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebhookArrayInput)(nil)).Elem(), WebhookArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebhookMapInput)(nil)).Elem(), WebhookMap{})
	pulumi.RegisterOutputType(WebhookOutput{})
	pulumi.RegisterOutputType(WebhookArrayOutput{})
	pulumi.RegisterOutputType(WebhookMapOutput{})
}
