// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Mailslurp
{
    /// <summary>
    /// An email template that MailSlurp fills with values when you send an email.
    /// You write each variable inside the content with the moustache markers.
    /// 
    /// You can update the `name` and the `content` of a template in place. Pulumi
    /// never replaces a template. MailSlurp parses the `variables` list from the
    /// content, so you cannot set it. A template is free, and it never counts
    /// against the inbox creation quota.
    /// 
    /// ## Example Usage
    /// ### A template that MailSlurp fills with two variables
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Mailslurp = Jschady.Mailslurp;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var welcomeTemplate = new Mailslurp.EmailTemplate("welcome-template", new()
    ///     {
    ///         Content = @"Hello {{firstName}},
    /// Your inbox {{inboxAddress}} is ready.
    /// ",
    ///         Name = "welcome-template",
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["variables"] = welcomeTemplate.Variables,
    ///     };
    /// });
    /// 
    /// ```
    /// </summary>
    [MailslurpResourceType("mailslurp:index:EmailTemplate")]
    public partial class EmailTemplate : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The body of the template.
        /// </summary>
        [Output("content")]
        public Output<string> Content { get; private set; } = null!;

        /// <summary>
        /// The time when MailSlurp created the template.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The display name of the template.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The variables that MailSlurp reads from the content. MailSlurp parses this
        /// list on the server, so you cannot set it.
        /// </summary>
        [Output("variables")]
        public Output<ImmutableArray<Outputs.EmailTemplateVariable>> Variables { get; private set; } = null!;


        /// <summary>
        /// Create a EmailTemplate resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EmailTemplate(string name, EmailTemplateArgs args, CustomResourceOptions? options = null)
            : base("mailslurp:index:EmailTemplate", name, args ?? new EmailTemplateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private EmailTemplate(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("mailslurp:index:EmailTemplate", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/jschady/pulumi-mailslurp",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EmailTemplate resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EmailTemplate Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new EmailTemplate(name, id, options);
        }
    }

    public sealed class EmailTemplateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The body of the template. Write a variable as `{{firstName}}`, and
        /// MailSlurp reports each variable that it reads in the `variables` property.
        /// You can update this property in place.
        /// </summary>
        [Input("content", required: true)]
        public Input<string> Content { get; set; } = null!;

        /// <summary>
        /// The display name of the template. You can update this property in place.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public EmailTemplateArgs()
        {
        }
        public static new EmailTemplateArgs Empty => new EmailTemplateArgs();
    }
}
