// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Jschady.Mailslurp
{
    [EnumType]
    public readonly struct DomainType : IEquatable<DomainType>
    {
        private readonly string _value;

        private DomainType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// The domain serves inboxes that store email with HTTP endpoints.
        /// </summary>
        public static DomainType HttpInbox { get; } = new DomainType("HTTP_INBOX");
        /// <summary>
        /// The domain serves inboxes that receive email on a real SMTP mail server.
        /// </summary>
        public static DomainType SmtpDomain { get; } = new DomainType("SMTP_DOMAIN");

        public static bool operator ==(DomainType left, DomainType right) => left.Equals(right);
        public static bool operator !=(DomainType left, DomainType right) => !left.Equals(right);

        public static explicit operator string(DomainType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is DomainType other && Equals(other);
        public bool Equals(DomainType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct ForwarderField : IEquatable<ForwarderField>
    {
        private readonly string _value;

        private ForwarderField(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// MailSlurp compares the addresses that the email went to.
        /// </summary>
        public static ForwarderField Recipients { get; } = new ForwarderField("RECIPIENTS");
        /// <summary>
        /// MailSlurp compares the address that sent the email.
        /// </summary>
        public static ForwarderField Sender { get; } = new ForwarderField("SENDER");
        /// <summary>
        /// MailSlurp compares the subject of the email.
        /// </summary>
        public static ForwarderField Subject { get; } = new ForwarderField("SUBJECT");
        /// <summary>
        /// MailSlurp compares the attachments of the email.
        /// </summary>
        public static ForwarderField Attachments { get; } = new ForwarderField("ATTACHMENTS");
        /// <summary>
        /// MailSlurp compares the file name of each attachment.
        /// </summary>
        public static ForwarderField AttachmentFilename { get; } = new ForwarderField("ATTACHMENT_FILENAME");
        /// <summary>
        /// MailSlurp compares the text inside each attachment.
        /// </summary>
        public static ForwarderField AttachmentText { get; } = new ForwarderField("ATTACHMENT_TEXT");

        public static bool operator ==(ForwarderField left, ForwarderField right) => left.Equals(right);
        public static bool operator !=(ForwarderField left, ForwarderField right) => !left.Equals(right);

        public static explicit operator string(ForwarderField value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is ForwarderField other && Equals(other);
        public bool Equals(ForwarderField other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct ForwarderMatchOperator : IEquatable<ForwarderMatchOperator>
    {
        private readonly string _value;

        private ForwarderMatchOperator(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// MailSlurp forwards the email when every rule of the group matches.
        /// </summary>
        public static ForwarderMatchOperator And { get; } = new ForwarderMatchOperator("AND");
        /// <summary>
        /// MailSlurp forwards the email when one rule of the group matches.
        /// </summary>
        public static ForwarderMatchOperator Or { get; } = new ForwarderMatchOperator("OR");

        public static bool operator ==(ForwarderMatchOperator left, ForwarderMatchOperator right) => left.Equals(right);
        public static bool operator !=(ForwarderMatchOperator left, ForwarderMatchOperator right) => !left.Equals(right);

        public static explicit operator string(ForwarderMatchOperator value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is ForwarderMatchOperator other && Equals(other);
        public bool Equals(ForwarderMatchOperator other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct ForwarderShould : IEquatable<ForwarderShould>
    {
        private readonly string _value;

        private ForwarderShould(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// MailSlurp reads the match value as a pattern. A star matches every character.
        /// </summary>
        public static ForwarderShould Wildcard { get; } = new ForwarderShould("WILDCARD");
        /// <summary>
        /// MailSlurp compares the part with the whole match value. The API does not state how this mode differs from `EQUAL`.
        /// </summary>
        public static ForwarderShould Match { get; } = new ForwarderShould("MATCH");
        /// <summary>
        /// MailSlurp forwards the email when the part holds the match value inside it.
        /// </summary>
        public static ForwarderShould Contain { get; } = new ForwarderShould("CONTAIN");
        /// <summary>
        /// MailSlurp forwards the email when the part and the match value are the same.
        /// </summary>
        public static ForwarderShould Equal { get; } = new ForwarderShould("EQUAL");

        public static bool operator ==(ForwarderShould left, ForwarderShould right) => left.Equals(right);
        public static bool operator !=(ForwarderShould left, ForwarderShould right) => !left.Equals(right);

        public static explicit operator string(ForwarderShould value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is ForwarderShould other && Equals(other);
        public bool Equals(ForwarderShould other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct InboxType : IEquatable<InboxType>
    {
        private readonly string _value;

        private InboxType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// The inbox stores email with HTTP endpoints. Use this type for tests and webhooks.
        /// </summary>
        public static InboxType HttpInbox { get; } = new InboxType("HTTP_INBOX");
        /// <summary>
        /// The inbox receives email on a real SMTP mail server. Use this type for external senders.
        /// </summary>
        public static InboxType SmtpInbox { get; } = new InboxType("SMTP_INBOX");

        public static bool operator ==(InboxType left, InboxType right) => left.Equals(right);
        public static bool operator !=(InboxType left, InboxType right) => !left.Equals(right);

        public static explicit operator string(InboxType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is InboxType other && Equals(other);
        public bool Equals(InboxType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct RulesetAction : IEquatable<RulesetAction>
    {
        private readonly string _value;

        private RulesetAction(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// MailSlurp stops the email when the target matches.
        /// </summary>
        public static RulesetAction Block { get; } = new RulesetAction("BLOCK");
        /// <summary>
        /// MailSlurp permits the email when the target matches, and this action wins over a block.
        /// </summary>
        public static RulesetAction Allow { get; } = new RulesetAction("ALLOW");
        /// <summary>
        /// MailSlurp removes the matched address from the email, and the rest of the email continues.
        /// </summary>
        public static RulesetAction FilterRemove { get; } = new RulesetAction("FILTER_REMOVE");
        /// <summary>
        /// MailSlurp answers the sender with a soft bounce, which states a temporary failure.
        /// </summary>
        public static RulesetAction BounceSoft { get; } = new RulesetAction("BOUNCE_SOFT");
        /// <summary>
        /// MailSlurp answers the sender with a hard bounce, which states a permanent failure.
        /// </summary>
        public static RulesetAction BounceHard { get; } = new RulesetAction("BOUNCE_HARD");

        public static bool operator ==(RulesetAction left, RulesetAction right) => left.Equals(right);
        public static bool operator !=(RulesetAction left, RulesetAction right) => !left.Equals(right);

        public static explicit operator string(RulesetAction value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is RulesetAction other && Equals(other);
        public bool Equals(RulesetAction other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct RulesetScope : IEquatable<RulesetScope>
    {
        private readonly string _value;

        private RulesetScope(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// MailSlurp applies the ruleset to every email that the inbox receives.
        /// </summary>
        public static RulesetScope ReceivingEmails { get; } = new RulesetScope("RECEIVING_EMAILS");
        /// <summary>
        /// MailSlurp applies the ruleset to every email that the inbox sends.
        /// </summary>
        public static RulesetScope SendingEmails { get; } = new RulesetScope("SENDING_EMAILS");
        /// <summary>
        /// MailSlurp applies the ruleset to every SMS message that a phone number receives.
        /// </summary>
        public static RulesetScope ReceivingSms { get; } = new RulesetScope("RECEIVING_SMS");
        /// <summary>
        /// MailSlurp applies the ruleset to every SMS message that a phone number sends.
        /// </summary>
        public static RulesetScope SendingSms { get; } = new RulesetScope("SENDING_SMS");

        public static bool operator ==(RulesetScope left, RulesetScope right) => left.Equals(right);
        public static bool operator !=(RulesetScope left, RulesetScope right) => !left.Equals(right);

        public static explicit operator string(RulesetScope value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is RulesetScope other && Equals(other);
        public bool Equals(RulesetScope other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct WebhookEventName : IEquatable<WebhookEventName>
    {
        private readonly string _value;

        private WebhookEventName(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// MailSlurp sends the event when an inbox receives an email payload.
        /// </summary>
        public static WebhookEventName EmailReceived { get; } = new WebhookEventName("EMAIL_RECEIVED");
        /// <summary>
        /// MailSlurp sends the event when an AI transformer produces a new extraction result.
        /// </summary>
        public static WebhookEventName NewAiTransformResult { get; } = new WebhookEventName("NEW_AI_TRANSFORM_RESULT");
        /// <summary>
        /// MailSlurp sends the event when an inbox receives a new email.
        /// </summary>
        public static WebhookEventName NewEmail { get; } = new WebhookEventName("NEW_EMAIL");
        /// <summary>
        /// MailSlurp sends the event when it creates a contact from inbound email activity.
        /// </summary>
        public static WebhookEventName NewContact { get; } = new WebhookEventName("NEW_CONTACT");
        /// <summary>
        /// MailSlurp sends the event when it detects an attachment on a received email.
        /// </summary>
        public static WebhookEventName NewAttachment { get; } = new WebhookEventName("NEW_ATTACHMENT");
        /// <summary>
        /// MailSlurp sends the event when it tracks an email open.
        /// </summary>
        public static WebhookEventName EmailOpened { get; } = new WebhookEventName("EMAIL_OPENED");
        /// <summary>
        /// MailSlurp sends the event when a recipient reads an email.
        /// </summary>
        public static WebhookEventName EmailRead { get; } = new WebhookEventName("EMAIL_READ");
        /// <summary>
        /// MailSlurp sends the event when the delivery status of a sent email changes.
        /// </summary>
        public static WebhookEventName DeliveryStatus { get; } = new WebhookEventName("DELIVERY_STATUS");
        /// <summary>
        /// MailSlurp sends the event when an email bounces at the account level.
        /// </summary>
        public static WebhookEventName Bounce { get; } = new WebhookEventName("BOUNCE");
        /// <summary>
        /// MailSlurp sends the event when an email address bounces.
        /// </summary>
        public static WebhookEventName BounceRecipient { get; } = new WebhookEventName("BOUNCE_RECIPIENT");
        /// <summary>
        /// MailSlurp sends the event when a phone number receives an SMS message.
        /// </summary>
        public static WebhookEventName NewSms { get; } = new WebhookEventName("NEW_SMS");
        /// <summary>
        /// MailSlurp sends the event for a guest user.
        /// </summary>
        public static WebhookEventName NewGuestUser { get; } = new WebhookEventName("NEW_GUEST_USER");

        public static bool operator ==(WebhookEventName left, WebhookEventName right) => left.Equals(right);
        public static bool operator !=(WebhookEventName left, WebhookEventName right) => !left.Equals(right);

        public static explicit operator string(WebhookEventName value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is WebhookEventName other && Equals(other);
        public bool Equals(WebhookEventName other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
