// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Mailslurp
{
    public static class GetDomain
    {
        /// <summary>
        /// The function reads one MailSlurp custom domain by its identifier. The
        /// result carries the DNS records that the domain needs, so a stack can
        /// create them with a DNS provider. The function reads the domain and
        /// changes nothing.
        /// </summary>
        public static Task<GetDomainResult> InvokeAsync(GetDomainArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDomainResult>("mailslurp:index:getDomain", args ?? new GetDomainArgs(), options.WithDefaults());

        /// <summary>
        /// The function reads one MailSlurp custom domain by its identifier. The
        /// result carries the DNS records that the domain needs, so a stack can
        /// create them with a DNS provider. The function reads the domain and
        /// changes nothing.
        /// </summary>
        public static Output<GetDomainResult> Invoke(GetDomainInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDomainResult>("mailslurp:index:getDomain", args ?? new GetDomainInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// The function reads one MailSlurp custom domain by its identifier. The
        /// result carries the DNS records that the domain needs, so a stack can
        /// create them with a DNS provider. The function reads the domain and
        /// changes nothing.
        /// </summary>
        public static Output<GetDomainResult> Invoke(GetDomainInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDomainResult>("mailslurp:index:getDomain", args ?? new GetDomainInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDomainArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// If you set this property, MailSlurp checks the domain for DNS record
        /// problems. The default is `false`.
        /// </summary>
        [Input("checkForErrors")]
        public bool? CheckForErrors { get; set; }

        /// <summary>
        /// The identifier of the domain to read. MailSlurp assigns this value when
        /// it creates the domain.
        /// </summary>
        [Input("domainId", required: true)]
        public string DomainId { get; set; } = null!;

        public GetDomainArgs()
        {
        }
        public static new GetDomainArgs Empty => new GetDomainArgs();
    }

    public sealed class GetDomainInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// If you set this property, MailSlurp checks the domain for DNS record
        /// problems. The default is `false`.
        /// </summary>
        [Input("checkForErrors")]
        public Input<bool>? CheckForErrors { get; set; }

        /// <summary>
        /// The identifier of the domain to read. MailSlurp assigns this value when
        /// it creates the domain.
        /// </summary>
        [Input("domainId", required: true)]
        public Input<string> DomainId { get; set; } = null!;

        public GetDomainInvokeArgs()
        {
        }
        public static new GetDomainInvokeArgs Empty => new GetDomainInvokeArgs();
    }


    [OutputType]
    public sealed class GetDomainResult
    {
        /// <summary>
        /// The identifier of the inbox that receives the email of every unmatched
        /// address.
        /// </summary>
        public readonly string? CatchAllInboxId;
        /// <summary>
        /// The time when MailSlurp created the domain.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The DKIM values of the domain. Add one CNAME record for each value.
        /// </summary>
        public readonly ImmutableArray<string> DkimTokens;
        /// <summary>
        /// The custom domain name.
        /// </summary>
        public readonly string Domain;
        /// <summary>
        /// The identifier of the domain.
        /// </summary>
        public readonly string DomainId;
        /// <summary>
        /// The DNS records that the domain needs. Loop over this list to create the
        /// records with a DNS provider.
        /// </summary>
        public readonly ImmutableArray<Outputs.DomainNameRecordResult> DomainNameRecords;
        /// <summary>
        /// The domain type.
        /// </summary>
        public readonly Jschady.Mailslurp.DomainType DomainType;
        /// <summary>
        /// The message that names the duplicate DNS records.
        /// </summary>
        public readonly string? DuplicateRecordsMessage;
        /// <summary>
        /// MailSlurp reports whether the domain has a duplicate DNS record.
        /// </summary>
        public readonly bool HasDuplicateRecords;
        /// <summary>
        /// MailSlurp reports whether the domain misses a required DNS record.
        /// </summary>
        public readonly bool HasMissingRecords;
        /// <summary>
        /// MailSlurp reports whether the domain passed the DNS checks.
        /// </summary>
        public readonly bool IsVerified;
        /// <summary>
        /// The message that names the missing DNS records.
        /// </summary>
        public readonly string? MissingRecordsMessage;
        /// <summary>
        /// The time when MailSlurp last changed the domain.
        /// </summary>
        public readonly string UpdatedAt;
        /// <summary>
        /// The value that proves you own the domain. Add it to the DNS records of
        /// the domain.
        /// </summary>
        public readonly string VerificationToken;

        [OutputConstructor]
        private GetDomainResult(
            string? catchAllInboxId,

            string createdAt,

            ImmutableArray<string> dkimTokens,

            string domain,

            string domainId,

            ImmutableArray<Outputs.DomainNameRecordResult> domainNameRecords,

            Jschady.Mailslurp.DomainType domainType,

            string? duplicateRecordsMessage,

            bool hasDuplicateRecords,

            bool hasMissingRecords,

            bool isVerified,

            string? missingRecordsMessage,

            string updatedAt,

            string verificationToken)
        {
            CatchAllInboxId = catchAllInboxId;
            CreatedAt = createdAt;
            DkimTokens = dkimTokens;
            Domain = domain;
            DomainId = domainId;
            DomainNameRecords = domainNameRecords;
            DomainType = domainType;
            DuplicateRecordsMessage = duplicateRecordsMessage;
            HasDuplicateRecords = hasDuplicateRecords;
            HasMissingRecords = hasMissingRecords;
            IsVerified = isVerified;
            MissingRecordsMessage = missingRecordsMessage;
            UpdatedAt = updatedAt;
            VerificationToken = verificationToken;
        }
    }
}
