// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Mailslurp
{
    public static class GetInbox
    {
        /// <summary>
        /// The function reads one MailSlurp inbox by its identifier. Use it when a
        /// stack must reference an inbox that Pulumi does not manage. The function
        /// reads the inbox and changes nothing.
        /// </summary>
        public static Task<GetInboxResult> InvokeAsync(GetInboxArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetInboxResult>("mailslurp:index:getInbox", args ?? new GetInboxArgs(), options.WithDefaults());

        /// <summary>
        /// The function reads one MailSlurp inbox by its identifier. Use it when a
        /// stack must reference an inbox that Pulumi does not manage. The function
        /// reads the inbox and changes nothing.
        /// </summary>
        public static Output<GetInboxResult> Invoke(GetInboxInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetInboxResult>("mailslurp:index:getInbox", args ?? new GetInboxInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// The function reads one MailSlurp inbox by its identifier. Use it when a
        /// stack must reference an inbox that Pulumi does not manage. The function
        /// reads the inbox and changes nothing.
        /// </summary>
        public static Output<GetInboxResult> Invoke(GetInboxInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetInboxResult>("mailslurp:index:getInbox", args ?? new GetInboxInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetInboxArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The identifier of the inbox to read. MailSlurp assigns this value when
        /// it creates the inbox.
        /// </summary>
        [Input("inboxId", required: true)]
        public string InboxId { get; set; } = null!;

        public GetInboxArgs()
        {
        }
        public static new GetInboxArgs Empty => new GetInboxArgs();
    }

    public sealed class GetInboxInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The identifier of the inbox to read. MailSlurp assigns this value when
        /// it creates the inbox.
        /// </summary>
        [Input("inboxId", required: true)]
        public Input<string> InboxId { get; set; } = null!;

        public GetInboxInvokeArgs()
        {
        }
        public static new GetInboxInvokeArgs Empty => new GetInboxInvokeArgs();
    }


    [OutputType]
    public sealed class GetInboxResult
    {
        /// <summary>
        /// The region of the account that holds the inbox.
        /// </summary>
        public readonly string? AccountRegion;
        /// <summary>
        /// The time when MailSlurp created the inbox.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The free-text description of the inbox.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// The domain part of the inbox email address.
        /// </summary>
        public readonly string? Domain;
        /// <summary>
        /// The identifier of the custom domain that provides the inbox address.
        /// </summary>
        public readonly string? DomainId;
        /// <summary>
        /// The full email address of the inbox.
        /// </summary>
        public readonly string EmailAddress;
        /// <summary>
        /// The time when MailSlurp expires the inbox, in RFC 3339 format.
        /// </summary>
        public readonly string? ExpiresAt;
        /// <summary>
        /// MailSlurp reports whether the inbox is a favourite in the dashboard.
        /// </summary>
        public readonly bool Favourite;
        /// <summary>
        /// The special function of the inbox, for example an alias or a catch-all.
        /// </summary>
        public readonly string? FunctionsAs;
        /// <summary>
        /// The identifier of the inbox.
        /// </summary>
        public readonly string InboxId;
        /// <summary>
        /// The inbox type.
        /// </summary>
        public readonly Jschady.Mailslurp.InboxType? InboxType;
        /// <summary>
        /// The local part of the inbox email address.
        /// </summary>
        public readonly string? LocalPart;
        /// <summary>
        /// The display name of the inbox.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// MailSlurp reports whether the inbox is read-only.
        /// </summary>
        public readonly bool ReadOnly;
        /// <summary>
        /// The tags on the inbox.
        /// </summary>
        public readonly ImmutableArray<string> Tags;
        /// <summary>
        /// MailSlurp reports whether the inbox is virtual. A virtual inbox never sends email to real recipients.
        /// </summary>
        public readonly bool VirtualInbox;

        [OutputConstructor]
        private GetInboxResult(
            string? accountRegion,

            string createdAt,

            string? description,

            string? domain,

            string? domainId,

            string emailAddress,

            string? expiresAt,

            bool favourite,

            string? functionsAs,

            string inboxId,

            Jschady.Mailslurp.InboxType? inboxType,

            string? localPart,

            string? name,

            bool readOnly,

            ImmutableArray<string> tags,

            bool virtualInbox)
        {
            AccountRegion = accountRegion;
            CreatedAt = createdAt;
            Description = description;
            Domain = domain;
            DomainId = domainId;
            EmailAddress = emailAddress;
            ExpiresAt = expiresAt;
            Favourite = favourite;
            FunctionsAs = functionsAs;
            InboxId = inboxId;
            InboxType = inboxType;
            LocalPart = localPart;
            Name = name;
            ReadOnly = readOnly;
            Tags = tags;
            VirtualInbox = virtualInbox;
        }
    }
}
