// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Mailslurp
{
    /// <summary>
    /// An inbox forwarder that sends a copy of a matching email to other
    /// addresses. MailSlurp reads each email that the inbox receives, and
    /// forwards the email when the rule matches.
    /// 
    /// You can update the `field`, the `should`, the `match`, the `matchOptions`
    /// and the `forwardToRecipients` properties in place. Pulumi replaces the
    /// forwarder when you change the `inboxId` property, because the API takes
    /// the inbox on the create call alone.
    /// 
    /// The API requires the `field` and the `match` properties, or the
    /// `matchOptions` property. A write that names none of them fails. Each
    /// update sends the whole create body, so a value that you set outside
    /// Pulumi can go away.
    /// 
    /// MailSlurp writes the `name` of the forwarder. The create call takes no
    /// name, so you cannot set it. This resource does not carry the
    /// `attachmentTextExtractionMethod` property of the API.
    /// 
    /// ## Example Usage
    /// ### A forwarder that sends every invoice email to the billing address
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Mailslurp = Jschady.Mailslurp;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var billingInbox = new Mailslurp.Inbox("billing-inbox", new()
    ///     {
    ///         Name = "billing-inbox",
    ///     });
    /// 
    ///     var invoiceForwarder = new Mailslurp.InboxForwarder("invoice-forwarder", new()
    ///     {
    ///         Field = Mailslurp.ForwarderField.Subject,
    ///         ForwardToRecipients = new[]
    ///         {
    ///             "billing@example.com",
    ///         },
    ///         InboxId = billingInbox.Id,
    ///         Match = "invoice",
    ///         Should = Mailslurp.ForwarderShould.Contain,
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["forwarderId"] = invoiceForwarder.Id,
    ///     };
    /// });
    /// 
    /// ```
    /// </summary>
    [MailslurpResourceType("mailslurp:index:InboxForwarder")]
    public partial class InboxForwarder : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The time when MailSlurp created the forwarder.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The part of the email that MailSlurp compares.
        /// </summary>
        [Output("field")]
        public Output<Jschady.Mailslurp.ForwarderField?> Field { get; private set; } = null!;

        /// <summary>
        /// The addresses that MailSlurp sends the matching email to.
        /// </summary>
        [Output("forwardToRecipients")]
        public Output<ImmutableArray<string>> ForwardToRecipients { get; private set; } = null!;

        /// <summary>
        /// The inbox that the forwarder reads.
        /// </summary>
        [Output("inboxId")]
        public Output<string> InboxId { get; private set; } = null!;

        /// <summary>
        /// The value or the pattern that MailSlurp compares.
        /// </summary>
        [Output("match")]
        public Output<string?> Match { get; private set; } = null!;

        /// <summary>
        /// The tree of match rules that MailSlurp applies to each email.
        /// </summary>
        [Output("matchOptions")]
        public Output<Outputs.InboxForwarderMatchGroup?> MatchOptions { get; private set; } = null!;

        /// <summary>
        /// The display name of the forwarder. MailSlurp writes it, and the create
        /// call takes no name, so you cannot set it.
        /// </summary>
        [Output("name")]
        public Output<string?> Name { get; private set; } = null!;

        /// <summary>
        /// The way that MailSlurp compares the `match` value.
        /// </summary>
        [Output("should")]
        public Output<Jschady.Mailslurp.ForwarderShould?> Should { get; private set; } = null!;


        /// <summary>
        /// Create a InboxForwarder resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public InboxForwarder(string name, InboxForwarderArgs args, CustomResourceOptions? options = null)
            : base("mailslurp:index:InboxForwarder", name, args ?? new InboxForwarderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private InboxForwarder(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("mailslurp:index:InboxForwarder", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/jschady/pulumi-mailslurp",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing InboxForwarder resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static InboxForwarder Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new InboxForwarder(name, id, options);
        }
    }

    public sealed class InboxForwarderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The part of the email that MailSlurp compares against the `match` value.
        /// You can update this property in place.
        /// </summary>
        [Input("field")]
        public Input<Jschady.Mailslurp.ForwarderField>? Field { get; set; }

        [Input("forwardToRecipients", required: true)]
        private InputList<string>? _forwardToRecipients;

        /// <summary>
        /// The addresses that MailSlurp sends the matching email to. The API
        /// requires this property on every write. You can update this property in
        /// place.
        /// </summary>
        public InputList<string> ForwardToRecipients
        {
            get => _forwardToRecipients ?? (_forwardToRecipients = new InputList<string>());
            set => _forwardToRecipients = value;
        }

        /// <summary>
        /// The inbox that the forwarder reads. MailSlurp compares each email that
        /// this inbox receives. **Warning:** If you change this property, Pulumi
        /// replaces the forwarder. The new forwarder carries a new identifier.
        /// </summary>
        [Input("inboxId", required: true)]
        public Input<string> InboxId { get; set; } = null!;

        /// <summary>
        /// The value or the pattern that MailSlurp compares. Use `*@example.com` to
        /// match every address of a domain. You can update this property in place.
        /// </summary>
        [Input("match")]
        public Input<string>? Match { get; set; }

        /// <summary>
        /// A tree of match rules that MailSlurp applies to each email. The
        /// `operator` property joins the rules of one group. You can put a group
        /// inside the `groups` property. You can update this property in place.
        /// </summary>
        [Input("matchOptions")]
        public Input<Inputs.InboxForwarderMatchGroupArgs>? MatchOptions { get; set; }

        /// <summary>
        /// The way that MailSlurp compares the `match` value. Use `WILDCARD` for a
        /// pattern that holds a star. Use `EQUAL` for one exact value. You can
        /// update this property in place.
        /// </summary>
        [Input("should")]
        public Input<Jschady.Mailslurp.ForwarderShould>? Should { get; set; }

        public InboxForwarderArgs()
        {
        }
        public static new InboxForwarderArgs Empty => new InboxForwarderArgs();
    }
}
