// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Mailslurp
{
    /// <summary>
    /// An email inbox on MailSlurp. The inbox has an email address that can
    /// send and receive email.
    /// 
    /// You can update the `name`, `description`, `tags`, `expiresAt`, and
    /// `favourite` properties in place. If you change any other property,
    /// Pulumi replaces the inbox. Each replacement creates a new inbox, which
    /// counts against the 30-day inbox creation quota of your MailSlurp
    /// account. MailSlurp bills each creation on paid plans. If you remove a
    /// property that forces a replacement, Pulumi keeps the inbox.
    /// 
    /// ## Example Usage
    /// ### An inbox that receives email at an address MailSlurp assigns
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Mailslurp = Jschady.Mailslurp;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var teamInbox = new Mailslurp.Inbox("team-inbox", new()
    ///     {
    ///         Description = "The shared inbox of the team",
    ///         InboxType = Mailslurp.InboxType.HttpInbox,
    ///         Name = "team-inbox",
    ///         Tags = new[]
    ///         {
    ///             "pulumi",
    ///             "team",
    ///         },
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["emailAddress"] = teamInbox.EmailAddress,
    ///     };
    /// });
    /// 
    /// ```
    /// ### A virtual inbox that holds every test email inside MailSlurp
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Mailslurp = Jschady.Mailslurp;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var testInbox = new Mailslurp.Inbox("test-inbox", new()
    ///     {
    ///         Description = "The inbox that the acceptance tests read",
    ///         ExpiresIn = 3600000,
    ///         Name = "test-inbox",
    ///         Tags = new[]
    ///         {
    ///             "test",
    ///         },
    ///         VirtualInbox = true,
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["emailAddress"] = testInbox.EmailAddress,
    ///     };
    /// });
    /// 
    /// ```
    /// </summary>
    [MailslurpResourceType("mailslurp:index:Inbox")]
    public partial class Inbox : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The region of the account that holds the inbox.
        /// </summary>
        [Output("accountRegion")]
        public Output<string?> AccountRegion { get; private set; } = null!;

        /// <summary>
        /// The time when MailSlurp created the inbox.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The free-text description of the inbox.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The domain part of the inbox email address.
        /// </summary>
        [Output("domain")]
        public Output<string?> Domain { get; private set; } = null!;

        /// <summary>
        /// The identifier of the custom domain that provides the inbox address.
        /// </summary>
        [Output("domainId")]
        public Output<string?> DomainId { get; private set; } = null!;

        /// <summary>
        /// The custom domain that provides the inbox address.
        /// </summary>
        [Output("domainName")]
        public Output<string?> DomainName { get; private set; } = null!;

        /// <summary>
        /// The full email address of the inbox.
        /// </summary>
        [Output("emailAddress")]
        public Output<string> EmailAddress { get; private set; } = null!;

        /// <summary>
        /// The time when MailSlurp expires the inbox, in RFC 3339 format.
        /// </summary>
        [Output("expiresAt")]
        public Output<string?> ExpiresAt { get; private set; } = null!;

        /// <summary>
        /// The lifetime of the inbox in milliseconds. The API does not echo this property.
        /// </summary>
        [Output("expiresIn")]
        public Output<int?> ExpiresIn { get; private set; } = null!;

        /// <summary>
        /// MailSlurp reports whether the inbox is a favourite in the dashboard.
        /// </summary>
        [Output("favourite")]
        public Output<bool?> Favourite { get; private set; } = null!;

        /// <summary>
        /// The special function of the inbox, for example an alias or a catch-all.
        /// </summary>
        [Output("functionsAs")]
        public Output<string?> FunctionsAs { get; private set; } = null!;

        /// <summary>
        /// The inbox type.
        /// </summary>
        [Output("inboxType")]
        public Output<Jschady.Mailslurp.InboxType?> InboxType { get; private set; } = null!;

        /// <summary>
        /// The local part of the inbox email address.
        /// </summary>
        [Output("localPart")]
        public Output<string?> LocalPart { get; private set; } = null!;

        /// <summary>
        /// The display name of the inbox.
        /// </summary>
        [Output("name")]
        public Output<string?> Name { get; private set; } = null!;

        /// <summary>
        /// The prefix for the local part of the assigned email address. The API does not echo this property.
        /// </summary>
        [Output("prefix")]
        public Output<string?> Prefix { get; private set; } = null!;

        /// <summary>
        /// MailSlurp reports whether the inbox is read-only.
        /// </summary>
        [Output("readOnly")]
        public Output<bool> ReadOnly { get; private set; } = null!;

        /// <summary>
        /// The tags on the inbox.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        /// <summary>
        /// The shared MailSlurp domain pool value of the inbox. The API does not echo this property.
        /// </summary>
        [Output("useDomainPool")]
        public Output<bool?> UseDomainPool { get; private set; } = null!;

        /// <summary>
        /// The short address value of the inbox. The API does not echo this property.
        /// </summary>
        [Output("useShortAddress")]
        public Output<bool?> UseShortAddress { get; private set; } = null!;

        /// <summary>
        /// MailSlurp reports whether the inbox is virtual. A virtual inbox never sends email to real recipients.
        /// </summary>
        [Output("virtualInbox")]
        public Output<bool?> VirtualInbox { get; private set; } = null!;


        /// <summary>
        /// Create a Inbox resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Inbox(string name, InboxArgs? args = null, CustomResourceOptions? options = null)
            : base("mailslurp:index:Inbox", name, args ?? new InboxArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Inbox(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("mailslurp:index:Inbox", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/jschady/pulumi-mailslurp",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Inbox resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Inbox Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Inbox(name, id, options);
        }
    }

    public sealed class InboxArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A free-text description of the inbox. You can update this property in
        /// place. The API cannot clear this property after you set it.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The identifier of a verified custom domain that provides the inbox
        /// address. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        /// </summary>
        [Input("domainId")]
        public Input<string>? DomainId { get; set; }

        /// <summary>
        /// The custom domain that provides the inbox address. The domain must be
        /// verified in your MailSlurp account. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        /// </summary>
        [Input("domainName")]
        public Input<string>? DomainName { get; set; }

        /// <summary>
        /// The full email address of the inbox. When you do not set this
        /// property, MailSlurp assigns an address. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        /// </summary>
        [Input("emailAddress")]
        public Input<string>? EmailAddress { get; set; }

        /// <summary>
        /// The time when MailSlurp expires the inbox, in RFC 3339 format. You can
        /// update this property in place. The API cannot clear this property after
        /// you set it.
        /// </summary>
        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        /// <summary>
        /// The lifetime of the inbox in milliseconds. The API does not echo this
        /// property, so Pulumi keeps it in the state and does not diff it against
        /// the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        /// </summary>
        [Input("expiresIn")]
        public Input<int>? ExpiresIn { get; set; }

        /// <summary>
        /// If you set this property, MailSlurp marks the inbox as a favourite in
        /// the dashboard. You can update this property in place.
        /// </summary>
        [Input("favourite")]
        public Input<bool>? Favourite { get; set; }

        /// <summary>
        /// The inbox type: `HTTP_INBOX` or `SMTP_INBOX`. A refresh keeps the
        /// prior value when the API does not report a type. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        /// </summary>
        [Input("inboxType")]
        public Input<Jschady.Mailslurp.InboxType>? InboxType { get; set; }

        /// <summary>
        /// The display name of the inbox. You can update this property in place.
        /// The API cannot clear this property after you set it.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// A prefix for the local part of the assigned email address. The API
        /// does not echo this property, so Pulumi keeps it in the state and does
        /// not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        /// </summary>
        [Input("prefix")]
        public Input<string>? Prefix { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// The tags on the inbox. Use tags to group and find inboxes. You can
        /// update this property in place. Set an empty list to clear the tags.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// If you set this property, MailSlurp assigns the address from the shared
        /// domain pool. The API does not echo this property, so Pulumi keeps it in
        /// the state and does not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        /// </summary>
        [Input("useDomainPool")]
        public Input<bool>? UseDomainPool { get; set; }

        /// <summary>
        /// If you set this property, MailSlurp assigns a short email address to the
        /// inbox. The API does not echo this property, so Pulumi keeps it in the
        /// state and does not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        /// </summary>
        [Input("useShortAddress")]
        public Input<bool>? UseShortAddress { get; set; }

        /// <summary>
        /// If you set this property, MailSlurp creates a virtual inbox. A virtual
        /// inbox receives email but never sends it to real recipients. Use it for
        /// safe tests. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        /// </summary>
        [Input("virtualInbox")]
        public Input<bool>? VirtualInbox { get; set; }

        public InboxArgs()
        {
        }
        public static new InboxArgs Empty => new InboxArgs();
    }
}
