// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Mailslurp
{
    /// <summary>
    /// An inbox ruleset that blocks or allows email for one inbox. MailSlurp
    /// applies the ruleset when the inbox sends or receives email.
    /// 
    /// You cannot update a ruleset. The API offers no update call, so Pulumi
    /// replaces the ruleset when you change any property. Pulumi creates the new
    /// ruleset, and then it deletes the old one. A ruleset is free, and it never
    /// counts against the inbox creation quota.
    /// 
    /// ## Example Usage
    /// ### A ruleset that blocks the email of one domain
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Mailslurp = Jschady.Mailslurp;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var supportInbox = new Mailslurp.Inbox("support-inbox", new()
    ///     {
    ///         Name = "support-inbox",
    ///     });
    /// 
    ///     var blockOneDomain = new Mailslurp.InboxRuleset("block-one-domain", new()
    ///     {
    ///         Action = Mailslurp.RulesetAction.Block,
    ///         InboxId = supportInbox.Id,
    ///         Scope = Mailslurp.RulesetScope.ReceivingEmails,
    ///         Target = "*@blocked.example.com",
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["rulesetId"] = blockOneDomain.Id,
    ///     };
    /// });
    /// 
    /// ```
    /// </summary>
    [MailslurpResourceType("mailslurp:index:InboxRuleset")]
    public partial class InboxRuleset : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The action that MailSlurp takes when the target matches.
        /// </summary>
        [Output("action")]
        public Output<Jschady.Mailslurp.RulesetAction> Action { get; private set; } = null!;

        /// <summary>
        /// The time when MailSlurp created the ruleset.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The handler that MailSlurp runs for the ruleset. The API reports one value, `EXCEPTION`.
        /// </summary>
        [Output("handler")]
        public Output<string> Handler { get; private set; } = null!;

        /// <summary>
        /// The inbox that the ruleset applies to.
        /// </summary>
        [Output("inboxId")]
        public Output<string> InboxId { get; private set; } = null!;

        /// <summary>
        /// The phone number that the ruleset applies to. This resource always names
        /// an inbox, so MailSlurp reports no phone number.
        /// </summary>
        [Output("phoneId")]
        public Output<string?> PhoneId { get; private set; } = null!;

        /// <summary>
        /// The activity that the ruleset applies to.
        /// </summary>
        [Output("scope")]
        public Output<Jschady.Mailslurp.RulesetScope> Scope { get; private set; } = null!;

        /// <summary>
        /// The email address or the pattern that MailSlurp matches.
        /// </summary>
        [Output("target")]
        public Output<string> Target { get; private set; } = null!;


        /// <summary>
        /// Create a InboxRuleset resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public InboxRuleset(string name, InboxRulesetArgs args, CustomResourceOptions? options = null)
            : base("mailslurp:index:InboxRuleset", name, args ?? new InboxRulesetArgs(), MakeResourceOptions(options, ""))
        {
        }

        private InboxRuleset(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("mailslurp:index:InboxRuleset", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/jschady/pulumi-mailslurp",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing InboxRuleset resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static InboxRuleset Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new InboxRuleset(name, id, options);
        }
    }

    public sealed class InboxRulesetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The action that MailSlurp takes when the target matches. The `ALLOW`
        /// action wins over the `BLOCK` action. The `FILTER_REMOVE` action removes
        /// the matched address and keeps the rest of the email. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        /// </summary>
        [Input("action", required: true)]
        public Input<Jschady.Mailslurp.RulesetAction> Action { get; set; } = null!;

        /// <summary>
        /// The inbox that the ruleset applies to. MailSlurp matches the email of the
        /// inbox against the target. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        /// </summary>
        [Input("inboxId", required: true)]
        public Input<string> InboxId { get; set; } = null!;

        /// <summary>
        /// The activity that the ruleset applies to. Use `RECEIVING_EMAILS` for the
        /// email the inbox receives. Use `SENDING_EMAILS` for the email the inbox
        /// sends. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        /// </summary>
        [Input("scope", required: true)]
        public Input<Jschady.Mailslurp.RulesetScope> Scope { get; set; } = null!;

        /// <summary>
        /// The email address or the pattern that MailSlurp matches. Use
        /// `*@example.com` to match every address of a domain. Use one full address
        /// to match that address alone. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        /// </summary>
        [Input("target", required: true)]
        public Input<string> Target { get; set; } = null!;

        public InboxRulesetArgs()
        {
        }
        public static new InboxRulesetArgs Empty => new InboxRulesetArgs();
    }
}
