// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Mailslurp
{
    [MailslurpResourceType("pulumi:providers:mailslurp")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// The MailSlurp API key. The provider reads `MAILSLURP_API_KEY` when you
        /// do not set this property. The key is a secret, and Pulumi encrypts it
        /// in the state.
        /// </summary>
        [Output("apiKey")]
        public Output<string?> ApiKey { get; private set; } = null!;

        /// <summary>
        /// The base URL of the MailSlurp API. The default is
        /// `https://api.mailslurp.com`. Set this property only when you test
        /// against a different endpoint.
        /// </summary>
        [Output("endpoint")]
        public Output<string?> Endpoint { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs? args = null, CustomResourceOptions? options = null)
            : base("mailslurp", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/jschady/pulumi-mailslurp",
                AdditionalSecretOutputs =
                {
                    "apiKey",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiKey")]
        private Input<string>? _apiKey;

        /// <summary>
        /// The MailSlurp API key. The provider reads `MAILSLURP_API_KEY` when you
        /// do not set this property. The key is a secret, and Pulumi encrypts it
        /// in the state.
        /// </summary>
        public Input<string>? ApiKey
        {
            get => _apiKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _apiKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The base URL of the MailSlurp API. The default is
        /// `https://api.mailslurp.com`. Set this property only when you test
        /// against a different endpoint.
        /// </summary>
        [Input("endpoint")]
        public Input<string>? Endpoint { get; set; }

        public ProviderArgs()
        {
            ApiKey = Utilities.GetEnv("MAILSLURP_API_KEY") ?? "";
            Endpoint = "https://api.mailslurp.com";
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
