// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Mailslurp
{
    /// <summary>
    /// A webhook that MailSlurp calls when an event happens. MailSlurp posts the
    /// event payload to the URL that you set.
    /// 
    /// You can update every property of the webhook in place. Pulumi never
    /// replaces a webhook. A webhook that names no inbox listens to every inbox
    /// in the account. If you set the `inboxId` property, the webhook listens to
    /// that one inbox.
    /// 
    /// This resource does not carry the `basicAuth` property of the API. The API
    /// reports the property as a boolean, so Pulumi cannot compare the user name
    /// and the password that it sent. The webhook list of the API also reports
    /// both values as plain text. Use the `includeHeaders` property to
    /// authenticate the request.
    /// 
    /// ## Example Usage
    /// ### A webhook that posts every new email of one inbox to your server
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Mailslurp = Jschady.Mailslurp;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var alertInbox = new Mailslurp.Inbox("alert-inbox", new()
    ///     {
    ///         Name = "alert-inbox",
    ///     });
    /// 
    ///     var newEmailHook = new Mailslurp.Webhook("new-email-hook", new()
    ///     {
    ///         EventName = Mailslurp.WebhookEventName.NewEmail,
    ///         InboxId = alertInbox.Id,
    ///         Name = "new-email-hook",
    ///         Url = "https://example.com/mailslurp/new-email",
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["webhookId"] = newEmailHook.Id,
    ///     };
    /// });
    /// 
    /// ```
    /// </summary>
    [MailslurpResourceType("mailslurp:index:Webhook")]
    public partial class Webhook : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The time when MailSlurp created the webhook.
        /// </summary>
        [Output("createdAt")]
        public Output<string?> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// MailSlurp reports whether the webhook is enabled. The API does not
        /// document this property, and the value can be empty.
        /// </summary>
        [Output("enabled")]
        public Output<bool?> Enabled { get; private set; } = null!;

        /// <summary>
        /// The event that triggers the webhook.
        /// </summary>
        [Output("eventName")]
        public Output<Jschady.Mailslurp.WebhookEventName> EventName { get; private set; } = null!;

        /// <summary>
        /// The health of the webhook, as MailSlurp computes it. The value is
        /// `HEALTHY` or `UNHEALTHY`. The value changes often, so Pulumi never
        /// compares it.
        /// </summary>
        [Output("healthStatus")]
        public Output<string?> HealthStatus { get; private set; } = null!;

        /// <summary>
        /// MailSlurp reports whether it accepts an insecure SSL certificate on your server.
        /// </summary>
        [Output("ignoreInsecureSslCertificates")]
        public Output<bool> IgnoreInsecureSslCertificates { get; private set; } = null!;

        /// <summary>
        /// The inbox that triggers the webhook. An empty value means that every
        /// inbox in the account triggers the webhook.
        /// </summary>
        [Output("inboxId")]
        public Output<string?> InboxId { get; private set; } = null!;

        /// <summary>
        /// The HTTP headers that MailSlurp sends with each webhook request. The API
        /// names this value `requestHeaders` when it reports it.
        /// </summary>
        [Output("includeHeaders")]
        public Output<ImmutableDictionary<string, string>?> IncludeHeaders { get; private set; } = null!;

        /// <summary>
        /// The HTTP method that your server must accept. MailSlurp sends `POST`.
        /// </summary>
        [Output("method")]
        public Output<string> Method { get; private set; } = null!;

        /// <summary>
        /// The display name of the webhook.
        /// </summary>
        [Output("name")]
        public Output<string?> Name { get; private set; } = null!;

        /// <summary>
        /// The template for the JSON body of the webhook request.
        /// </summary>
        [Output("requestBodyTemplate")]
        public Output<string?> RequestBodyTemplate { get; private set; } = null!;

        /// <summary>
        /// The URL that MailSlurp posts the event payload to.
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;

        /// <summary>
        /// MailSlurp reports whether it calls your server from its static IP range.
        /// </summary>
        [Output("useStaticIpRange")]
        public Output<bool> UseStaticIpRange { get; private set; } = null!;


        /// <summary>
        /// Create a Webhook resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Webhook(string name, WebhookArgs args, CustomResourceOptions? options = null)
            : base("mailslurp:index:Webhook", name, args ?? new WebhookArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Webhook(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("mailslurp:index:Webhook", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/jschady/pulumi-mailslurp",
                AdditionalSecretOutputs =
                {
                    "includeHeaders",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Webhook resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Webhook Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Webhook(name, id, options);
        }
    }

    public sealed class WebhookArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The event that triggers the webhook. If you do not set this property,
        /// MailSlurp sends the `EMAIL_RECEIVED` event.
        /// </summary>
        [Input("eventName")]
        public Input<Jschady.Mailslurp.WebhookEventName>? EventName { get; set; }

        /// <summary>
        /// If you set this property, MailSlurp accepts an insecure SSL certificate
        /// on your server. Use it for a self-signed certificate. The default value
        /// is false.
        /// </summary>
        [Input("ignoreInsecureSslCertificates")]
        public Input<bool>? IgnoreInsecureSslCertificates { get; set; }

        /// <summary>
        /// The inbox that triggers the webhook. If you do not set this property,
        /// every inbox in the account triggers the webhook. You can move the webhook
        /// to another inbox in place. You cannot remove this property after you set
        /// it, because the API has no value for the account.
        /// </summary>
        [Input("inboxId")]
        public Input<string>? InboxId { get; set; }

        [Input("includeHeaders")]
        private InputMap<string>? _includeHeaders;

        /// <summary>
        /// The HTTP headers that MailSlurp sends with each webhook request. Each key
        /// is a header name, and each value is the header value. The provider marks
        /// the values as secret. MailSlurp reports the values as plain text, so
        /// anyone with the API key can read them.
        /// </summary>
        public InputMap<string> IncludeHeaders
        {
            get => _includeHeaders ?? (_includeHeaders = new InputMap<string>());
            set
            {
                var emptySecret = Output.CreateSecret(ImmutableDictionary.Create<string, string>());
                _includeHeaders = Output.All(value, emptySecret).Apply(v => v[0]);
            }
        }

        /// <summary>
        /// The display name of the webhook. You can update this property in place.
        /// Remove the property to clear the name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// A template for the JSON body of the webhook request. Use `{{variableName}}`
        /// markers to insert values from the event payload.
        /// </summary>
        [Input("requestBodyTemplate")]
        public Input<string>? RequestBodyTemplate { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// The tags on the webhook. MailSlurp accepts the tags and never reports
        /// them, so Pulumi cannot compare this property. A change to the tags alone
        /// plans no update.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The URL that MailSlurp posts the event payload to. Your server must
        /// accept the request. You can update this property in place.
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        /// <summary>
        /// If you set this property, MailSlurp calls your server from its static IP
        /// range. The default value is false.
        /// </summary>
        [Input("useStaticIpRange")]
        public Input<bool>? UseStaticIpRange { get; set; }

        public WebhookArgs()
        {
        }
        public static new WebhookArgs Empty => new WebhookArgs();
    }
}
