// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -typed -package internal -source client.go -destination mockclient_test.go --self_package github.com/jschady/pulumi-mailslurp/provider/internal
//

// Package internal is a generated GoMock package.
package internal

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateAccountWebhook mocks base method.
func (m *MockClient) CreateAccountWebhook(ctx context.Context, opts WebhookOptions) (*WebhookDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountWebhook", ctx, opts)
	ret0, _ := ret[0].(*WebhookDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccountWebhook indicates an expected call of CreateAccountWebhook.
func (mr *MockClientMockRecorder) CreateAccountWebhook(ctx, opts any) *MockClientCreateAccountWebhookCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountWebhook", reflect.TypeOf((*MockClient)(nil).CreateAccountWebhook), ctx, opts)
	return &MockClientCreateAccountWebhookCall{Call: call}
}

// MockClientCreateAccountWebhookCall wrap *gomock.Call
type MockClientCreateAccountWebhookCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCreateAccountWebhookCall) Return(arg0 *WebhookDto, arg1 error) *MockClientCreateAccountWebhookCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCreateAccountWebhookCall) Do(f func(context.Context, WebhookOptions) (*WebhookDto, error)) *MockClientCreateAccountWebhookCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCreateAccountWebhookCall) DoAndReturn(f func(context.Context, WebhookOptions) (*WebhookDto, error)) *MockClientCreateAccountWebhookCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateForwarder mocks base method.
func (m *MockClient) CreateForwarder(ctx context.Context, inboxID string, opts ForwarderOptions) (*ForwarderDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForwarder", ctx, inboxID, opts)
	ret0, _ := ret[0].(*ForwarderDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateForwarder indicates an expected call of CreateForwarder.
func (mr *MockClientMockRecorder) CreateForwarder(ctx, inboxID, opts any) *MockClientCreateForwarderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForwarder", reflect.TypeOf((*MockClient)(nil).CreateForwarder), ctx, inboxID, opts)
	return &MockClientCreateForwarderCall{Call: call}
}

// MockClientCreateForwarderCall wrap *gomock.Call
type MockClientCreateForwarderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCreateForwarderCall) Return(arg0 *ForwarderDto, arg1 error) *MockClientCreateForwarderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCreateForwarderCall) Do(f func(context.Context, string, ForwarderOptions) (*ForwarderDto, error)) *MockClientCreateForwarderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCreateForwarderCall) DoAndReturn(f func(context.Context, string, ForwarderOptions) (*ForwarderDto, error)) *MockClientCreateForwarderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateInbox mocks base method.
func (m *MockClient) CreateInbox(ctx context.Context, opts CreateInboxOptions) (*InboxDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInbox", ctx, opts)
	ret0, _ := ret[0].(*InboxDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInbox indicates an expected call of CreateInbox.
func (mr *MockClientMockRecorder) CreateInbox(ctx, opts any) *MockClientCreateInboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInbox", reflect.TypeOf((*MockClient)(nil).CreateInbox), ctx, opts)
	return &MockClientCreateInboxCall{Call: call}
}

// MockClientCreateInboxCall wrap *gomock.Call
type MockClientCreateInboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCreateInboxCall) Return(arg0 *InboxDto, arg1 error) *MockClientCreateInboxCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCreateInboxCall) Do(f func(context.Context, CreateInboxOptions) (*InboxDto, error)) *MockClientCreateInboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCreateInboxCall) DoAndReturn(f func(context.Context, CreateInboxOptions) (*InboxDto, error)) *MockClientCreateInboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateInboxWebhook mocks base method.
func (m *MockClient) CreateInboxWebhook(ctx context.Context, inboxID string, opts WebhookOptions) (*WebhookDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInboxWebhook", ctx, inboxID, opts)
	ret0, _ := ret[0].(*WebhookDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInboxWebhook indicates an expected call of CreateInboxWebhook.
func (mr *MockClientMockRecorder) CreateInboxWebhook(ctx, inboxID, opts any) *MockClientCreateInboxWebhookCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInboxWebhook", reflect.TypeOf((*MockClient)(nil).CreateInboxWebhook), ctx, inboxID, opts)
	return &MockClientCreateInboxWebhookCall{Call: call}
}

// MockClientCreateInboxWebhookCall wrap *gomock.Call
type MockClientCreateInboxWebhookCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCreateInboxWebhookCall) Return(arg0 *WebhookDto, arg1 error) *MockClientCreateInboxWebhookCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCreateInboxWebhookCall) Do(f func(context.Context, string, WebhookOptions) (*WebhookDto, error)) *MockClientCreateInboxWebhookCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCreateInboxWebhookCall) DoAndReturn(f func(context.Context, string, WebhookOptions) (*WebhookDto, error)) *MockClientCreateInboxWebhookCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateRuleset mocks base method.
func (m *MockClient) CreateRuleset(ctx context.Context, inboxID string, opts RulesetOptions) (*RulesetDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRuleset", ctx, inboxID, opts)
	ret0, _ := ret[0].(*RulesetDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRuleset indicates an expected call of CreateRuleset.
func (mr *MockClientMockRecorder) CreateRuleset(ctx, inboxID, opts any) *MockClientCreateRulesetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRuleset", reflect.TypeOf((*MockClient)(nil).CreateRuleset), ctx, inboxID, opts)
	return &MockClientCreateRulesetCall{Call: call}
}

// MockClientCreateRulesetCall wrap *gomock.Call
type MockClientCreateRulesetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCreateRulesetCall) Return(arg0 *RulesetDto, arg1 error) *MockClientCreateRulesetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCreateRulesetCall) Do(f func(context.Context, string, RulesetOptions) (*RulesetDto, error)) *MockClientCreateRulesetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCreateRulesetCall) DoAndReturn(f func(context.Context, string, RulesetOptions) (*RulesetDto, error)) *MockClientCreateRulesetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateTemplate mocks base method.
func (m *MockClient) CreateTemplate(ctx context.Context, opts TemplateOptions) (*TemplateDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", ctx, opts)
	ret0, _ := ret[0].(*TemplateDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockClientMockRecorder) CreateTemplate(ctx, opts any) *MockClientCreateTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockClient)(nil).CreateTemplate), ctx, opts)
	return &MockClientCreateTemplateCall{Call: call}
}

// MockClientCreateTemplateCall wrap *gomock.Call
type MockClientCreateTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCreateTemplateCall) Return(arg0 *TemplateDto, arg1 error) *MockClientCreateTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCreateTemplateCall) Do(f func(context.Context, TemplateOptions) (*TemplateDto, error)) *MockClientCreateTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCreateTemplateCall) DoAndReturn(f func(context.Context, TemplateOptions) (*TemplateDto, error)) *MockClientCreateTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteForwarder mocks base method.
func (m *MockClient) DeleteForwarder(ctx context.Context, forwarderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForwarder", ctx, forwarderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteForwarder indicates an expected call of DeleteForwarder.
func (mr *MockClientMockRecorder) DeleteForwarder(ctx, forwarderID any) *MockClientDeleteForwarderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForwarder", reflect.TypeOf((*MockClient)(nil).DeleteForwarder), ctx, forwarderID)
	return &MockClientDeleteForwarderCall{Call: call}
}

// MockClientDeleteForwarderCall wrap *gomock.Call
type MockClientDeleteForwarderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientDeleteForwarderCall) Return(arg0 error) *MockClientDeleteForwarderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientDeleteForwarderCall) Do(f func(context.Context, string) error) *MockClientDeleteForwarderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientDeleteForwarderCall) DoAndReturn(f func(context.Context, string) error) *MockClientDeleteForwarderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteInbox mocks base method.
func (m *MockClient) DeleteInbox(ctx context.Context, inboxID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInbox", ctx, inboxID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInbox indicates an expected call of DeleteInbox.
func (mr *MockClientMockRecorder) DeleteInbox(ctx, inboxID any) *MockClientDeleteInboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInbox", reflect.TypeOf((*MockClient)(nil).DeleteInbox), ctx, inboxID)
	return &MockClientDeleteInboxCall{Call: call}
}

// MockClientDeleteInboxCall wrap *gomock.Call
type MockClientDeleteInboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientDeleteInboxCall) Return(arg0 error) *MockClientDeleteInboxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientDeleteInboxCall) Do(f func(context.Context, string) error) *MockClientDeleteInboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientDeleteInboxCall) DoAndReturn(f func(context.Context, string) error) *MockClientDeleteInboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteRuleset mocks base method.
func (m *MockClient) DeleteRuleset(ctx context.Context, rulesetID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRuleset", ctx, rulesetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRuleset indicates an expected call of DeleteRuleset.
func (mr *MockClientMockRecorder) DeleteRuleset(ctx, rulesetID any) *MockClientDeleteRulesetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRuleset", reflect.TypeOf((*MockClient)(nil).DeleteRuleset), ctx, rulesetID)
	return &MockClientDeleteRulesetCall{Call: call}
}

// MockClientDeleteRulesetCall wrap *gomock.Call
type MockClientDeleteRulesetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientDeleteRulesetCall) Return(arg0 error) *MockClientDeleteRulesetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientDeleteRulesetCall) Do(f func(context.Context, string) error) *MockClientDeleteRulesetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientDeleteRulesetCall) DoAndReturn(f func(context.Context, string) error) *MockClientDeleteRulesetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteTemplate mocks base method.
func (m *MockClient) DeleteTemplate(ctx context.Context, templateID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", ctx, templateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockClientMockRecorder) DeleteTemplate(ctx, templateID any) *MockClientDeleteTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockClient)(nil).DeleteTemplate), ctx, templateID)
	return &MockClientDeleteTemplateCall{Call: call}
}

// MockClientDeleteTemplateCall wrap *gomock.Call
type MockClientDeleteTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientDeleteTemplateCall) Return(arg0 error) *MockClientDeleteTemplateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientDeleteTemplateCall) Do(f func(context.Context, string) error) *MockClientDeleteTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientDeleteTemplateCall) DoAndReturn(f func(context.Context, string) error) *MockClientDeleteTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteWebhook mocks base method.
func (m *MockClient) DeleteWebhook(ctx context.Context, webhookID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebhook", ctx, webhookID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWebhook indicates an expected call of DeleteWebhook.
func (mr *MockClientMockRecorder) DeleteWebhook(ctx, webhookID any) *MockClientDeleteWebhookCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebhook", reflect.TypeOf((*MockClient)(nil).DeleteWebhook), ctx, webhookID)
	return &MockClientDeleteWebhookCall{Call: call}
}

// MockClientDeleteWebhookCall wrap *gomock.Call
type MockClientDeleteWebhookCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientDeleteWebhookCall) Return(arg0 error) *MockClientDeleteWebhookCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientDeleteWebhookCall) Do(f func(context.Context, string) error) *MockClientDeleteWebhookCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientDeleteWebhookCall) DoAndReturn(f func(context.Context, string) error) *MockClientDeleteWebhookCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDomain mocks base method.
func (m *MockClient) GetDomain(ctx context.Context, domainID string, checkForErrors bool) (*DomainDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomain", ctx, domainID, checkForErrors)
	ret0, _ := ret[0].(*DomainDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDomain indicates an expected call of GetDomain.
func (mr *MockClientMockRecorder) GetDomain(ctx, domainID, checkForErrors any) *MockClientGetDomainCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomain", reflect.TypeOf((*MockClient)(nil).GetDomain), ctx, domainID, checkForErrors)
	return &MockClientGetDomainCall{Call: call}
}

// MockClientGetDomainCall wrap *gomock.Call
type MockClientGetDomainCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetDomainCall) Return(arg0 *DomainDto, arg1 error) *MockClientGetDomainCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetDomainCall) Do(f func(context.Context, string, bool) (*DomainDto, error)) *MockClientGetDomainCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetDomainCall) DoAndReturn(f func(context.Context, string, bool) (*DomainDto, error)) *MockClientGetDomainCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetForwarder mocks base method.
func (m *MockClient) GetForwarder(ctx context.Context, forwarderID string) (*ForwarderDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForwarder", ctx, forwarderID)
	ret0, _ := ret[0].(*ForwarderDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForwarder indicates an expected call of GetForwarder.
func (mr *MockClientMockRecorder) GetForwarder(ctx, forwarderID any) *MockClientGetForwarderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForwarder", reflect.TypeOf((*MockClient)(nil).GetForwarder), ctx, forwarderID)
	return &MockClientGetForwarderCall{Call: call}
}

// MockClientGetForwarderCall wrap *gomock.Call
type MockClientGetForwarderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetForwarderCall) Return(arg0 *ForwarderDto, arg1 error) *MockClientGetForwarderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetForwarderCall) Do(f func(context.Context, string) (*ForwarderDto, error)) *MockClientGetForwarderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetForwarderCall) DoAndReturn(f func(context.Context, string) (*ForwarderDto, error)) *MockClientGetForwarderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetInbox mocks base method.
func (m *MockClient) GetInbox(ctx context.Context, inboxID string) (*InboxDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInbox", ctx, inboxID)
	ret0, _ := ret[0].(*InboxDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInbox indicates an expected call of GetInbox.
func (mr *MockClientMockRecorder) GetInbox(ctx, inboxID any) *MockClientGetInboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInbox", reflect.TypeOf((*MockClient)(nil).GetInbox), ctx, inboxID)
	return &MockClientGetInboxCall{Call: call}
}

// MockClientGetInboxCall wrap *gomock.Call
type MockClientGetInboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetInboxCall) Return(arg0 *InboxDto, arg1 error) *MockClientGetInboxCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetInboxCall) Do(f func(context.Context, string) (*InboxDto, error)) *MockClientGetInboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetInboxCall) DoAndReturn(f func(context.Context, string) (*InboxDto, error)) *MockClientGetInboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRuleset mocks base method.
func (m *MockClient) GetRuleset(ctx context.Context, rulesetID string) (*RulesetDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRuleset", ctx, rulesetID)
	ret0, _ := ret[0].(*RulesetDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRuleset indicates an expected call of GetRuleset.
func (mr *MockClientMockRecorder) GetRuleset(ctx, rulesetID any) *MockClientGetRulesetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRuleset", reflect.TypeOf((*MockClient)(nil).GetRuleset), ctx, rulesetID)
	return &MockClientGetRulesetCall{Call: call}
}

// MockClientGetRulesetCall wrap *gomock.Call
type MockClientGetRulesetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetRulesetCall) Return(arg0 *RulesetDto, arg1 error) *MockClientGetRulesetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetRulesetCall) Do(f func(context.Context, string) (*RulesetDto, error)) *MockClientGetRulesetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetRulesetCall) DoAndReturn(f func(context.Context, string) (*RulesetDto, error)) *MockClientGetRulesetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTemplate mocks base method.
func (m *MockClient) GetTemplate(ctx context.Context, templateID string) (*TemplateDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplate", ctx, templateID)
	ret0, _ := ret[0].(*TemplateDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockClientMockRecorder) GetTemplate(ctx, templateID any) *MockClientGetTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockClient)(nil).GetTemplate), ctx, templateID)
	return &MockClientGetTemplateCall{Call: call}
}

// MockClientGetTemplateCall wrap *gomock.Call
type MockClientGetTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetTemplateCall) Return(arg0 *TemplateDto, arg1 error) *MockClientGetTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetTemplateCall) Do(f func(context.Context, string) (*TemplateDto, error)) *MockClientGetTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetTemplateCall) DoAndReturn(f func(context.Context, string) (*TemplateDto, error)) *MockClientGetTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetWebhook mocks base method.
func (m *MockClient) GetWebhook(ctx context.Context, webhookID string) (*WebhookDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhook", ctx, webhookID)
	ret0, _ := ret[0].(*WebhookDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhook indicates an expected call of GetWebhook.
func (mr *MockClientMockRecorder) GetWebhook(ctx, webhookID any) *MockClientGetWebhookCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhook", reflect.TypeOf((*MockClient)(nil).GetWebhook), ctx, webhookID)
	return &MockClientGetWebhookCall{Call: call}
}

// MockClientGetWebhookCall wrap *gomock.Call
type MockClientGetWebhookCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetWebhookCall) Return(arg0 *WebhookDto, arg1 error) *MockClientGetWebhookCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetWebhookCall) Do(f func(context.Context, string) (*WebhookDto, error)) *MockClientGetWebhookCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetWebhookCall) DoAndReturn(f func(context.Context, string) (*WebhookDto, error)) *MockClientGetWebhookCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateForwarder mocks base method.
func (m *MockClient) UpdateForwarder(ctx context.Context, forwarderID string, opts ForwarderOptions) (*ForwarderDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateForwarder", ctx, forwarderID, opts)
	ret0, _ := ret[0].(*ForwarderDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateForwarder indicates an expected call of UpdateForwarder.
func (mr *MockClientMockRecorder) UpdateForwarder(ctx, forwarderID, opts any) *MockClientUpdateForwarderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateForwarder", reflect.TypeOf((*MockClient)(nil).UpdateForwarder), ctx, forwarderID, opts)
	return &MockClientUpdateForwarderCall{Call: call}
}

// MockClientUpdateForwarderCall wrap *gomock.Call
type MockClientUpdateForwarderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientUpdateForwarderCall) Return(arg0 *ForwarderDto, arg1 error) *MockClientUpdateForwarderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientUpdateForwarderCall) Do(f func(context.Context, string, ForwarderOptions) (*ForwarderDto, error)) *MockClientUpdateForwarderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientUpdateForwarderCall) DoAndReturn(f func(context.Context, string, ForwarderOptions) (*ForwarderDto, error)) *MockClientUpdateForwarderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateInbox mocks base method.
func (m *MockClient) UpdateInbox(ctx context.Context, inboxID string, opts UpdateInboxOptions) (*InboxDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInbox", ctx, inboxID, opts)
	ret0, _ := ret[0].(*InboxDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInbox indicates an expected call of UpdateInbox.
func (mr *MockClientMockRecorder) UpdateInbox(ctx, inboxID, opts any) *MockClientUpdateInboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInbox", reflect.TypeOf((*MockClient)(nil).UpdateInbox), ctx, inboxID, opts)
	return &MockClientUpdateInboxCall{Call: call}
}

// MockClientUpdateInboxCall wrap *gomock.Call
type MockClientUpdateInboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientUpdateInboxCall) Return(arg0 *InboxDto, arg1 error) *MockClientUpdateInboxCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientUpdateInboxCall) Do(f func(context.Context, string, UpdateInboxOptions) (*InboxDto, error)) *MockClientUpdateInboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientUpdateInboxCall) DoAndReturn(f func(context.Context, string, UpdateInboxOptions) (*InboxDto, error)) *MockClientUpdateInboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTemplate mocks base method.
func (m *MockClient) UpdateTemplate(ctx context.Context, templateID string, opts TemplateOptions) (*TemplateDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", ctx, templateID, opts)
	ret0, _ := ret[0].(*TemplateDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockClientMockRecorder) UpdateTemplate(ctx, templateID, opts any) *MockClientUpdateTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockClient)(nil).UpdateTemplate), ctx, templateID, opts)
	return &MockClientUpdateTemplateCall{Call: call}
}

// MockClientUpdateTemplateCall wrap *gomock.Call
type MockClientUpdateTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientUpdateTemplateCall) Return(arg0 *TemplateDto, arg1 error) *MockClientUpdateTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientUpdateTemplateCall) Do(f func(context.Context, string, TemplateOptions) (*TemplateDto, error)) *MockClientUpdateTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientUpdateTemplateCall) DoAndReturn(f func(context.Context, string, TemplateOptions) (*TemplateDto, error)) *MockClientUpdateTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateWebhook mocks base method.
func (m *MockClient) UpdateWebhook(ctx context.Context, webhookID string, inboxID *string, opts WebhookOptions) (*WebhookDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebhook", ctx, webhookID, inboxID, opts)
	ret0, _ := ret[0].(*WebhookDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWebhook indicates an expected call of UpdateWebhook.
func (mr *MockClientMockRecorder) UpdateWebhook(ctx, webhookID, inboxID, opts any) *MockClientUpdateWebhookCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebhook", reflect.TypeOf((*MockClient)(nil).UpdateWebhook), ctx, webhookID, inboxID, opts)
	return &MockClientUpdateWebhookCall{Call: call}
}

// MockClientUpdateWebhookCall wrap *gomock.Call
type MockClientUpdateWebhookCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientUpdateWebhookCall) Return(arg0 *WebhookDto, arg1 error) *MockClientUpdateWebhookCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientUpdateWebhookCall) Do(f func(context.Context, string, *string, WebhookOptions) (*WebhookDto, error)) *MockClientUpdateWebhookCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientUpdateWebhookCall) DoAndReturn(f func(context.Context, string, *string, WebhookOptions) (*WebhookDto, error)) *MockClientUpdateWebhookCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateWebhookHeaders mocks base method.
func (m *MockClient) UpdateWebhookHeaders(ctx context.Context, webhookID string, headers WebhookHeaders) (*WebhookDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebhookHeaders", ctx, webhookID, headers)
	ret0, _ := ret[0].(*WebhookDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWebhookHeaders indicates an expected call of UpdateWebhookHeaders.
func (mr *MockClientMockRecorder) UpdateWebhookHeaders(ctx, webhookID, headers any) *MockClientUpdateWebhookHeadersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebhookHeaders", reflect.TypeOf((*MockClient)(nil).UpdateWebhookHeaders), ctx, webhookID, headers)
	return &MockClientUpdateWebhookHeadersCall{Call: call}
}

// MockClientUpdateWebhookHeadersCall wrap *gomock.Call
type MockClientUpdateWebhookHeadersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientUpdateWebhookHeadersCall) Return(arg0 *WebhookDto, arg1 error) *MockClientUpdateWebhookHeadersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientUpdateWebhookHeadersCall) Do(f func(context.Context, string, WebhookHeaders) (*WebhookDto, error)) *MockClientUpdateWebhookHeadersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientUpdateWebhookHeadersCall) DoAndReturn(f func(context.Context, string, WebhookHeaders) (*WebhookDto, error)) *MockClientUpdateWebhookHeadersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
