# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .email_template import *
from .get_domain import *
from .get_inbox import *
from .inbox import *
from .inbox_forwarder import *
from .inbox_ruleset import *
from .provider import *
from .webhook import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_mailslurp.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_mailslurp.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "mailslurp",
  "mod": "index",
  "fqn": "pulumi_mailslurp",
  "classes": {
   "mailslurp:index:EmailTemplate": "EmailTemplate",
   "mailslurp:index:Inbox": "Inbox",
   "mailslurp:index:InboxForwarder": "InboxForwarder",
   "mailslurp:index:InboxRuleset": "InboxRuleset",
   "mailslurp:index:Webhook": "Webhook"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "mailslurp",
  "token": "pulumi:providers:mailslurp",
  "fqn": "pulumi_mailslurp",
  "class": "Provider"
 }
]
"""
)
