# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'DomainType',
    'ForwarderField',
    'ForwarderMatchOperator',
    'ForwarderShould',
    'InboxType',
    'RulesetAction',
    'RulesetScope',
    'WebhookEventName',
]


@pulumi.type_token("mailslurp:index:DomainType")
class DomainType(_builtins.str, Enum):
    HTTP_INBOX = "HTTP_INBOX"
    """
    The domain serves inboxes that store email with HTTP endpoints.
    """
    SMTP_DOMAIN = "SMTP_DOMAIN"
    """
    The domain serves inboxes that receive email on a real SMTP mail server.
    """


@pulumi.type_token("mailslurp:index:ForwarderField")
class ForwarderField(_builtins.str, Enum):
    RECIPIENTS = "RECIPIENTS"
    """
    MailSlurp compares the addresses that the email went to.
    """
    SENDER = "SENDER"
    """
    MailSlurp compares the address that sent the email.
    """
    SUBJECT = "SUBJECT"
    """
    MailSlurp compares the subject of the email.
    """
    ATTACHMENTS = "ATTACHMENTS"
    """
    MailSlurp compares the attachments of the email.
    """
    ATTACHMENT_FILENAME = "ATTACHMENT_FILENAME"
    """
    MailSlurp compares the file name of each attachment.
    """
    ATTACHMENT_TEXT = "ATTACHMENT_TEXT"
    """
    MailSlurp compares the text inside each attachment.
    """


@pulumi.type_token("mailslurp:index:ForwarderMatchOperator")
class ForwarderMatchOperator(_builtins.str, Enum):
    AND_ = "AND"
    """
    MailSlurp forwards the email when every rule of the group matches.
    """
    OR_ = "OR"
    """
    MailSlurp forwards the email when one rule of the group matches.
    """


@pulumi.type_token("mailslurp:index:ForwarderShould")
class ForwarderShould(_builtins.str, Enum):
    WILDCARD = "WILDCARD"
    """
    MailSlurp reads the match value as a pattern. A star matches every character.
    """
    MATCH = "MATCH"
    """
    MailSlurp compares the part with the whole match value. The API does not state how this mode differs from `EQUAL`.
    """
    CONTAIN = "CONTAIN"
    """
    MailSlurp forwards the email when the part holds the match value inside it.
    """
    EQUAL = "EQUAL"
    """
    MailSlurp forwards the email when the part and the match value are the same.
    """


@pulumi.type_token("mailslurp:index:InboxType")
class InboxType(_builtins.str, Enum):
    HTTP_INBOX = "HTTP_INBOX"
    """
    The inbox stores email with HTTP endpoints. Use this type for tests and webhooks.
    """
    SMTP_INBOX = "SMTP_INBOX"
    """
    The inbox receives email on a real SMTP mail server. Use this type for external senders.
    """


@pulumi.type_token("mailslurp:index:RulesetAction")
class RulesetAction(_builtins.str, Enum):
    BLOCK = "BLOCK"
    """
    MailSlurp stops the email when the target matches.
    """
    ALLOW = "ALLOW"
    """
    MailSlurp permits the email when the target matches, and this action wins over a block.
    """
    FILTER_REMOVE = "FILTER_REMOVE"
    """
    MailSlurp removes the matched address from the email, and the rest of the email continues.
    """
    BOUNCE_SOFT = "BOUNCE_SOFT"
    """
    MailSlurp answers the sender with a soft bounce, which states a temporary failure.
    """
    BOUNCE_HARD = "BOUNCE_HARD"
    """
    MailSlurp answers the sender with a hard bounce, which states a permanent failure.
    """


@pulumi.type_token("mailslurp:index:RulesetScope")
class RulesetScope(_builtins.str, Enum):
    RECEIVING_EMAILS = "RECEIVING_EMAILS"
    """
    MailSlurp applies the ruleset to every email that the inbox receives.
    """
    SENDING_EMAILS = "SENDING_EMAILS"
    """
    MailSlurp applies the ruleset to every email that the inbox sends.
    """
    RECEIVING_SMS = "RECEIVING_SMS"
    """
    MailSlurp applies the ruleset to every SMS message that a phone number receives.
    """
    SENDING_SMS = "SENDING_SMS"
    """
    MailSlurp applies the ruleset to every SMS message that a phone number sends.
    """


@pulumi.type_token("mailslurp:index:WebhookEventName")
class WebhookEventName(_builtins.str, Enum):
    EMAIL_RECEIVED = "EMAIL_RECEIVED"
    """
    MailSlurp sends the event when an inbox receives an email payload.
    """
    NEW_AI_TRANSFORM_RESULT = "NEW_AI_TRANSFORM_RESULT"
    """
    MailSlurp sends the event when an AI transformer produces a new extraction result.
    """
    NEW_EMAIL = "NEW_EMAIL"
    """
    MailSlurp sends the event when an inbox receives a new email.
    """
    NEW_CONTACT = "NEW_CONTACT"
    """
    MailSlurp sends the event when it creates a contact from inbound email activity.
    """
    NEW_ATTACHMENT = "NEW_ATTACHMENT"
    """
    MailSlurp sends the event when it detects an attachment on a received email.
    """
    EMAIL_OPENED = "EMAIL_OPENED"
    """
    MailSlurp sends the event when it tracks an email open.
    """
    EMAIL_READ = "EMAIL_READ"
    """
    MailSlurp sends the event when a recipient reads an email.
    """
    DELIVERY_STATUS = "DELIVERY_STATUS"
    """
    MailSlurp sends the event when the delivery status of a sent email changes.
    """
    BOUNCE = "BOUNCE"
    """
    MailSlurp sends the event when an email bounces at the account level.
    """
    BOUNCE_RECIPIENT = "BOUNCE_RECIPIENT"
    """
    MailSlurp sends the event when an email address bounces.
    """
    NEW_SMS = "NEW_SMS"
    """
    MailSlurp sends the event when a phone number receives an SMS message.
    """
    NEW_GUEST_USER = "NEW_GUEST_USER"
    """
    MailSlurp sends the event for a guest user.
    """
