# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = [
    'InboxForwarderMatchGroupArgs',
    'InboxForwarderMatchGroupArgsDict',
    'InboxForwarderMatchRuleArgs',
    'InboxForwarderMatchRuleArgsDict',
]

class InboxForwarderMatchGroupArgsDict(TypedDict):
    operator: pulumi.Input['ForwarderMatchOperator']
    """
    The way that MailSlurp joins the rules of this group. Use `AND` when
    every rule must match. Use `OR` when one rule is enough.
    """
    groups: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['InboxForwarderMatchGroupArgsDict']]]]]
    """
    The groups that this group holds. Put a group inside a group to build a
    deeper tree.
    """
    matches: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['InboxForwarderMatchRuleArgsDict']]]]]
    """
    The rules that MailSlurp applies to the email.
    """

@pulumi.input_type
class InboxForwarderMatchGroupArgs:
    def __init__(__self__, *,
                 operator: pulumi.Input['ForwarderMatchOperator'],
                 groups: pulumi.Input[Optional[Sequence[pulumi.Input['InboxForwarderMatchGroupArgs']]]] = None,
                 matches: pulumi.Input[Optional[Sequence[pulumi.Input['InboxForwarderMatchRuleArgs']]]] = None):
        """
        :param pulumi.Input['ForwarderMatchOperator'] operator: The way that MailSlurp joins the rules of this group. Use `AND` when
               every rule must match. Use `OR` when one rule is enough.
        :param pulumi.Input[Sequence[pulumi.Input['InboxForwarderMatchGroupArgs']]] groups: The groups that this group holds. Put a group inside a group to build a
               deeper tree.
        :param pulumi.Input[Sequence[pulumi.Input['InboxForwarderMatchRuleArgs']]] matches: The rules that MailSlurp applies to the email.
        """
        pulumi.set(__self__, "operator", operator)
        if groups is not None:
            pulumi.set(__self__, "groups", groups)
        if matches is not None:
            pulumi.set(__self__, "matches", matches)

    @_builtins.property
    @pulumi.getter
    def operator(self) -> pulumi.Input['ForwarderMatchOperator']:
        """
        The way that MailSlurp joins the rules of this group. Use `AND` when
        every rule must match. Use `OR` when one rule is enough.
        """
        return pulumi.get(self, "operator")

    @operator.setter
    def operator(self, value: pulumi.Input['ForwarderMatchOperator']):
        pulumi.set(self, "operator", value)

    @_builtins.property
    @pulumi.getter
    def groups(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['InboxForwarderMatchGroupArgs']]]]:
        """
        The groups that this group holds. Put a group inside a group to build a
        deeper tree.
        """
        return pulumi.get(self, "groups")

    @groups.setter
    def groups(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['InboxForwarderMatchGroupArgs']]]]):
        pulumi.set(self, "groups", value)

    @_builtins.property
    @pulumi.getter
    def matches(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['InboxForwarderMatchRuleArgs']]]]:
        """
        The rules that MailSlurp applies to the email.
        """
        return pulumi.get(self, "matches")

    @matches.setter
    def matches(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['InboxForwarderMatchRuleArgs']]]]):
        pulumi.set(self, "matches", value)


class InboxForwarderMatchRuleArgsDict(TypedDict):
    field: pulumi.Input['ForwarderField']
    """
    The part of the email that MailSlurp compares against the `value` property.
    """
    should: pulumi.Input['ForwarderShould']
    """
    The way that MailSlurp compares the `value` property.
    """
    value: pulumi.Input[_builtins.str]
    """
    The value or the pattern that MailSlurp compares.
    """

@pulumi.input_type
class InboxForwarderMatchRuleArgs:
    def __init__(__self__, *,
                 field: pulumi.Input['ForwarderField'],
                 should: pulumi.Input['ForwarderShould'],
                 value: pulumi.Input[_builtins.str]):
        """
        :param pulumi.Input['ForwarderField'] field: The part of the email that MailSlurp compares against the `value` property.
        :param pulumi.Input['ForwarderShould'] should: The way that MailSlurp compares the `value` property.
        :param pulumi.Input[_builtins.str] value: The value or the pattern that MailSlurp compares.
        """
        pulumi.set(__self__, "field", field)
        pulumi.set(__self__, "should", should)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def field(self) -> pulumi.Input['ForwarderField']:
        """
        The part of the email that MailSlurp compares against the `value` property.
        """
        return pulumi.get(self, "field")

    @field.setter
    def field(self, value: pulumi.Input['ForwarderField']):
        pulumi.set(self, "field", value)

    @_builtins.property
    @pulumi.getter
    def should(self) -> pulumi.Input['ForwarderShould']:
        """
        The way that MailSlurp compares the `value` property.
        """
        return pulumi.get(self, "should")

    @should.setter
    def should(self, value: pulumi.Input['ForwarderShould']):
        pulumi.set(self, "should", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Input[_builtins.str]:
        """
        The value or the pattern that MailSlurp compares.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "value", value)


