# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = ['EmailTemplateArgs', 'EmailTemplate']

@pulumi.input_type
class EmailTemplateArgs:
    def __init__(__self__, *,
                 content: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a EmailTemplate resource.

        :param pulumi.Input[_builtins.str] content: The body of the template. Write a variable as `{{firstName}}`, and
               MailSlurp reports each variable that it reads in the `variables` property.
               You can update this property in place.
        :param pulumi.Input[_builtins.str] name: The display name of the template. You can update this property in place.
        """
        pulumi.set(__self__, "content", content)
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def content(self) -> pulumi.Input[_builtins.str]:
        """
        The body of the template. Write a variable as `{{firstName}}`, and
        MailSlurp reports each variable that it reads in the `variables` property.
        You can update this property in place.
        """
        return pulumi.get(self, "content")

    @content.setter
    def content(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "content", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The display name of the template. You can update this property in place.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)


@pulumi.type_token("mailslurp:index:EmailTemplate")
class EmailTemplate(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 content: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        An email template that MailSlurp fills with values when you send an email.
        You write each variable inside the content with the moustache markers.

        You can update the `name` and the `content` of a template in place. Pulumi
        never replaces a template. MailSlurp parses the `variables` list from the
        content, so you cannot set it. A template is free, and it never counts
        against the inbox creation quota.

        ## Example Usage
        ### A template that MailSlurp fills with two variables
        ```python
        import pulumi
        import pulumi_mailslurp as mailslurp

        welcome_template = mailslurp.EmailTemplate("welcome-template",
            content=\"\"\"Hello {{firstName}},
        Your inbox {{inboxAddress}} is ready.
        \"\"\",
            name="welcome-template")
        pulumi.export("variables", welcome_template.variables)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] content: The body of the template. Write a variable as `{{firstName}}`, and
               MailSlurp reports each variable that it reads in the `variables` property.
               You can update this property in place.
        :param pulumi.Input[_builtins.str] name: The display name of the template. You can update this property in place.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: EmailTemplateArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        An email template that MailSlurp fills with values when you send an email.
        You write each variable inside the content with the moustache markers.

        You can update the `name` and the `content` of a template in place. Pulumi
        never replaces a template. MailSlurp parses the `variables` list from the
        content, so you cannot set it. A template is free, and it never counts
        against the inbox creation quota.

        ## Example Usage
        ### A template that MailSlurp fills with two variables
        ```python
        import pulumi
        import pulumi_mailslurp as mailslurp

        welcome_template = mailslurp.EmailTemplate("welcome-template",
            content=\"\"\"Hello {{firstName}},
        Your inbox {{inboxAddress}} is ready.
        \"\"\",
            name="welcome-template")
        pulumi.export("variables", welcome_template.variables)
        ```


        :param str resource_name: The name of the resource.
        :param EmailTemplateArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(EmailTemplateArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 content: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = EmailTemplateArgs.__new__(EmailTemplateArgs)

            if content is None and not opts.urn:
                raise TypeError("Missing required property 'content'")
            __props__.__dict__["content"] = content
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["created_at"] = None
            __props__.__dict__["variables"] = None
        super(EmailTemplate, __self__).__init__(
            'mailslurp:index:EmailTemplate',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'EmailTemplate':
        """
        Get an existing EmailTemplate resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = EmailTemplateArgs.__new__(EmailTemplateArgs)

        __props__.__dict__["content"] = None
        __props__.__dict__["created_at"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["variables"] = None
        return EmailTemplate(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def content(self) -> pulumi.Output[_builtins.str]:
        """
        The body of the template.
        """
        return pulumi.get(self, "content")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        The time when MailSlurp created the template.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The display name of the template.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def variables(self) -> pulumi.Output[Sequence['outputs.EmailTemplateVariable']]:
        """
        The variables that MailSlurp reads from the content. MailSlurp parses this
        list on the server, so you cannot set it.
        """
        return pulumi.get(self, "variables")

