# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'GetDomainResult',
    'AwaitableGetDomainResult',
    'get_domain',
    'get_domain_output',
]

@pulumi.output_type
class GetDomainResult:
    def __init__(__self__, catch_all_inbox_id=None, created_at=None, dkim_tokens=None, domain=None, domain_id=None, domain_name_records=None, domain_type=None, duplicate_records_message=None, has_duplicate_records=None, has_missing_records=None, is_verified=None, missing_records_message=None, updated_at=None, verification_token=None):
        if catch_all_inbox_id and not isinstance(catch_all_inbox_id, str):
            raise TypeError("Expected argument 'catch_all_inbox_id' to be a str")
        pulumi.set(__self__, "catch_all_inbox_id", catch_all_inbox_id)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if dkim_tokens and not isinstance(dkim_tokens, list):
            raise TypeError("Expected argument 'dkim_tokens' to be a list")
        pulumi.set(__self__, "dkim_tokens", dkim_tokens)
        if domain and not isinstance(domain, str):
            raise TypeError("Expected argument 'domain' to be a str")
        pulumi.set(__self__, "domain", domain)
        if domain_id and not isinstance(domain_id, str):
            raise TypeError("Expected argument 'domain_id' to be a str")
        pulumi.set(__self__, "domain_id", domain_id)
        if domain_name_records and not isinstance(domain_name_records, list):
            raise TypeError("Expected argument 'domain_name_records' to be a list")
        pulumi.set(__self__, "domain_name_records", domain_name_records)
        if domain_type and not isinstance(domain_type, str):
            raise TypeError("Expected argument 'domain_type' to be a str")
        pulumi.set(__self__, "domain_type", domain_type)
        if duplicate_records_message and not isinstance(duplicate_records_message, str):
            raise TypeError("Expected argument 'duplicate_records_message' to be a str")
        pulumi.set(__self__, "duplicate_records_message", duplicate_records_message)
        if has_duplicate_records and not isinstance(has_duplicate_records, bool):
            raise TypeError("Expected argument 'has_duplicate_records' to be a bool")
        pulumi.set(__self__, "has_duplicate_records", has_duplicate_records)
        if has_missing_records and not isinstance(has_missing_records, bool):
            raise TypeError("Expected argument 'has_missing_records' to be a bool")
        pulumi.set(__self__, "has_missing_records", has_missing_records)
        if is_verified and not isinstance(is_verified, bool):
            raise TypeError("Expected argument 'is_verified' to be a bool")
        pulumi.set(__self__, "is_verified", is_verified)
        if missing_records_message and not isinstance(missing_records_message, str):
            raise TypeError("Expected argument 'missing_records_message' to be a str")
        pulumi.set(__self__, "missing_records_message", missing_records_message)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)
        if verification_token and not isinstance(verification_token, str):
            raise TypeError("Expected argument 'verification_token' to be a str")
        pulumi.set(__self__, "verification_token", verification_token)

    @_builtins.property
    @pulumi.getter(name="catchAllInboxId")
    def catch_all_inbox_id(self) -> Optional[_builtins.str]:
        """
        The identifier of the inbox that receives the email of every unmatched
        address.
        """
        return pulumi.get(self, "catch_all_inbox_id")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        """
        The time when MailSlurp created the domain.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="dkimTokens")
    def dkim_tokens(self) -> Sequence[_builtins.str]:
        """
        The DKIM values of the domain. Add one CNAME record for each value.
        """
        return pulumi.get(self, "dkim_tokens")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> _builtins.str:
        """
        The custom domain name.
        """
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter(name="domainId")
    def domain_id(self) -> _builtins.str:
        """
        The identifier of the domain.
        """
        return pulumi.get(self, "domain_id")

    @_builtins.property
    @pulumi.getter(name="domainNameRecords")
    def domain_name_records(self) -> Sequence['outputs.DomainNameRecordResult']:
        """
        The DNS records that the domain needs. Loop over this list to create the
        records with a DNS provider.
        """
        return pulumi.get(self, "domain_name_records")

    @_builtins.property
    @pulumi.getter(name="domainType")
    def domain_type(self) -> 'DomainType':
        """
        The domain type.
        """
        return pulumi.get(self, "domain_type")

    @_builtins.property
    @pulumi.getter(name="duplicateRecordsMessage")
    def duplicate_records_message(self) -> Optional[_builtins.str]:
        """
        The message that names the duplicate DNS records.
        """
        return pulumi.get(self, "duplicate_records_message")

    @_builtins.property
    @pulumi.getter(name="hasDuplicateRecords")
    def has_duplicate_records(self) -> _builtins.bool:
        """
        MailSlurp reports whether the domain has a duplicate DNS record.
        """
        return pulumi.get(self, "has_duplicate_records")

    @_builtins.property
    @pulumi.getter(name="hasMissingRecords")
    def has_missing_records(self) -> _builtins.bool:
        """
        MailSlurp reports whether the domain misses a required DNS record.
        """
        return pulumi.get(self, "has_missing_records")

    @_builtins.property
    @pulumi.getter(name="isVerified")
    def is_verified(self) -> _builtins.bool:
        """
        MailSlurp reports whether the domain passed the DNS checks.
        """
        return pulumi.get(self, "is_verified")

    @_builtins.property
    @pulumi.getter(name="missingRecordsMessage")
    def missing_records_message(self) -> Optional[_builtins.str]:
        """
        The message that names the missing DNS records.
        """
        return pulumi.get(self, "missing_records_message")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> _builtins.str:
        """
        The time when MailSlurp last changed the domain.
        """
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter(name="verificationToken")
    def verification_token(self) -> _builtins.str:
        """
        The value that proves you own the domain. Add it to the DNS records of
        the domain.
        """
        return pulumi.get(self, "verification_token")


class AwaitableGetDomainResult(GetDomainResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDomainResult(
            catch_all_inbox_id=self.catch_all_inbox_id,
            created_at=self.created_at,
            dkim_tokens=self.dkim_tokens,
            domain=self.domain,
            domain_id=self.domain_id,
            domain_name_records=self.domain_name_records,
            domain_type=self.domain_type,
            duplicate_records_message=self.duplicate_records_message,
            has_duplicate_records=self.has_duplicate_records,
            has_missing_records=self.has_missing_records,
            is_verified=self.is_verified,
            missing_records_message=self.missing_records_message,
            updated_at=self.updated_at,
            verification_token=self.verification_token)


def get_domain(check_for_errors: Optional[_builtins.bool] = None,
               domain_id: Optional[_builtins.str] = None,
               opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDomainResult:
    """
    The function reads one MailSlurp custom domain by its identifier. The
    result carries the DNS records that the domain needs, so a stack can
    create them with a DNS provider. The function reads the domain and
    changes nothing.

    :param _builtins.bool check_for_errors: If you set this property, MailSlurp checks the domain for DNS record
           problems. The default is `false`.
    :param _builtins.str domain_id: The identifier of the domain to read. MailSlurp assigns this value when
           it creates the domain.
    """
    __args__ = dict()
    __args__['checkForErrors'] = check_for_errors
    __args__['domainId'] = domain_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('mailslurp:index:getDomain', __args__, opts=opts, typ=GetDomainResult).value

    return AwaitableGetDomainResult(
        catch_all_inbox_id=pulumi.get(__ret__, 'catch_all_inbox_id'),
        created_at=pulumi.get(__ret__, 'created_at'),
        dkim_tokens=pulumi.get(__ret__, 'dkim_tokens'),
        domain=pulumi.get(__ret__, 'domain'),
        domain_id=pulumi.get(__ret__, 'domain_id'),
        domain_name_records=pulumi.get(__ret__, 'domain_name_records'),
        domain_type=pulumi.get(__ret__, 'domain_type'),
        duplicate_records_message=pulumi.get(__ret__, 'duplicate_records_message'),
        has_duplicate_records=pulumi.get(__ret__, 'has_duplicate_records'),
        has_missing_records=pulumi.get(__ret__, 'has_missing_records'),
        is_verified=pulumi.get(__ret__, 'is_verified'),
        missing_records_message=pulumi.get(__ret__, 'missing_records_message'),
        updated_at=pulumi.get(__ret__, 'updated_at'),
        verification_token=pulumi.get(__ret__, 'verification_token'))
def get_domain_output(check_for_errors: pulumi.Input[Optional[Optional[_builtins.bool]]] = None,
                      domain_id: pulumi.Input[Optional[_builtins.str]] = None,
                      opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetDomainResult]:
    """
    The function reads one MailSlurp custom domain by its identifier. The
    result carries the DNS records that the domain needs, so a stack can
    create them with a DNS provider. The function reads the domain and
    changes nothing.

    :param _builtins.bool check_for_errors: If you set this property, MailSlurp checks the domain for DNS record
           problems. The default is `false`.
    :param _builtins.str domain_id: The identifier of the domain to read. MailSlurp assigns this value when
           it creates the domain.
    """
    __args__ = dict()
    __args__['checkForErrors'] = check_for_errors
    __args__['domainId'] = domain_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('mailslurp:index:getDomain', __args__, opts=opts, typ=GetDomainResult)
    return __ret__.apply(lambda __response__: GetDomainResult(
        catch_all_inbox_id=pulumi.get(__response__, 'catch_all_inbox_id'),
        created_at=pulumi.get(__response__, 'created_at'),
        dkim_tokens=pulumi.get(__response__, 'dkim_tokens'),
        domain=pulumi.get(__response__, 'domain'),
        domain_id=pulumi.get(__response__, 'domain_id'),
        domain_name_records=pulumi.get(__response__, 'domain_name_records'),
        domain_type=pulumi.get(__response__, 'domain_type'),
        duplicate_records_message=pulumi.get(__response__, 'duplicate_records_message'),
        has_duplicate_records=pulumi.get(__response__, 'has_duplicate_records'),
        has_missing_records=pulumi.get(__response__, 'has_missing_records'),
        is_verified=pulumi.get(__response__, 'is_verified'),
        missing_records_message=pulumi.get(__response__, 'missing_records_message'),
        updated_at=pulumi.get(__response__, 'updated_at'),
        verification_token=pulumi.get(__response__, 'verification_token')))
