# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = [
    'GetInboxResult',
    'AwaitableGetInboxResult',
    'get_inbox',
    'get_inbox_output',
]

@pulumi.output_type
class GetInboxResult:
    def __init__(__self__, account_region=None, created_at=None, description=None, domain=None, domain_id=None, email_address=None, expires_at=None, favourite=None, functions_as=None, inbox_id=None, inbox_type=None, local_part=None, name=None, read_only=None, tags=None, virtual_inbox=None):
        if account_region and not isinstance(account_region, str):
            raise TypeError("Expected argument 'account_region' to be a str")
        pulumi.set(__self__, "account_region", account_region)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if domain and not isinstance(domain, str):
            raise TypeError("Expected argument 'domain' to be a str")
        pulumi.set(__self__, "domain", domain)
        if domain_id and not isinstance(domain_id, str):
            raise TypeError("Expected argument 'domain_id' to be a str")
        pulumi.set(__self__, "domain_id", domain_id)
        if email_address and not isinstance(email_address, str):
            raise TypeError("Expected argument 'email_address' to be a str")
        pulumi.set(__self__, "email_address", email_address)
        if expires_at and not isinstance(expires_at, str):
            raise TypeError("Expected argument 'expires_at' to be a str")
        pulumi.set(__self__, "expires_at", expires_at)
        if favourite and not isinstance(favourite, bool):
            raise TypeError("Expected argument 'favourite' to be a bool")
        pulumi.set(__self__, "favourite", favourite)
        if functions_as and not isinstance(functions_as, str):
            raise TypeError("Expected argument 'functions_as' to be a str")
        pulumi.set(__self__, "functions_as", functions_as)
        if inbox_id and not isinstance(inbox_id, str):
            raise TypeError("Expected argument 'inbox_id' to be a str")
        pulumi.set(__self__, "inbox_id", inbox_id)
        if inbox_type and not isinstance(inbox_type, str):
            raise TypeError("Expected argument 'inbox_type' to be a str")
        pulumi.set(__self__, "inbox_type", inbox_type)
        if local_part and not isinstance(local_part, str):
            raise TypeError("Expected argument 'local_part' to be a str")
        pulumi.set(__self__, "local_part", local_part)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if read_only and not isinstance(read_only, bool):
            raise TypeError("Expected argument 'read_only' to be a bool")
        pulumi.set(__self__, "read_only", read_only)
        if tags and not isinstance(tags, list):
            raise TypeError("Expected argument 'tags' to be a list")
        pulumi.set(__self__, "tags", tags)
        if virtual_inbox and not isinstance(virtual_inbox, bool):
            raise TypeError("Expected argument 'virtual_inbox' to be a bool")
        pulumi.set(__self__, "virtual_inbox", virtual_inbox)

    @_builtins.property
    @pulumi.getter(name="accountRegion")
    def account_region(self) -> Optional[_builtins.str]:
        """
        The region of the account that holds the inbox.
        """
        return pulumi.get(self, "account_region")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        """
        The time when MailSlurp created the inbox.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[_builtins.str]:
        """
        The free-text description of the inbox.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> Optional[_builtins.str]:
        """
        The domain part of the inbox email address.
        """
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter(name="domainId")
    def domain_id(self) -> Optional[_builtins.str]:
        """
        The identifier of the custom domain that provides the inbox address.
        """
        return pulumi.get(self, "domain_id")

    @_builtins.property
    @pulumi.getter(name="emailAddress")
    def email_address(self) -> _builtins.str:
        """
        The full email address of the inbox.
        """
        return pulumi.get(self, "email_address")

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> Optional[_builtins.str]:
        """
        The time when MailSlurp expires the inbox, in RFC 3339 format.
        """
        return pulumi.get(self, "expires_at")

    @_builtins.property
    @pulumi.getter
    def favourite(self) -> _builtins.bool:
        """
        MailSlurp reports whether the inbox is a favourite in the dashboard.
        """
        return pulumi.get(self, "favourite")

    @_builtins.property
    @pulumi.getter(name="functionsAs")
    def functions_as(self) -> Optional[_builtins.str]:
        """
        The special function of the inbox, for example an alias or a catch-all.
        """
        return pulumi.get(self, "functions_as")

    @_builtins.property
    @pulumi.getter(name="inboxId")
    def inbox_id(self) -> _builtins.str:
        """
        The identifier of the inbox.
        """
        return pulumi.get(self, "inbox_id")

    @_builtins.property
    @pulumi.getter(name="inboxType")
    def inbox_type(self) -> Optional['InboxType']:
        """
        The inbox type.
        """
        return pulumi.get(self, "inbox_type")

    @_builtins.property
    @pulumi.getter(name="localPart")
    def local_part(self) -> Optional[_builtins.str]:
        """
        The local part of the inbox email address.
        """
        return pulumi.get(self, "local_part")

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        """
        The display name of the inbox.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="readOnly")
    def read_only(self) -> _builtins.bool:
        """
        MailSlurp reports whether the inbox is read-only.
        """
        return pulumi.get(self, "read_only")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Sequence[_builtins.str]:
        """
        The tags on the inbox.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="virtualInbox")
    def virtual_inbox(self) -> _builtins.bool:
        """
        MailSlurp reports whether the inbox is virtual. A virtual inbox never sends email to real recipients.
        """
        return pulumi.get(self, "virtual_inbox")


class AwaitableGetInboxResult(GetInboxResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetInboxResult(
            account_region=self.account_region,
            created_at=self.created_at,
            description=self.description,
            domain=self.domain,
            domain_id=self.domain_id,
            email_address=self.email_address,
            expires_at=self.expires_at,
            favourite=self.favourite,
            functions_as=self.functions_as,
            inbox_id=self.inbox_id,
            inbox_type=self.inbox_type,
            local_part=self.local_part,
            name=self.name,
            read_only=self.read_only,
            tags=self.tags,
            virtual_inbox=self.virtual_inbox)


def get_inbox(inbox_id: Optional[_builtins.str] = None,
              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetInboxResult:
    """
    The function reads one MailSlurp inbox by its identifier. Use it when a
    stack must reference an inbox that Pulumi does not manage. The function
    reads the inbox and changes nothing.

    :param _builtins.str inbox_id: The identifier of the inbox to read. MailSlurp assigns this value when
           it creates the inbox.
    """
    __args__ = dict()
    __args__['inboxId'] = inbox_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('mailslurp:index:getInbox', __args__, opts=opts, typ=GetInboxResult).value

    return AwaitableGetInboxResult(
        account_region=pulumi.get(__ret__, 'account_region'),
        created_at=pulumi.get(__ret__, 'created_at'),
        description=pulumi.get(__ret__, 'description'),
        domain=pulumi.get(__ret__, 'domain'),
        domain_id=pulumi.get(__ret__, 'domain_id'),
        email_address=pulumi.get(__ret__, 'email_address'),
        expires_at=pulumi.get(__ret__, 'expires_at'),
        favourite=pulumi.get(__ret__, 'favourite'),
        functions_as=pulumi.get(__ret__, 'functions_as'),
        inbox_id=pulumi.get(__ret__, 'inbox_id'),
        inbox_type=pulumi.get(__ret__, 'inbox_type'),
        local_part=pulumi.get(__ret__, 'local_part'),
        name=pulumi.get(__ret__, 'name'),
        read_only=pulumi.get(__ret__, 'read_only'),
        tags=pulumi.get(__ret__, 'tags'),
        virtual_inbox=pulumi.get(__ret__, 'virtual_inbox'))
def get_inbox_output(inbox_id: pulumi.Input[Optional[_builtins.str]] = None,
                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetInboxResult]:
    """
    The function reads one MailSlurp inbox by its identifier. Use it when a
    stack must reference an inbox that Pulumi does not manage. The function
    reads the inbox and changes nothing.

    :param _builtins.str inbox_id: The identifier of the inbox to read. MailSlurp assigns this value when
           it creates the inbox.
    """
    __args__ = dict()
    __args__['inboxId'] = inbox_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('mailslurp:index:getInbox', __args__, opts=opts, typ=GetInboxResult)
    return __ret__.apply(lambda __response__: GetInboxResult(
        account_region=pulumi.get(__response__, 'account_region'),
        created_at=pulumi.get(__response__, 'created_at'),
        description=pulumi.get(__response__, 'description'),
        domain=pulumi.get(__response__, 'domain'),
        domain_id=pulumi.get(__response__, 'domain_id'),
        email_address=pulumi.get(__response__, 'email_address'),
        expires_at=pulumi.get(__response__, 'expires_at'),
        favourite=pulumi.get(__response__, 'favourite'),
        functions_as=pulumi.get(__response__, 'functions_as'),
        inbox_id=pulumi.get(__response__, 'inbox_id'),
        inbox_type=pulumi.get(__response__, 'inbox_type'),
        local_part=pulumi.get(__response__, 'local_part'),
        name=pulumi.get(__response__, 'name'),
        read_only=pulumi.get(__response__, 'read_only'),
        tags=pulumi.get(__response__, 'tags'),
        virtual_inbox=pulumi.get(__response__, 'virtual_inbox')))
