# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = ['InboxArgs', 'Inbox']

@pulumi.input_type
class InboxArgs:
    def __init__(__self__, *,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 domain_id: pulumi.Input[Optional[_builtins.str]] = None,
                 domain_name: pulumi.Input[Optional[_builtins.str]] = None,
                 email_address: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_at: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_in: pulumi.Input[Optional[_builtins.int]] = None,
                 favourite: pulumi.Input[Optional[_builtins.bool]] = None,
                 inbox_type: pulumi.Input[Optional['InboxType']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 prefix: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 use_domain_pool: pulumi.Input[Optional[_builtins.bool]] = None,
                 use_short_address: pulumi.Input[Optional[_builtins.bool]] = None,
                 virtual_inbox: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a Inbox resource.

        :param pulumi.Input[_builtins.str] description: A free-text description of the inbox. You can update this property in
               place. The API cannot clear this property after you set it.
        :param pulumi.Input[_builtins.str] domain_id: The identifier of a verified custom domain that provides the inbox
               address. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.str] domain_name: The custom domain that provides the inbox address. The domain must be
               verified in your MailSlurp account. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.str] email_address: The full email address of the inbox. When you do not set this
               property, MailSlurp assigns an address. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.str] expires_at: The time when MailSlurp expires the inbox, in RFC 3339 format. You can
               update this property in place. The API cannot clear this property after
               you set it.
        :param pulumi.Input[_builtins.int] expires_in: The lifetime of the inbox in milliseconds. The API does not echo this
               property, so Pulumi keeps it in the state and does not diff it against
               the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.bool] favourite: If you set this property, MailSlurp marks the inbox as a favourite in
               the dashboard. You can update this property in place.
        :param pulumi.Input['InboxType'] inbox_type: The inbox type: `HTTP_INBOX` or `SMTP_INBOX`. A refresh keeps the
               prior value when the API does not report a type. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.str] name: The display name of the inbox. You can update this property in place.
               The API cannot clear this property after you set it.
        :param pulumi.Input[_builtins.str] prefix: A prefix for the local part of the assigned email address. The API
               does not echo this property, so Pulumi keeps it in the state and does
               not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: The tags on the inbox. Use tags to group and find inboxes. You can
               update this property in place. Set an empty list to clear the tags.
        :param pulumi.Input[_builtins.bool] use_domain_pool: If you set this property, MailSlurp assigns the address from the shared
               domain pool. The API does not echo this property, so Pulumi keeps it in
               the state and does not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.bool] use_short_address: If you set this property, MailSlurp assigns a short email address to the
               inbox. The API does not echo this property, so Pulumi keeps it in the
               state and does not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.bool] virtual_inbox: If you set this property, MailSlurp creates a virtual inbox. A virtual
               inbox receives email but never sends it to real recipients. Use it for
               safe tests. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if domain_id is not None:
            pulumi.set(__self__, "domain_id", domain_id)
        if domain_name is not None:
            pulumi.set(__self__, "domain_name", domain_name)
        if email_address is not None:
            pulumi.set(__self__, "email_address", email_address)
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if expires_in is not None:
            pulumi.set(__self__, "expires_in", expires_in)
        if favourite is not None:
            pulumi.set(__self__, "favourite", favourite)
        if inbox_type is not None:
            pulumi.set(__self__, "inbox_type", inbox_type)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if prefix is not None:
            pulumi.set(__self__, "prefix", prefix)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if use_domain_pool is not None:
            pulumi.set(__self__, "use_domain_pool", use_domain_pool)
        if use_short_address is not None:
            pulumi.set(__self__, "use_short_address", use_short_address)
        if virtual_inbox is not None:
            pulumi.set(__self__, "virtual_inbox", virtual_inbox)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A free-text description of the inbox. You can update this property in
        place. The API cannot clear this property after you set it.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="domainId")
    def domain_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The identifier of a verified custom domain that provides the inbox
        address. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        """
        return pulumi.get(self, "domain_id")

    @domain_id.setter
    def domain_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "domain_id", value)

    @_builtins.property
    @pulumi.getter(name="domainName")
    def domain_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The custom domain that provides the inbox address. The domain must be
        verified in your MailSlurp account. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        """
        return pulumi.get(self, "domain_name")

    @domain_name.setter
    def domain_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "domain_name", value)

    @_builtins.property
    @pulumi.getter(name="emailAddress")
    def email_address(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The full email address of the inbox. When you do not set this
        property, MailSlurp assigns an address. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        """
        return pulumi.get(self, "email_address")

    @email_address.setter
    def email_address(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "email_address", value)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The time when MailSlurp expires the inbox, in RFC 3339 format. You can
        update this property in place. The API cannot clear this property after
        you set it.
        """
        return pulumi.get(self, "expires_at")

    @expires_at.setter
    def expires_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "expires_at", value)

    @_builtins.property
    @pulumi.getter(name="expiresIn")
    def expires_in(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The lifetime of the inbox in milliseconds. The API does not echo this
        property, so Pulumi keeps it in the state and does not diff it against
        the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        """
        return pulumi.get(self, "expires_in")

    @expires_in.setter
    def expires_in(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "expires_in", value)

    @_builtins.property
    @pulumi.getter
    def favourite(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        If you set this property, MailSlurp marks the inbox as a favourite in
        the dashboard. You can update this property in place.
        """
        return pulumi.get(self, "favourite")

    @favourite.setter
    def favourite(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "favourite", value)

    @_builtins.property
    @pulumi.getter(name="inboxType")
    def inbox_type(self) -> pulumi.Input[Optional['InboxType']]:
        """
        The inbox type: `HTTP_INBOX` or `SMTP_INBOX`. A refresh keeps the
        prior value when the API does not report a type. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        """
        return pulumi.get(self, "inbox_type")

    @inbox_type.setter
    def inbox_type(self, value: pulumi.Input[Optional['InboxType']]):
        pulumi.set(self, "inbox_type", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The display name of the inbox. You can update this property in place.
        The API cannot clear this property after you set it.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A prefix for the local part of the assigned email address. The API
        does not echo this property, so Pulumi keeps it in the state and does
        not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        """
        return pulumi.get(self, "prefix")

    @prefix.setter
    def prefix(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "prefix", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The tags on the inbox. Use tags to group and find inboxes. You can
        update this property in place. Set an empty list to clear the tags.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="useDomainPool")
    def use_domain_pool(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        If you set this property, MailSlurp assigns the address from the shared
        domain pool. The API does not echo this property, so Pulumi keeps it in
        the state and does not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        """
        return pulumi.get(self, "use_domain_pool")

    @use_domain_pool.setter
    def use_domain_pool(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "use_domain_pool", value)

    @_builtins.property
    @pulumi.getter(name="useShortAddress")
    def use_short_address(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        If you set this property, MailSlurp assigns a short email address to the
        inbox. The API does not echo this property, so Pulumi keeps it in the
        state and does not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        """
        return pulumi.get(self, "use_short_address")

    @use_short_address.setter
    def use_short_address(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "use_short_address", value)

    @_builtins.property
    @pulumi.getter(name="virtualInbox")
    def virtual_inbox(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        If you set this property, MailSlurp creates a virtual inbox. A virtual
        inbox receives email but never sends it to real recipients. Use it for
        safe tests. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        """
        return pulumi.get(self, "virtual_inbox")

    @virtual_inbox.setter
    def virtual_inbox(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "virtual_inbox", value)


@pulumi.type_token("mailslurp:index:Inbox")
class Inbox(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 domain_id: pulumi.Input[Optional[_builtins.str]] = None,
                 domain_name: pulumi.Input[Optional[_builtins.str]] = None,
                 email_address: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_at: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_in: pulumi.Input[Optional[_builtins.int]] = None,
                 favourite: pulumi.Input[Optional[_builtins.bool]] = None,
                 inbox_type: pulumi.Input[Optional['InboxType']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 prefix: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 use_domain_pool: pulumi.Input[Optional[_builtins.bool]] = None,
                 use_short_address: pulumi.Input[Optional[_builtins.bool]] = None,
                 virtual_inbox: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        An email inbox on MailSlurp. The inbox has an email address that can
        send and receive email.

        You can update the `name`, `description`, `tags`, `expiresAt`, and
        `favourite` properties in place. If you change any other property,
        Pulumi replaces the inbox. Each replacement creates a new inbox, which
        counts against the 30-day inbox creation quota of your MailSlurp
        account. MailSlurp bills each creation on paid plans. If you remove a
        property that forces a replacement, Pulumi keeps the inbox.

        ## Example Usage
        ### An inbox that receives email at an address MailSlurp assigns
        ```python
        import pulumi
        import pulumi_mailslurp as mailslurp

        team_inbox = mailslurp.Inbox("team-inbox",
            description="The shared inbox of the team",
            inbox_type=mailslurp.InboxType.HTTP_INBOX,
            name="team-inbox",
            tags=[
                "pulumi",
                "team",
            ])
        pulumi.export("emailAddress", team_inbox.email_address)
        ```
        ### A virtual inbox that holds every test email inside MailSlurp
        ```python
        import pulumi
        import pulumi_mailslurp as mailslurp

        test_inbox = mailslurp.Inbox("test-inbox",
            description="The inbox that the acceptance tests read",
            expires_in=3600000,
            name="test-inbox",
            tags=["test"],
            virtual_inbox=True)
        pulumi.export("emailAddress", test_inbox.email_address)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: A free-text description of the inbox. You can update this property in
               place. The API cannot clear this property after you set it.
        :param pulumi.Input[_builtins.str] domain_id: The identifier of a verified custom domain that provides the inbox
               address. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.str] domain_name: The custom domain that provides the inbox address. The domain must be
               verified in your MailSlurp account. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.str] email_address: The full email address of the inbox. When you do not set this
               property, MailSlurp assigns an address. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.str] expires_at: The time when MailSlurp expires the inbox, in RFC 3339 format. You can
               update this property in place. The API cannot clear this property after
               you set it.
        :param pulumi.Input[_builtins.int] expires_in: The lifetime of the inbox in milliseconds. The API does not echo this
               property, so Pulumi keeps it in the state and does not diff it against
               the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.bool] favourite: If you set this property, MailSlurp marks the inbox as a favourite in
               the dashboard. You can update this property in place.
        :param pulumi.Input['InboxType'] inbox_type: The inbox type: `HTTP_INBOX` or `SMTP_INBOX`. A refresh keeps the
               prior value when the API does not report a type. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.str] name: The display name of the inbox. You can update this property in place.
               The API cannot clear this property after you set it.
        :param pulumi.Input[_builtins.str] prefix: A prefix for the local part of the assigned email address. The API
               does not echo this property, so Pulumi keeps it in the state and does
               not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: The tags on the inbox. Use tags to group and find inboxes. You can
               update this property in place. Set an empty list to clear the tags.
        :param pulumi.Input[_builtins.bool] use_domain_pool: If you set this property, MailSlurp assigns the address from the shared
               domain pool. The API does not echo this property, so Pulumi keeps it in
               the state and does not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.bool] use_short_address: If you set this property, MailSlurp assigns a short email address to the
               inbox. The API does not echo this property, so Pulumi keeps it in the
               state and does not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        :param pulumi.Input[_builtins.bool] virtual_inbox: If you set this property, MailSlurp creates a virtual inbox. A virtual
               inbox receives email but never sends it to real recipients. Use it for
               safe tests. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[InboxArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        An email inbox on MailSlurp. The inbox has an email address that can
        send and receive email.

        You can update the `name`, `description`, `tags`, `expiresAt`, and
        `favourite` properties in place. If you change any other property,
        Pulumi replaces the inbox. Each replacement creates a new inbox, which
        counts against the 30-day inbox creation quota of your MailSlurp
        account. MailSlurp bills each creation on paid plans. If you remove a
        property that forces a replacement, Pulumi keeps the inbox.

        ## Example Usage
        ### An inbox that receives email at an address MailSlurp assigns
        ```python
        import pulumi
        import pulumi_mailslurp as mailslurp

        team_inbox = mailslurp.Inbox("team-inbox",
            description="The shared inbox of the team",
            inbox_type=mailslurp.InboxType.HTTP_INBOX,
            name="team-inbox",
            tags=[
                "pulumi",
                "team",
            ])
        pulumi.export("emailAddress", team_inbox.email_address)
        ```
        ### A virtual inbox that holds every test email inside MailSlurp
        ```python
        import pulumi
        import pulumi_mailslurp as mailslurp

        test_inbox = mailslurp.Inbox("test-inbox",
            description="The inbox that the acceptance tests read",
            expires_in=3600000,
            name="test-inbox",
            tags=["test"],
            virtual_inbox=True)
        pulumi.export("emailAddress", test_inbox.email_address)
        ```


        :param str resource_name: The name of the resource.
        :param InboxArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(InboxArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 domain_id: pulumi.Input[Optional[_builtins.str]] = None,
                 domain_name: pulumi.Input[Optional[_builtins.str]] = None,
                 email_address: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_at: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_in: pulumi.Input[Optional[_builtins.int]] = None,
                 favourite: pulumi.Input[Optional[_builtins.bool]] = None,
                 inbox_type: pulumi.Input[Optional['InboxType']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 prefix: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 use_domain_pool: pulumi.Input[Optional[_builtins.bool]] = None,
                 use_short_address: pulumi.Input[Optional[_builtins.bool]] = None,
                 virtual_inbox: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = InboxArgs.__new__(InboxArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["domain_id"] = domain_id
            __props__.__dict__["domain_name"] = domain_name
            __props__.__dict__["email_address"] = email_address
            __props__.__dict__["expires_at"] = expires_at
            __props__.__dict__["expires_in"] = expires_in
            __props__.__dict__["favourite"] = favourite
            __props__.__dict__["inbox_type"] = inbox_type
            __props__.__dict__["name"] = name
            __props__.__dict__["prefix"] = prefix
            __props__.__dict__["tags"] = tags
            __props__.__dict__["use_domain_pool"] = use_domain_pool
            __props__.__dict__["use_short_address"] = use_short_address
            __props__.__dict__["virtual_inbox"] = virtual_inbox
            __props__.__dict__["account_region"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["domain"] = None
            __props__.__dict__["functions_as"] = None
            __props__.__dict__["local_part"] = None
            __props__.__dict__["read_only"] = None
        super(Inbox, __self__).__init__(
            'mailslurp:index:Inbox',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Inbox':
        """
        Get an existing Inbox resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = InboxArgs.__new__(InboxArgs)

        __props__.__dict__["account_region"] = None
        __props__.__dict__["created_at"] = None
        __props__.__dict__["description"] = None
        __props__.__dict__["domain"] = None
        __props__.__dict__["domain_id"] = None
        __props__.__dict__["domain_name"] = None
        __props__.__dict__["email_address"] = None
        __props__.__dict__["expires_at"] = None
        __props__.__dict__["expires_in"] = None
        __props__.__dict__["favourite"] = None
        __props__.__dict__["functions_as"] = None
        __props__.__dict__["inbox_type"] = None
        __props__.__dict__["local_part"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["prefix"] = None
        __props__.__dict__["read_only"] = None
        __props__.__dict__["tags"] = None
        __props__.__dict__["use_domain_pool"] = None
        __props__.__dict__["use_short_address"] = None
        __props__.__dict__["virtual_inbox"] = None
        return Inbox(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accountRegion")
    def account_region(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The region of the account that holds the inbox.
        """
        return pulumi.get(self, "account_region")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        The time when MailSlurp created the inbox.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The free-text description of the inbox.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The domain part of the inbox email address.
        """
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter(name="domainId")
    def domain_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The identifier of the custom domain that provides the inbox address.
        """
        return pulumi.get(self, "domain_id")

    @_builtins.property
    @pulumi.getter(name="domainName")
    def domain_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The custom domain that provides the inbox address.
        """
        return pulumi.get(self, "domain_name")

    @_builtins.property
    @pulumi.getter(name="emailAddress")
    def email_address(self) -> pulumi.Output[_builtins.str]:
        """
        The full email address of the inbox.
        """
        return pulumi.get(self, "email_address")

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The time when MailSlurp expires the inbox, in RFC 3339 format.
        """
        return pulumi.get(self, "expires_at")

    @_builtins.property
    @pulumi.getter(name="expiresIn")
    def expires_in(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The lifetime of the inbox in milliseconds. The API does not echo this property.
        """
        return pulumi.get(self, "expires_in")

    @_builtins.property
    @pulumi.getter
    def favourite(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        MailSlurp reports whether the inbox is a favourite in the dashboard.
        """
        return pulumi.get(self, "favourite")

    @_builtins.property
    @pulumi.getter(name="functionsAs")
    def functions_as(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The special function of the inbox, for example an alias or a catch-all.
        """
        return pulumi.get(self, "functions_as")

    @_builtins.property
    @pulumi.getter(name="inboxType")
    def inbox_type(self) -> pulumi.Output[Optional['InboxType']]:
        """
        The inbox type.
        """
        return pulumi.get(self, "inbox_type")

    @_builtins.property
    @pulumi.getter(name="localPart")
    def local_part(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The local part of the inbox email address.
        """
        return pulumi.get(self, "local_part")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The display name of the inbox.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The prefix for the local part of the assigned email address. The API does not echo this property.
        """
        return pulumi.get(self, "prefix")

    @_builtins.property
    @pulumi.getter(name="readOnly")
    def read_only(self) -> pulumi.Output[_builtins.bool]:
        """
        MailSlurp reports whether the inbox is read-only.
        """
        return pulumi.get(self, "read_only")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        The tags on the inbox.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="useDomainPool")
    def use_domain_pool(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        The shared MailSlurp domain pool value of the inbox. The API does not echo this property.
        """
        return pulumi.get(self, "use_domain_pool")

    @_builtins.property
    @pulumi.getter(name="useShortAddress")
    def use_short_address(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        The short address value of the inbox. The API does not echo this property.
        """
        return pulumi.get(self, "use_short_address")

    @_builtins.property
    @pulumi.getter(name="virtualInbox")
    def virtual_inbox(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        MailSlurp reports whether the inbox is virtual. A virtual inbox never sends email to real recipients.
        """
        return pulumi.get(self, "virtual_inbox")

