# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._enums import *
from ._inputs import *

__all__ = ['InboxForwarderArgs', 'InboxForwarder']

@pulumi.input_type
class InboxForwarderArgs:
    def __init__(__self__, *,
                 forward_to_recipients: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 inbox_id: pulumi.Input[_builtins.str],
                 field: pulumi.Input[Optional['ForwarderField']] = None,
                 match: pulumi.Input[Optional[_builtins.str]] = None,
                 match_options: pulumi.Input[Optional['InboxForwarderMatchGroupArgs']] = None,
                 should: pulumi.Input[Optional['ForwarderShould']] = None):
        """
        The set of arguments for constructing a InboxForwarder resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] forward_to_recipients: The addresses that MailSlurp sends the matching email to. The API
               requires this property on every write. You can update this property in
               place.
        :param pulumi.Input[_builtins.str] inbox_id: The inbox that the forwarder reads. MailSlurp compares each email that
               this inbox receives. **Warning:** If you change this property, Pulumi
               replaces the forwarder. The new forwarder carries a new identifier.
        :param pulumi.Input['ForwarderField'] field: The part of the email that MailSlurp compares against the `match` value.
               You can update this property in place.
        :param pulumi.Input[_builtins.str] match: The value or the pattern that MailSlurp compares. Use `*@example.com` to
               match every address of a domain. You can update this property in place.
        :param pulumi.Input['InboxForwarderMatchGroupArgs'] match_options: A tree of match rules that MailSlurp applies to each email. The
               `operator` property joins the rules of one group. You can put a group
               inside the `groups` property. You can update this property in place.
        :param pulumi.Input['ForwarderShould'] should: The way that MailSlurp compares the `match` value. Use `WILDCARD` for a
               pattern that holds a star. Use `EQUAL` for one exact value. You can
               update this property in place.
        """
        pulumi.set(__self__, "forward_to_recipients", forward_to_recipients)
        pulumi.set(__self__, "inbox_id", inbox_id)
        if field is not None:
            pulumi.set(__self__, "field", field)
        if match is not None:
            pulumi.set(__self__, "match", match)
        if match_options is not None:
            pulumi.set(__self__, "match_options", match_options)
        if should is not None:
            pulumi.set(__self__, "should", should)

    @_builtins.property
    @pulumi.getter(name="forwardToRecipients")
    def forward_to_recipients(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        The addresses that MailSlurp sends the matching email to. The API
        requires this property on every write. You can update this property in
        place.
        """
        return pulumi.get(self, "forward_to_recipients")

    @forward_to_recipients.setter
    def forward_to_recipients(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "forward_to_recipients", value)

    @_builtins.property
    @pulumi.getter(name="inboxId")
    def inbox_id(self) -> pulumi.Input[_builtins.str]:
        """
        The inbox that the forwarder reads. MailSlurp compares each email that
        this inbox receives. **Warning:** If you change this property, Pulumi
        replaces the forwarder. The new forwarder carries a new identifier.
        """
        return pulumi.get(self, "inbox_id")

    @inbox_id.setter
    def inbox_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "inbox_id", value)

    @_builtins.property
    @pulumi.getter
    def field(self) -> pulumi.Input[Optional['ForwarderField']]:
        """
        The part of the email that MailSlurp compares against the `match` value.
        You can update this property in place.
        """
        return pulumi.get(self, "field")

    @field.setter
    def field(self, value: pulumi.Input[Optional['ForwarderField']]):
        pulumi.set(self, "field", value)

    @_builtins.property
    @pulumi.getter
    def match(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The value or the pattern that MailSlurp compares. Use `*@example.com` to
        match every address of a domain. You can update this property in place.
        """
        return pulumi.get(self, "match")

    @match.setter
    def match(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "match", value)

    @_builtins.property
    @pulumi.getter(name="matchOptions")
    def match_options(self) -> pulumi.Input[Optional['InboxForwarderMatchGroupArgs']]:
        """
        A tree of match rules that MailSlurp applies to each email. The
        `operator` property joins the rules of one group. You can put a group
        inside the `groups` property. You can update this property in place.
        """
        return pulumi.get(self, "match_options")

    @match_options.setter
    def match_options(self, value: pulumi.Input[Optional['InboxForwarderMatchGroupArgs']]):
        pulumi.set(self, "match_options", value)

    @_builtins.property
    @pulumi.getter
    def should(self) -> pulumi.Input[Optional['ForwarderShould']]:
        """
        The way that MailSlurp compares the `match` value. Use `WILDCARD` for a
        pattern that holds a star. Use `EQUAL` for one exact value. You can
        update this property in place.
        """
        return pulumi.get(self, "should")

    @should.setter
    def should(self, value: pulumi.Input[Optional['ForwarderShould']]):
        pulumi.set(self, "should", value)


@pulumi.type_token("mailslurp:index:InboxForwarder")
class InboxForwarder(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 field: pulumi.Input[Optional['ForwarderField']] = None,
                 forward_to_recipients: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 inbox_id: pulumi.Input[Optional[_builtins.str]] = None,
                 match: pulumi.Input[Optional[_builtins.str]] = None,
                 match_options: pulumi.Input[Optional[Union['InboxForwarderMatchGroupArgs', 'InboxForwarderMatchGroupArgsDict']]] = None,
                 should: pulumi.Input[Optional['ForwarderShould']] = None,
                 __props__=None):
        """
        An inbox forwarder that sends a copy of a matching email to other
        addresses. MailSlurp reads each email that the inbox receives, and
        forwards the email when the rule matches.

        You can update the `field`, the `should`, the `match`, the `matchOptions`
        and the `forwardToRecipients` properties in place. Pulumi replaces the
        forwarder when you change the `inboxId` property, because the API takes
        the inbox on the create call alone.

        The API requires the `field` and the `match` properties, or the
        `matchOptions` property. A write that names none of them fails. Each
        update sends the whole create body, so a value that you set outside
        Pulumi can go away.

        MailSlurp writes the `name` of the forwarder. The create call takes no
        name, so you cannot set it. This resource does not carry the
        `attachmentTextExtractionMethod` property of the API.

        ## Example Usage
        ### A forwarder that sends every invoice email to the billing address
        ```python
        import pulumi
        import pulumi_mailslurp as mailslurp

        billing_inbox = mailslurp.Inbox("billing-inbox", name="billing-inbox")
        invoice_forwarder = mailslurp.InboxForwarder("invoice-forwarder",
            field=mailslurp.ForwarderField.SUBJECT,
            forward_to_recipients=["billing@example.com"],
            inbox_id=billing_inbox.id,
            match="invoice",
            should=mailslurp.ForwarderShould.CONTAIN)
        pulumi.export("forwarderId", invoice_forwarder.id)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input['ForwarderField'] field: The part of the email that MailSlurp compares against the `match` value.
               You can update this property in place.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] forward_to_recipients: The addresses that MailSlurp sends the matching email to. The API
               requires this property on every write. You can update this property in
               place.
        :param pulumi.Input[_builtins.str] inbox_id: The inbox that the forwarder reads. MailSlurp compares each email that
               this inbox receives. **Warning:** If you change this property, Pulumi
               replaces the forwarder. The new forwarder carries a new identifier.
        :param pulumi.Input[_builtins.str] match: The value or the pattern that MailSlurp compares. Use `*@example.com` to
               match every address of a domain. You can update this property in place.
        :param pulumi.Input[Union['InboxForwarderMatchGroupArgs', 'InboxForwarderMatchGroupArgsDict']] match_options: A tree of match rules that MailSlurp applies to each email. The
               `operator` property joins the rules of one group. You can put a group
               inside the `groups` property. You can update this property in place.
        :param pulumi.Input['ForwarderShould'] should: The way that MailSlurp compares the `match` value. Use `WILDCARD` for a
               pattern that holds a star. Use `EQUAL` for one exact value. You can
               update this property in place.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: InboxForwarderArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        An inbox forwarder that sends a copy of a matching email to other
        addresses. MailSlurp reads each email that the inbox receives, and
        forwards the email when the rule matches.

        You can update the `field`, the `should`, the `match`, the `matchOptions`
        and the `forwardToRecipients` properties in place. Pulumi replaces the
        forwarder when you change the `inboxId` property, because the API takes
        the inbox on the create call alone.

        The API requires the `field` and the `match` properties, or the
        `matchOptions` property. A write that names none of them fails. Each
        update sends the whole create body, so a value that you set outside
        Pulumi can go away.

        MailSlurp writes the `name` of the forwarder. The create call takes no
        name, so you cannot set it. This resource does not carry the
        `attachmentTextExtractionMethod` property of the API.

        ## Example Usage
        ### A forwarder that sends every invoice email to the billing address
        ```python
        import pulumi
        import pulumi_mailslurp as mailslurp

        billing_inbox = mailslurp.Inbox("billing-inbox", name="billing-inbox")
        invoice_forwarder = mailslurp.InboxForwarder("invoice-forwarder",
            field=mailslurp.ForwarderField.SUBJECT,
            forward_to_recipients=["billing@example.com"],
            inbox_id=billing_inbox.id,
            match="invoice",
            should=mailslurp.ForwarderShould.CONTAIN)
        pulumi.export("forwarderId", invoice_forwarder.id)
        ```


        :param str resource_name: The name of the resource.
        :param InboxForwarderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(InboxForwarderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 field: pulumi.Input[Optional['ForwarderField']] = None,
                 forward_to_recipients: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 inbox_id: pulumi.Input[Optional[_builtins.str]] = None,
                 match: pulumi.Input[Optional[_builtins.str]] = None,
                 match_options: pulumi.Input[Optional[Union['InboxForwarderMatchGroupArgs', 'InboxForwarderMatchGroupArgsDict']]] = None,
                 should: pulumi.Input[Optional['ForwarderShould']] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = InboxForwarderArgs.__new__(InboxForwarderArgs)

            __props__.__dict__["field"] = field
            if forward_to_recipients is None and not opts.urn:
                raise TypeError("Missing required property 'forward_to_recipients'")
            __props__.__dict__["forward_to_recipients"] = forward_to_recipients
            if inbox_id is None and not opts.urn:
                raise TypeError("Missing required property 'inbox_id'")
            __props__.__dict__["inbox_id"] = inbox_id
            __props__.__dict__["match"] = match
            __props__.__dict__["match_options"] = match_options
            __props__.__dict__["should"] = should
            __props__.__dict__["created_at"] = None
            __props__.__dict__["name"] = None
        super(InboxForwarder, __self__).__init__(
            'mailslurp:index:InboxForwarder',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'InboxForwarder':
        """
        Get an existing InboxForwarder resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = InboxForwarderArgs.__new__(InboxForwarderArgs)

        __props__.__dict__["created_at"] = None
        __props__.__dict__["field"] = None
        __props__.__dict__["forward_to_recipients"] = None
        __props__.__dict__["inbox_id"] = None
        __props__.__dict__["match"] = None
        __props__.__dict__["match_options"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["should"] = None
        return InboxForwarder(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        The time when MailSlurp created the forwarder.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def field(self) -> pulumi.Output[Optional['ForwarderField']]:
        """
        The part of the email that MailSlurp compares.
        """
        return pulumi.get(self, "field")

    @_builtins.property
    @pulumi.getter(name="forwardToRecipients")
    def forward_to_recipients(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        The addresses that MailSlurp sends the matching email to.
        """
        return pulumi.get(self, "forward_to_recipients")

    @_builtins.property
    @pulumi.getter(name="inboxId")
    def inbox_id(self) -> pulumi.Output[_builtins.str]:
        """
        The inbox that the forwarder reads.
        """
        return pulumi.get(self, "inbox_id")

    @_builtins.property
    @pulumi.getter
    def match(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The value or the pattern that MailSlurp compares.
        """
        return pulumi.get(self, "match")

    @_builtins.property
    @pulumi.getter(name="matchOptions")
    def match_options(self) -> pulumi.Output[Optional['outputs.InboxForwarderMatchGroup']]:
        """
        The tree of match rules that MailSlurp applies to each email.
        """
        return pulumi.get(self, "match_options")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The display name of the forwarder. MailSlurp writes it, and the create
        call takes no name, so you cannot set it.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def should(self) -> pulumi.Output[Optional['ForwarderShould']]:
        """
        The way that MailSlurp compares the `match` value.
        """
        return pulumi.get(self, "should")

