# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = ['InboxRulesetArgs', 'InboxRuleset']

@pulumi.input_type
class InboxRulesetArgs:
    def __init__(__self__, *,
                 action: pulumi.Input['RulesetAction'],
                 inbox_id: pulumi.Input[_builtins.str],
                 scope: pulumi.Input['RulesetScope'],
                 target: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a InboxRuleset resource.

        :param pulumi.Input['RulesetAction'] action: The action that MailSlurp takes when the target matches. The `ALLOW`
               action wins over the `BLOCK` action. The `FILTER_REMOVE` action removes
               the matched address and keeps the rest of the email. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        :param pulumi.Input[_builtins.str] inbox_id: The inbox that the ruleset applies to. MailSlurp matches the email of the
               inbox against the target. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        :param pulumi.Input['RulesetScope'] scope: The activity that the ruleset applies to. Use `RECEIVING_EMAILS` for the
               email the inbox receives. Use `SENDING_EMAILS` for the email the inbox
               sends. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        :param pulumi.Input[_builtins.str] target: The email address or the pattern that MailSlurp matches. Use
               `*@example.com` to match every address of a domain. Use one full address
               to match that address alone. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        """
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "inbox_id", inbox_id)
        pulumi.set(__self__, "scope", scope)
        pulumi.set(__self__, "target", target)

    @_builtins.property
    @pulumi.getter
    def action(self) -> pulumi.Input['RulesetAction']:
        """
        The action that MailSlurp takes when the target matches. The `ALLOW`
        action wins over the `BLOCK` action. The `FILTER_REMOVE` action removes
        the matched address and keeps the rest of the email. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: pulumi.Input['RulesetAction']):
        pulumi.set(self, "action", value)

    @_builtins.property
    @pulumi.getter(name="inboxId")
    def inbox_id(self) -> pulumi.Input[_builtins.str]:
        """
        The inbox that the ruleset applies to. MailSlurp matches the email of the
        inbox against the target. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        """
        return pulumi.get(self, "inbox_id")

    @inbox_id.setter
    def inbox_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "inbox_id", value)

    @_builtins.property
    @pulumi.getter
    def scope(self) -> pulumi.Input['RulesetScope']:
        """
        The activity that the ruleset applies to. Use `RECEIVING_EMAILS` for the
        email the inbox receives. Use `SENDING_EMAILS` for the email the inbox
        sends. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        """
        return pulumi.get(self, "scope")

    @scope.setter
    def scope(self, value: pulumi.Input['RulesetScope']):
        pulumi.set(self, "scope", value)

    @_builtins.property
    @pulumi.getter
    def target(self) -> pulumi.Input[_builtins.str]:
        """
        The email address or the pattern that MailSlurp matches. Use
        `*@example.com` to match every address of a domain. Use one full address
        to match that address alone. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        """
        return pulumi.get(self, "target")

    @target.setter
    def target(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "target", value)


@pulumi.type_token("mailslurp:index:InboxRuleset")
class InboxRuleset(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action: pulumi.Input[Optional['RulesetAction']] = None,
                 inbox_id: pulumi.Input[Optional[_builtins.str]] = None,
                 scope: pulumi.Input[Optional['RulesetScope']] = None,
                 target: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        An inbox ruleset that blocks or allows email for one inbox. MailSlurp
        applies the ruleset when the inbox sends or receives email.

        You cannot update a ruleset. The API offers no update call, so Pulumi
        replaces the ruleset when you change any property. Pulumi creates the new
        ruleset, and then it deletes the old one. A ruleset is free, and it never
        counts against the inbox creation quota.

        ## Example Usage
        ### A ruleset that blocks the email of one domain
        ```python
        import pulumi
        import pulumi_mailslurp as mailslurp

        support_inbox = mailslurp.Inbox("support-inbox", name="support-inbox")
        block_one_domain = mailslurp.InboxRuleset("block-one-domain",
            action=mailslurp.RulesetAction.BLOCK,
            inbox_id=support_inbox.id,
            scope=mailslurp.RulesetScope.RECEIVING_EMAILS,
            target="*@blocked.example.com")
        pulumi.export("rulesetId", block_one_domain.id)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input['RulesetAction'] action: The action that MailSlurp takes when the target matches. The `ALLOW`
               action wins over the `BLOCK` action. The `FILTER_REMOVE` action removes
               the matched address and keeps the rest of the email. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        :param pulumi.Input[_builtins.str] inbox_id: The inbox that the ruleset applies to. MailSlurp matches the email of the
               inbox against the target. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        :param pulumi.Input['RulesetScope'] scope: The activity that the ruleset applies to. Use `RECEIVING_EMAILS` for the
               email the inbox receives. Use `SENDING_EMAILS` for the email the inbox
               sends. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        :param pulumi.Input[_builtins.str] target: The email address or the pattern that MailSlurp matches. Use
               `*@example.com` to match every address of a domain. Use one full address
               to match that address alone. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: InboxRulesetArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        An inbox ruleset that blocks or allows email for one inbox. MailSlurp
        applies the ruleset when the inbox sends or receives email.

        You cannot update a ruleset. The API offers no update call, so Pulumi
        replaces the ruleset when you change any property. Pulumi creates the new
        ruleset, and then it deletes the old one. A ruleset is free, and it never
        counts against the inbox creation quota.

        ## Example Usage
        ### A ruleset that blocks the email of one domain
        ```python
        import pulumi
        import pulumi_mailslurp as mailslurp

        support_inbox = mailslurp.Inbox("support-inbox", name="support-inbox")
        block_one_domain = mailslurp.InboxRuleset("block-one-domain",
            action=mailslurp.RulesetAction.BLOCK,
            inbox_id=support_inbox.id,
            scope=mailslurp.RulesetScope.RECEIVING_EMAILS,
            target="*@blocked.example.com")
        pulumi.export("rulesetId", block_one_domain.id)
        ```


        :param str resource_name: The name of the resource.
        :param InboxRulesetArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(InboxRulesetArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action: pulumi.Input[Optional['RulesetAction']] = None,
                 inbox_id: pulumi.Input[Optional[_builtins.str]] = None,
                 scope: pulumi.Input[Optional['RulesetScope']] = None,
                 target: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = InboxRulesetArgs.__new__(InboxRulesetArgs)

            if action is None and not opts.urn:
                raise TypeError("Missing required property 'action'")
            __props__.__dict__["action"] = action
            if inbox_id is None and not opts.urn:
                raise TypeError("Missing required property 'inbox_id'")
            __props__.__dict__["inbox_id"] = inbox_id
            if scope is None and not opts.urn:
                raise TypeError("Missing required property 'scope'")
            __props__.__dict__["scope"] = scope
            if target is None and not opts.urn:
                raise TypeError("Missing required property 'target'")
            __props__.__dict__["target"] = target
            __props__.__dict__["created_at"] = None
            __props__.__dict__["handler"] = None
            __props__.__dict__["phone_id"] = None
        super(InboxRuleset, __self__).__init__(
            'mailslurp:index:InboxRuleset',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'InboxRuleset':
        """
        Get an existing InboxRuleset resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = InboxRulesetArgs.__new__(InboxRulesetArgs)

        __props__.__dict__["action"] = None
        __props__.__dict__["created_at"] = None
        __props__.__dict__["handler"] = None
        __props__.__dict__["inbox_id"] = None
        __props__.__dict__["phone_id"] = None
        __props__.__dict__["scope"] = None
        __props__.__dict__["target"] = None
        return InboxRuleset(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def action(self) -> pulumi.Output['RulesetAction']:
        """
        The action that MailSlurp takes when the target matches.
        """
        return pulumi.get(self, "action")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        The time when MailSlurp created the ruleset.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def handler(self) -> pulumi.Output[_builtins.str]:
        """
        The handler that MailSlurp runs for the ruleset. The API reports one value, `EXCEPTION`.
        """
        return pulumi.get(self, "handler")

    @_builtins.property
    @pulumi.getter(name="inboxId")
    def inbox_id(self) -> pulumi.Output[_builtins.str]:
        """
        The inbox that the ruleset applies to.
        """
        return pulumi.get(self, "inbox_id")

    @_builtins.property
    @pulumi.getter(name="phoneId")
    def phone_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The phone number that the ruleset applies to. This resource always names
        an inbox, so MailSlurp reports no phone number.
        """
        return pulumi.get(self, "phone_id")

    @_builtins.property
    @pulumi.getter
    def scope(self) -> pulumi.Output['RulesetScope']:
        """
        The activity that the ruleset applies to.
        """
        return pulumi.get(self, "scope")

    @_builtins.property
    @pulumi.getter
    def target(self) -> pulumi.Output[_builtins.str]:
        """
        The email address or the pattern that MailSlurp matches.
        """
        return pulumi.get(self, "target")

