# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'DomainNameRecordResult',
    'EmailTemplateVariable',
    'InboxForwarderMatchGroup',
    'InboxForwarderMatchRule',
]

@pulumi.output_type
class DomainNameRecordResult(dict):
    def __init__(__self__, *,
                 alternative_record_entries: Sequence[_builtins.str],
                 label: _builtins.str,
                 name: _builtins.str,
                 record_entries: Sequence[_builtins.str],
                 record_type: _builtins.str,
                 required: _builtins.bool,
                 ttl: _builtins.int):
        """
        :param Sequence[_builtins.str] alternative_record_entries: The values to use when your DNS provider rejects the main entries.
        :param _builtins.str label: The role of the record, for example `VERIFICATION` or `DKIM`.
        :param _builtins.str name: The full DNS name of the record.
        :param Sequence[_builtins.str] record_entries: The values of the record. Add one entry for each value.
        :param _builtins.str record_type: The DNS record type, for example `TXT`, `MX`, or `CNAME`.
        :param _builtins.bool required: MailSlurp reports whether the domain needs this record.
        :param _builtins.int ttl: The time to live of the record, in seconds.
        """
        pulumi.set(__self__, "alternative_record_entries", alternative_record_entries)
        pulumi.set(__self__, "label", label)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "record_entries", record_entries)
        pulumi.set(__self__, "record_type", record_type)
        pulumi.set(__self__, "required", required)
        pulumi.set(__self__, "ttl", ttl)

    @_builtins.property
    @pulumi.getter(name="alternativeRecordEntries")
    def alternative_record_entries(self) -> Sequence[_builtins.str]:
        """
        The values to use when your DNS provider rejects the main entries.
        """
        return pulumi.get(self, "alternative_record_entries")

    @_builtins.property
    @pulumi.getter
    def label(self) -> _builtins.str:
        """
        The role of the record, for example `VERIFICATION` or `DKIM`.
        """
        return pulumi.get(self, "label")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The full DNS name of the record.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="recordEntries")
    def record_entries(self) -> Sequence[_builtins.str]:
        """
        The values of the record. Add one entry for each value.
        """
        return pulumi.get(self, "record_entries")

    @_builtins.property
    @pulumi.getter(name="recordType")
    def record_type(self) -> _builtins.str:
        """
        The DNS record type, for example `TXT`, `MX`, or `CNAME`.
        """
        return pulumi.get(self, "record_type")

    @_builtins.property
    @pulumi.getter
    def required(self) -> _builtins.bool:
        """
        MailSlurp reports whether the domain needs this record.
        """
        return pulumi.get(self, "required")

    @_builtins.property
    @pulumi.getter
    def ttl(self) -> _builtins.int:
        """
        The time to live of the record, in seconds.
        """
        return pulumi.get(self, "ttl")


@pulumi.output_type
class EmailTemplateVariable(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "variableType":
            suggest = "variable_type"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in EmailTemplateVariable. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        EmailTemplateVariable.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        EmailTemplateVariable.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 name: _builtins.str,
                 variable_type: _builtins.str):
        """
        :param _builtins.str name: The name of the variable, without the moustache markers.
        :param _builtins.str variable_type: The type of the variable. The API reports one value, `STRING`.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "variable_type", variable_type)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the variable, without the moustache markers.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="variableType")
    def variable_type(self) -> _builtins.str:
        """
        The type of the variable. The API reports one value, `STRING`.
        """
        return pulumi.get(self, "variable_type")


@pulumi.output_type
class InboxForwarderMatchGroup(dict):
    def __init__(__self__, *,
                 operator: 'ForwarderMatchOperator',
                 groups: Optional[Sequence['outputs.InboxForwarderMatchGroup']] = None,
                 matches: Optional[Sequence['outputs.InboxForwarderMatchRule']] = None):
        """
        :param 'ForwarderMatchOperator' operator: The way that MailSlurp joins the rules of this group. Use `AND` when
               every rule must match. Use `OR` when one rule is enough.
        :param Sequence['InboxForwarderMatchGroup'] groups: The groups that this group holds. Put a group inside a group to build a
               deeper tree.
        :param Sequence['InboxForwarderMatchRule'] matches: The rules that MailSlurp applies to the email.
        """
        pulumi.set(__self__, "operator", operator)
        if groups is not None:
            pulumi.set(__self__, "groups", groups)
        if matches is not None:
            pulumi.set(__self__, "matches", matches)

    @_builtins.property
    @pulumi.getter
    def operator(self) -> 'ForwarderMatchOperator':
        """
        The way that MailSlurp joins the rules of this group. Use `AND` when
        every rule must match. Use `OR` when one rule is enough.
        """
        return pulumi.get(self, "operator")

    @_builtins.property
    @pulumi.getter
    def groups(self) -> Optional[Sequence['outputs.InboxForwarderMatchGroup']]:
        """
        The groups that this group holds. Put a group inside a group to build a
        deeper tree.
        """
        return pulumi.get(self, "groups")

    @_builtins.property
    @pulumi.getter
    def matches(self) -> Optional[Sequence['outputs.InboxForwarderMatchRule']]:
        """
        The rules that MailSlurp applies to the email.
        """
        return pulumi.get(self, "matches")


@pulumi.output_type
class InboxForwarderMatchRule(dict):
    def __init__(__self__, *,
                 field: 'ForwarderField',
                 should: 'ForwarderShould',
                 value: _builtins.str):
        """
        :param 'ForwarderField' field: The part of the email that MailSlurp compares against the `value` property.
        :param 'ForwarderShould' should: The way that MailSlurp compares the `value` property.
        :param _builtins.str value: The value or the pattern that MailSlurp compares.
        """
        pulumi.set(__self__, "field", field)
        pulumi.set(__self__, "should", should)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def field(self) -> 'ForwarderField':
        """
        The part of the email that MailSlurp compares against the `value` property.
        """
        return pulumi.get(self, "field")

    @_builtins.property
    @pulumi.getter
    def should(self) -> 'ForwarderShould':
        """
        The way that MailSlurp compares the `value` property.
        """
        return pulumi.get(self, "should")

    @_builtins.property
    @pulumi.getter
    def value(self) -> _builtins.str:
        """
        The value or the pattern that MailSlurp compares.
        """
        return pulumi.get(self, "value")


