# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 api_key: pulumi.Input[Optional[_builtins.str]] = None,
                 endpoint: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Provider resource.

        :param pulumi.Input[_builtins.str] api_key: The MailSlurp API key. The provider reads `MAILSLURP_API_KEY` when you
               do not set this property. The key is a secret, and Pulumi encrypts it
               in the state.
        :param pulumi.Input[_builtins.str] endpoint: The base URL of the MailSlurp API. The default is
               `https://api.mailslurp.com`. Set this property only when you test
               against a different endpoint.
        """
        if api_key is None:
            api_key = (_utilities.get_env('MAILSLURP_API_KEY') or '')
        if api_key is not None:
            pulumi.set(__self__, "api_key", api_key)
        if endpoint is None:
            endpoint = 'https://api.mailslurp.com'
        if endpoint is not None:
            pulumi.set(__self__, "endpoint", endpoint)

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The MailSlurp API key. The provider reads `MAILSLURP_API_KEY` when you
        do not set this property. The key is a secret, and Pulumi encrypts it
        in the state.
        """
        return pulumi.get(self, "api_key")

    @api_key.setter
    def api_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "api_key", value)

    @_builtins.property
    @pulumi.getter
    def endpoint(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The base URL of the MailSlurp API. The default is
        `https://api.mailslurp.com`. Set this property only when you test
        against a different endpoint.
        """
        return pulumi.get(self, "endpoint")

    @endpoint.setter
    def endpoint(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "endpoint", value)


@pulumi.type_token("pulumi:providers:mailslurp")
class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_key: pulumi.Input[Optional[_builtins.str]] = None,
                 endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Mailslurp resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] api_key: The MailSlurp API key. The provider reads `MAILSLURP_API_KEY` when you
               do not set this property. The key is a secret, and Pulumi encrypts it
               in the state.
        :param pulumi.Input[_builtins.str] endpoint: The base URL of the MailSlurp API. The default is
               `https://api.mailslurp.com`. Set this property only when you test
               against a different endpoint.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProviderArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Mailslurp resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_key: pulumi.Input[Optional[_builtins.str]] = None,
                 endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            if api_key is None:
                api_key = (_utilities.get_env('MAILSLURP_API_KEY') or '')
            __props__.__dict__["api_key"] = None if api_key is None else pulumi.Output.secret(api_key)
            if endpoint is None:
                endpoint = 'https://api.mailslurp.com'
            __props__.__dict__["endpoint"] = endpoint
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["apiKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Provider, __self__).__init__(
            'mailslurp',
            resource_name,
            __props__,
            opts)

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The MailSlurp API key. The provider reads `MAILSLURP_API_KEY` when you
        do not set this property. The key is a secret, and Pulumi encrypts it
        in the state.
        """
        return pulumi.get(self, "api_key")

    @_builtins.property
    @pulumi.getter
    def endpoint(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The base URL of the MailSlurp API. The default is
        `https://api.mailslurp.com`. Set this property only when you test
        against a different endpoint.
        """
        return pulumi.get(self, "endpoint")

