// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const DomainType = {
    /**
     * The domain serves inboxes that store email with HTTP endpoints.
     */
    HttpInbox: "HTTP_INBOX",
    /**
     * The domain serves inboxes that receive email on a real SMTP mail server.
     */
    SmtpDomain: "SMTP_DOMAIN",
} as const;

export type DomainType = (typeof DomainType)[keyof typeof DomainType];

export const ForwarderField = {
    /**
     * MailSlurp compares the addresses that the email went to.
     */
    Recipients: "RECIPIENTS",
    /**
     * MailSlurp compares the address that sent the email.
     */
    Sender: "SENDER",
    /**
     * MailSlurp compares the subject of the email.
     */
    Subject: "SUBJECT",
    /**
     * MailSlurp compares the attachments of the email.
     */
    Attachments: "ATTACHMENTS",
    /**
     * MailSlurp compares the file name of each attachment.
     */
    AttachmentFilename: "ATTACHMENT_FILENAME",
    /**
     * MailSlurp compares the text inside each attachment.
     */
    AttachmentText: "ATTACHMENT_TEXT",
} as const;

export type ForwarderField = (typeof ForwarderField)[keyof typeof ForwarderField];

export const ForwarderMatchOperator = {
    /**
     * MailSlurp forwards the email when every rule of the group matches.
     */
    And: "AND",
    /**
     * MailSlurp forwards the email when one rule of the group matches.
     */
    Or: "OR",
} as const;

export type ForwarderMatchOperator = (typeof ForwarderMatchOperator)[keyof typeof ForwarderMatchOperator];

export const ForwarderShould = {
    /**
     * MailSlurp reads the match value as a pattern. A star matches every character.
     */
    Wildcard: "WILDCARD",
    /**
     * MailSlurp compares the part with the whole match value. The API does not state how this mode differs from `EQUAL`.
     */
    Match: "MATCH",
    /**
     * MailSlurp forwards the email when the part holds the match value inside it.
     */
    Contain: "CONTAIN",
    /**
     * MailSlurp forwards the email when the part and the match value are the same.
     */
    Equal: "EQUAL",
} as const;

export type ForwarderShould = (typeof ForwarderShould)[keyof typeof ForwarderShould];

export const InboxType = {
    /**
     * The inbox stores email with HTTP endpoints. Use this type for tests and webhooks.
     */
    HttpInbox: "HTTP_INBOX",
    /**
     * The inbox receives email on a real SMTP mail server. Use this type for external senders.
     */
    SmtpInbox: "SMTP_INBOX",
} as const;

export type InboxType = (typeof InboxType)[keyof typeof InboxType];

export const RulesetAction = {
    /**
     * MailSlurp stops the email when the target matches.
     */
    Block: "BLOCK",
    /**
     * MailSlurp permits the email when the target matches, and this action wins over a block.
     */
    Allow: "ALLOW",
    /**
     * MailSlurp removes the matched address from the email, and the rest of the email continues.
     */
    FilterRemove: "FILTER_REMOVE",
    /**
     * MailSlurp answers the sender with a soft bounce, which states a temporary failure.
     */
    BounceSoft: "BOUNCE_SOFT",
    /**
     * MailSlurp answers the sender with a hard bounce, which states a permanent failure.
     */
    BounceHard: "BOUNCE_HARD",
} as const;

export type RulesetAction = (typeof RulesetAction)[keyof typeof RulesetAction];

export const RulesetScope = {
    /**
     * MailSlurp applies the ruleset to every email that the inbox receives.
     */
    ReceivingEmails: "RECEIVING_EMAILS",
    /**
     * MailSlurp applies the ruleset to every email that the inbox sends.
     */
    SendingEmails: "SENDING_EMAILS",
    /**
     * MailSlurp applies the ruleset to every SMS message that a phone number receives.
     */
    ReceivingSms: "RECEIVING_SMS",
    /**
     * MailSlurp applies the ruleset to every SMS message that a phone number sends.
     */
    SendingSms: "SENDING_SMS",
} as const;

export type RulesetScope = (typeof RulesetScope)[keyof typeof RulesetScope];

export const WebhookEventName = {
    /**
     * MailSlurp sends the event when an inbox receives an email payload.
     */
    EmailReceived: "EMAIL_RECEIVED",
    /**
     * MailSlurp sends the event when an AI transformer produces a new extraction result.
     */
    NewAiTransformResult: "NEW_AI_TRANSFORM_RESULT",
    /**
     * MailSlurp sends the event when an inbox receives a new email.
     */
    NewEmail: "NEW_EMAIL",
    /**
     * MailSlurp sends the event when it creates a contact from inbound email activity.
     */
    NewContact: "NEW_CONTACT",
    /**
     * MailSlurp sends the event when it detects an attachment on a received email.
     */
    NewAttachment: "NEW_ATTACHMENT",
    /**
     * MailSlurp sends the event when it tracks an email open.
     */
    EmailOpened: "EMAIL_OPENED",
    /**
     * MailSlurp sends the event when a recipient reads an email.
     */
    EmailRead: "EMAIL_READ",
    /**
     * MailSlurp sends the event when the delivery status of a sent email changes.
     */
    DeliveryStatus: "DELIVERY_STATUS",
    /**
     * MailSlurp sends the event when an email bounces at the account level.
     */
    Bounce: "BOUNCE",
    /**
     * MailSlurp sends the event when an email address bounces.
     */
    BounceRecipient: "BOUNCE_RECIPIENT",
    /**
     * MailSlurp sends the event when a phone number receives an SMS message.
     */
    NewSms: "NEW_SMS",
    /**
     * MailSlurp sends the event for a guest user.
     */
    NewGuestUser: "NEW_GUEST_USER",
} as const;

export type WebhookEventName = (typeof WebhookEventName)[keyof typeof WebhookEventName];
