<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Pulumi" Version="3.*" />
		<PackageReference Include="Jschady.Mailslurp" Version="*-*" />
	</ItemGroup>

	<PropertyGroup Condition="'$(PULUMI_LOCAL_NUGET)' != ''">
		<RestoreAdditionalProjectSources>$(PULUMI_LOCAL_NUGET)</RestoreAdditionalProjectSources>
	</PropertyGroup>

</Project>
