// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("mailslurp");

/**
 * The MailSlurp API key. The provider reads `MAILSLURP_API_KEY` when you
 * do not set this property. The key is a secret, and Pulumi encrypts it
 * in the state.
 */
export declare const apiKey: string;
Object.defineProperty(exports, "apiKey", {
    get() {
        return __config.get("apiKey") ?? (utilities.getEnv("MAILSLURP_API_KEY") || "");
    },
    enumerable: true,
});

/**
 * The base URL of the MailSlurp API. The default is
 * `https://api.mailslurp.com`. Set this property only when you test
 * against a different endpoint.
 */
export declare const endpoint: string;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint") ?? "https://api.mailslurp.com";
    },
    enumerable: true,
});

