// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Mailslurp.Outputs
{

    [OutputType]
    public sealed class DomainNameRecordResult
    {
        /// <summary>
        /// The values to use when your DNS provider rejects the main entries.
        /// </summary>
        public readonly ImmutableArray<string> AlternativeRecordEntries;
        /// <summary>
        /// The role of the record, for example `VERIFICATION` or `DKIM`.
        /// </summary>
        public readonly string Label;
        /// <summary>
        /// The full DNS name of the record.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The values of the record. Add one entry for each value.
        /// </summary>
        public readonly ImmutableArray<string> RecordEntries;
        /// <summary>
        /// The DNS record type, for example `TXT`, `MX`, or `CNAME`.
        /// </summary>
        public readonly string RecordType;
        /// <summary>
        /// MailSlurp reports whether the domain needs this record.
        /// </summary>
        public readonly bool Required;
        /// <summary>
        /// The time to live of the record, in seconds.
        /// </summary>
        public readonly int Ttl;

        [OutputConstructor]
        private DomainNameRecordResult(
            ImmutableArray<string> alternativeRecordEntries,

            string label,

            string name,

            ImmutableArray<string> recordEntries,

            string recordType,

            bool required,

            int ttl)
        {
            AlternativeRecordEntries = alternativeRecordEntries;
            Label = label;
            Name = name;
            RecordEntries = recordEntries;
            RecordType = recordType;
            Required = required;
            Ttl = ttl;
        }
    }
}
