// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Mailslurp.Outputs
{

    [OutputType]
    public sealed class EmailTemplateVariable
    {
        /// <summary>
        /// The name of the variable, without the moustache markers.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The type of the variable. The API reports one value, `STRING`.
        /// </summary>
        public readonly string VariableType;

        [OutputConstructor]
        private EmailTemplateVariable(
            string name,

            string variableType)
        {
            Name = name;
            VariableType = variableType;
        }
    }
}
