// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Mailslurp.Outputs
{

    [OutputType]
    public sealed class InboxForwarderMatchRule
    {
        /// <summary>
        /// The part of the email that MailSlurp compares against the `value` property.
        /// </summary>
        public readonly Jschady.Mailslurp.ForwarderField Field;
        /// <summary>
        /// The way that MailSlurp compares the `value` property.
        /// </summary>
        public readonly Jschady.Mailslurp.ForwarderShould Should;
        /// <summary>
        /// The value or the pattern that MailSlurp compares.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private InboxForwarderMatchRule(
            Jschady.Mailslurp.ForwarderField field,

            Jschady.Mailslurp.ForwarderShould should,

            string value)
        {
            Field = field;
            Should = should;
            Value = value;
        }
    }
}
