# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('mailslurp')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def api_key(self) -> str:
        """
        The MailSlurp API key. The provider reads `MAILSLURP_API_KEY` when you
        do not set this property. The key is a secret, and Pulumi encrypts it
        in the state.
        """
        return __config__.get('apiKey') or (_utilities.get_env('MAILSLURP_API_KEY') or '')

    @_builtins.property
    def endpoint(self) -> str:
        """
        The base URL of the MailSlurp API. The default is
        `https://api.mailslurp.com`. Set this property only when you test
        against a different endpoint.
        """
        return __config__.get('endpoint') or 'https://api.mailslurp.com'

