// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Mailslurp.Inputs
{

    public sealed class InboxForwarderMatchGroupArgs : global::Pulumi.ResourceArgs
    {
        [Input("groups")]
        private InputList<Inputs.InboxForwarderMatchGroupArgs>? _groups;

        /// <summary>
        /// The groups that this group holds. Put a group inside a group to build a
        /// deeper tree.
        /// </summary>
        public InputList<Inputs.InboxForwarderMatchGroupArgs> Groups
        {
            get => _groups ?? (_groups = new InputList<Inputs.InboxForwarderMatchGroupArgs>());
            set => _groups = value;
        }

        [Input("matches")]
        private InputList<Inputs.InboxForwarderMatchRuleArgs>? _matches;

        /// <summary>
        /// The rules that MailSlurp applies to the email.
        /// </summary>
        public InputList<Inputs.InboxForwarderMatchRuleArgs> Matches
        {
            get => _matches ?? (_matches = new InputList<Inputs.InboxForwarderMatchRuleArgs>());
            set => _matches = value;
        }

        /// <summary>
        /// The way that MailSlurp joins the rules of this group. Use `AND` when
        /// every rule must match. Use `OR` when one rule is enough.
        /// </summary>
        [Input("operator", required: true)]
        public Input<Jschady.Mailslurp.ForwarderMatchOperator> Operator { get; set; } = null!;

        public InboxForwarderMatchGroupArgs()
        {
        }
        public static new InboxForwarderMatchGroupArgs Empty => new InboxForwarderMatchGroupArgs();
    }
}
