// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Mailslurp.Inputs
{

    public sealed class InboxForwarderMatchRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The part of the email that MailSlurp compares against the `value` property.
        /// </summary>
        [Input("field", required: true)]
        public Input<Jschady.Mailslurp.ForwarderField> Field { get; set; } = null!;

        /// <summary>
        /// The way that MailSlurp compares the `value` property.
        /// </summary>
        [Input("should", required: true)]
        public Input<Jschady.Mailslurp.ForwarderShould> Should { get; set; } = null!;

        /// <summary>
        /// The value or the pattern that MailSlurp compares.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public InboxForwarderMatchRuleArgs()
        {
        }
        public static new InboxForwarderMatchRuleArgs Empty => new InboxForwarderMatchRuleArgs();
    }
}
