// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * An email template that MailSlurp fills with values when you send an email.
 * You write each variable inside the content with the moustache markers.
 *
 * You can update the `name` and the `content` of a template in place. Pulumi
 * never replaces a template. MailSlurp parses the `variables` list from the
 * content, so you cannot set it. A template is free, and it never counts
 * against the inbox creation quota.
 *
 * ## Example Usage
 * ### A template that MailSlurp fills with two variables
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mailslurp from "pulumi-mailslurp";
 *
 * const welcomeTemplate = new mailslurp.EmailTemplate("welcome-template", {
 *     content: `Hello {{firstName}},
 * Your inbox {{inboxAddress}} is ready.
 * `,
 *     name: "welcome-template",
 * });
 * export const variables = welcomeTemplate.variables;
 * ```
 */
export class EmailTemplate extends pulumi.CustomResource {
    /**
     * Get an existing EmailTemplate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): EmailTemplate {
        return new EmailTemplate(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mailslurp:index:EmailTemplate';

    /**
     * Returns true if the given object is an instance of EmailTemplate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EmailTemplate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EmailTemplate.__pulumiType;
    }

    /**
     * The body of the template.
     */
    declare public readonly content: pulumi.Output<string>;
    /**
     * The time when MailSlurp created the template.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The display name of the template.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The variables that MailSlurp reads from the content. MailSlurp parses this
     * list on the server, so you cannot set it.
     */
    declare public /*out*/ readonly variables: pulumi.Output<outputs.EmailTemplateVariable[]>;

    /**
     * Create a EmailTemplate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EmailTemplateArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.content === undefined && !opts.urn) {
                throw new Error("Missing required property 'content'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["content"] = args?.content;
            resourceInputs["name"] = args?.name;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["variables"] = undefined /*out*/;
        } else {
            resourceInputs["content"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["variables"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EmailTemplate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a EmailTemplate resource.
 */
export interface EmailTemplateArgs {
    /**
     * The body of the template. Write a variable as `{{firstName}}`, and
     * MailSlurp reports each variable that it reads in the `variables` property.
     * You can update this property in place.
     */
    content: pulumi.Input<string>;
    /**
     * The display name of the template. You can update this property in place.
     */
    name: pulumi.Input<string>;
}
