// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * An inbox ruleset that blocks or allows email for one inbox. MailSlurp
 * applies the ruleset when the inbox sends or receives email.
 *
 * You cannot update a ruleset. The API offers no update call, so Pulumi
 * replaces the ruleset when you change any property. Pulumi creates the new
 * ruleset, and then it deletes the old one. A ruleset is free, and it never
 * counts against the inbox creation quota.
 *
 * ## Example Usage
 * ### A ruleset that blocks the email of one domain
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mailslurp from "pulumi-mailslurp";
 *
 * const supportInbox = new mailslurp.Inbox("support-inbox", {name: "support-inbox"});
 * const blockOneDomain = new mailslurp.InboxRuleset("block-one-domain", {
 *     action: mailslurp.RulesetAction.Block,
 *     inboxId: supportInbox.id,
 *     scope: mailslurp.RulesetScope.ReceivingEmails,
 *     target: "*@blocked.example.com",
 * });
 * export const rulesetId = blockOneDomain.id;
 * ```
 */
export class InboxRuleset extends pulumi.CustomResource {
    /**
     * Get an existing InboxRuleset resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): InboxRuleset {
        return new InboxRuleset(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mailslurp:index:InboxRuleset';

    /**
     * Returns true if the given object is an instance of InboxRuleset.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is InboxRuleset {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === InboxRuleset.__pulumiType;
    }

    /**
     * The action that MailSlurp takes when the target matches.
     */
    declare public readonly action: pulumi.Output<enums.RulesetAction>;
    /**
     * The time when MailSlurp created the ruleset.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The handler that MailSlurp runs for the ruleset. The API reports one value, `EXCEPTION`.
     */
    declare public /*out*/ readonly handler: pulumi.Output<string>;
    /**
     * The inbox that the ruleset applies to.
     */
    declare public readonly inboxId: pulumi.Output<string>;
    /**
     * The phone number that the ruleset applies to. This resource always names
     * an inbox, so MailSlurp reports no phone number.
     */
    declare public /*out*/ readonly phoneId: pulumi.Output<string | undefined>;
    /**
     * The activity that the ruleset applies to.
     */
    declare public readonly scope: pulumi.Output<enums.RulesetScope>;
    /**
     * The email address or the pattern that MailSlurp matches.
     */
    declare public readonly target: pulumi.Output<string>;

    /**
     * Create a InboxRuleset resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: InboxRulesetArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.action === undefined && !opts.urn) {
                throw new Error("Missing required property 'action'");
            }
            if (args?.inboxId === undefined && !opts.urn) {
                throw new Error("Missing required property 'inboxId'");
            }
            if (args?.scope === undefined && !opts.urn) {
                throw new Error("Missing required property 'scope'");
            }
            if (args?.target === undefined && !opts.urn) {
                throw new Error("Missing required property 'target'");
            }
            resourceInputs["action"] = args?.action;
            resourceInputs["inboxId"] = args?.inboxId;
            resourceInputs["scope"] = args?.scope;
            resourceInputs["target"] = args?.target;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["handler"] = undefined /*out*/;
            resourceInputs["phoneId"] = undefined /*out*/;
        } else {
            resourceInputs["action"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["handler"] = undefined /*out*/;
            resourceInputs["inboxId"] = undefined /*out*/;
            resourceInputs["phoneId"] = undefined /*out*/;
            resourceInputs["scope"] = undefined /*out*/;
            resourceInputs["target"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(InboxRuleset.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a InboxRuleset resource.
 */
export interface InboxRulesetArgs {
    /**
     * The action that MailSlurp takes when the target matches. The `ALLOW`
     * action wins over the `BLOCK` action. The `FILTER_REMOVE` action removes
     * the matched address and keeps the rest of the email. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
     */
    action: pulumi.Input<enums.RulesetAction>;
    /**
     * The inbox that the ruleset applies to. MailSlurp matches the email of the
     * inbox against the target. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
     */
    inboxId: pulumi.Input<string>;
    /**
     * The activity that the ruleset applies to. Use `RECEIVING_EMAILS` for the
     * email the inbox receives. Use `SENDING_EMAILS` for the email the inbox
     * sends. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
     */
    scope: pulumi.Input<enums.RulesetScope>;
    /**
     * The email address or the pattern that MailSlurp matches. Use
     * `*@example.com` to match every address of a domain. Use one full address
     * to match that address alone. **Warning:** If you change this property, Pulumi replaces the ruleset. The new ruleset carries a new identifier.
     */
    target: pulumi.Input<string>;
}
