// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * An inbox forwarder that sends a copy of a matching email to other
 * addresses. MailSlurp reads each email that the inbox receives, and
 * forwards the email when the rule matches.
 *
 * You can update the `field`, the `should`, the `match`, the `matchOptions`
 * and the `forwardToRecipients` properties in place. Pulumi replaces the
 * forwarder when you change the `inboxId` property, because the API takes
 * the inbox on the create call alone.
 *
 * The API requires the `field` and the `match` properties, or the
 * `matchOptions` property. A write that names none of them fails. Each
 * update sends the whole create body, so a value that you set outside
 * Pulumi can go away.
 *
 * MailSlurp writes the `name` of the forwarder. The create call takes no
 * name, so you cannot set it. This resource does not carry the
 * `attachmentTextExtractionMethod` property of the API.
 *
 * ## Example Usage
 * ### A forwarder that sends every invoice email to the billing address
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mailslurp from "pulumi-mailslurp";
 *
 * const billingInbox = new mailslurp.Inbox("billing-inbox", {name: "billing-inbox"});
 * const invoiceForwarder = new mailslurp.InboxForwarder("invoice-forwarder", {
 *     field: mailslurp.ForwarderField.Subject,
 *     forwardToRecipients: ["billing@example.com"],
 *     inboxId: billingInbox.id,
 *     match: "invoice",
 *     should: mailslurp.ForwarderShould.Contain,
 * });
 * export const forwarderId = invoiceForwarder.id;
 * ```
 */
export class InboxForwarder extends pulumi.CustomResource {
    /**
     * Get an existing InboxForwarder resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): InboxForwarder {
        return new InboxForwarder(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mailslurp:index:InboxForwarder';

    /**
     * Returns true if the given object is an instance of InboxForwarder.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is InboxForwarder {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === InboxForwarder.__pulumiType;
    }

    /**
     * The time when MailSlurp created the forwarder.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The part of the email that MailSlurp compares.
     */
    declare public readonly field: pulumi.Output<enums.ForwarderField | undefined>;
    /**
     * The addresses that MailSlurp sends the matching email to.
     */
    declare public readonly forwardToRecipients: pulumi.Output<string[]>;
    /**
     * The inbox that the forwarder reads.
     */
    declare public readonly inboxId: pulumi.Output<string>;
    /**
     * The value or the pattern that MailSlurp compares.
     */
    declare public readonly match: pulumi.Output<string | undefined>;
    /**
     * The tree of match rules that MailSlurp applies to each email.
     */
    declare public readonly matchOptions: pulumi.Output<outputs.InboxForwarderMatchGroup | undefined>;
    /**
     * The display name of the forwarder. MailSlurp writes it, and the create
     * call takes no name, so you cannot set it.
     */
    declare public /*out*/ readonly name: pulumi.Output<string | undefined>;
    /**
     * The way that MailSlurp compares the `match` value.
     */
    declare public readonly should: pulumi.Output<enums.ForwarderShould | undefined>;

    /**
     * Create a InboxForwarder resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: InboxForwarderArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.forwardToRecipients === undefined && !opts.urn) {
                throw new Error("Missing required property 'forwardToRecipients'");
            }
            if (args?.inboxId === undefined && !opts.urn) {
                throw new Error("Missing required property 'inboxId'");
            }
            resourceInputs["field"] = args?.field;
            resourceInputs["forwardToRecipients"] = args?.forwardToRecipients;
            resourceInputs["inboxId"] = args?.inboxId;
            resourceInputs["match"] = args?.match;
            resourceInputs["matchOptions"] = args?.matchOptions;
            resourceInputs["should"] = args?.should;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
        } else {
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["field"] = undefined /*out*/;
            resourceInputs["forwardToRecipients"] = undefined /*out*/;
            resourceInputs["inboxId"] = undefined /*out*/;
            resourceInputs["match"] = undefined /*out*/;
            resourceInputs["matchOptions"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["should"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(InboxForwarder.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a InboxForwarder resource.
 */
export interface InboxForwarderArgs {
    /**
     * The part of the email that MailSlurp compares against the `match` value.
     * You can update this property in place.
     */
    field?: pulumi.Input<enums.ForwarderField | undefined>;
    /**
     * The addresses that MailSlurp sends the matching email to. The API
     * requires this property on every write. You can update this property in
     * place.
     */
    forwardToRecipients: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The inbox that the forwarder reads. MailSlurp compares each email that
     * this inbox receives. **Warning:** If you change this property, Pulumi
     * replaces the forwarder. The new forwarder carries a new identifier.
     */
    inboxId: pulumi.Input<string>;
    /**
     * The value or the pattern that MailSlurp compares. Use `*@example.com` to
     * match every address of a domain. You can update this property in place.
     */
    match?: pulumi.Input<string | undefined>;
    /**
     * A tree of match rules that MailSlurp applies to each email. The
     * `operator` property joins the rules of one group. You can put a group
     * inside the `groups` property. You can update this property in place.
     */
    matchOptions?: pulumi.Input<inputs.InboxForwarderMatchGroupArgs | undefined>;
    /**
     * The way that MailSlurp compares the `match` value. Use `WILDCARD` for a
     * pattern that holds a star. Use `EQUAL` for one exact value. You can
     * update this property in place.
     */
    should?: pulumi.Input<enums.ForwarderShould | undefined>;
}
