// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * An email inbox on MailSlurp. The inbox has an email address that can
 * send and receive email.
 *
 * You can update the `name`, `description`, `tags`, `expiresAt`, and
 * `favourite` properties in place. If you change any other property,
 * Pulumi replaces the inbox. Each replacement creates a new inbox, which
 * counts against the 30-day inbox creation quota of your MailSlurp
 * account. MailSlurp bills each creation on paid plans. If you remove a
 * property that forces a replacement, Pulumi keeps the inbox.
 *
 * ## Example Usage
 * ### An inbox that receives email at an address MailSlurp assigns
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mailslurp from "pulumi-mailslurp";
 *
 * const teamInbox = new mailslurp.Inbox("team-inbox", {
 *     description: "The shared inbox of the team",
 *     inboxType: mailslurp.InboxType.HttpInbox,
 *     name: "team-inbox",
 *     tags: [
 *         "pulumi",
 *         "team",
 *     ],
 * });
 * export const emailAddress = teamInbox.emailAddress;
 * ```
 * ### A virtual inbox that holds every test email inside MailSlurp
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mailslurp from "pulumi-mailslurp";
 *
 * const testInbox = new mailslurp.Inbox("test-inbox", {
 *     description: "The inbox that the acceptance tests read",
 *     expiresIn: 3600000,
 *     name: "test-inbox",
 *     tags: ["test"],
 *     virtualInbox: true,
 * });
 * export const emailAddress = testInbox.emailAddress;
 * ```
 */
export class Inbox extends pulumi.CustomResource {
    /**
     * Get an existing Inbox resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Inbox {
        return new Inbox(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mailslurp:index:Inbox';

    /**
     * Returns true if the given object is an instance of Inbox.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Inbox {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Inbox.__pulumiType;
    }

    /**
     * The region of the account that holds the inbox.
     */
    declare public /*out*/ readonly accountRegion: pulumi.Output<string | undefined>;
    /**
     * The time when MailSlurp created the inbox.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The free-text description of the inbox.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The domain part of the inbox email address.
     */
    declare public /*out*/ readonly domain: pulumi.Output<string | undefined>;
    /**
     * The identifier of the custom domain that provides the inbox address.
     */
    declare public readonly domainId: pulumi.Output<string | undefined>;
    /**
     * The custom domain that provides the inbox address.
     */
    declare public readonly domainName: pulumi.Output<string | undefined>;
    /**
     * The full email address of the inbox.
     */
    declare public readonly emailAddress: pulumi.Output<string>;
    /**
     * The time when MailSlurp expires the inbox, in RFC 3339 format.
     */
    declare public readonly expiresAt: pulumi.Output<string | undefined>;
    /**
     * The lifetime of the inbox in milliseconds. The API does not echo this property.
     */
    declare public readonly expiresIn: pulumi.Output<number | undefined>;
    /**
     * MailSlurp reports whether the inbox is a favourite in the dashboard.
     */
    declare public readonly favourite: pulumi.Output<boolean | undefined>;
    /**
     * The special function of the inbox, for example an alias or a catch-all.
     */
    declare public /*out*/ readonly functionsAs: pulumi.Output<string | undefined>;
    /**
     * The inbox type.
     */
    declare public readonly inboxType: pulumi.Output<enums.InboxType | undefined>;
    /**
     * The local part of the inbox email address.
     */
    declare public /*out*/ readonly localPart: pulumi.Output<string | undefined>;
    /**
     * The display name of the inbox.
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * The prefix for the local part of the assigned email address. The API does not echo this property.
     */
    declare public readonly prefix: pulumi.Output<string | undefined>;
    /**
     * MailSlurp reports whether the inbox is read-only.
     */
    declare public /*out*/ readonly readOnly: pulumi.Output<boolean>;
    /**
     * The tags on the inbox.
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    /**
     * The shared MailSlurp domain pool value of the inbox. The API does not echo this property.
     */
    declare public readonly useDomainPool: pulumi.Output<boolean | undefined>;
    /**
     * The short address value of the inbox. The API does not echo this property.
     */
    declare public readonly useShortAddress: pulumi.Output<boolean | undefined>;
    /**
     * MailSlurp reports whether the inbox is virtual. A virtual inbox never sends email to real recipients.
     */
    declare public readonly virtualInbox: pulumi.Output<boolean | undefined>;

    /**
     * Create a Inbox resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: InboxArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["description"] = args?.description;
            resourceInputs["domainId"] = args?.domainId;
            resourceInputs["domainName"] = args?.domainName;
            resourceInputs["emailAddress"] = args?.emailAddress;
            resourceInputs["expiresAt"] = args?.expiresAt;
            resourceInputs["expiresIn"] = args?.expiresIn;
            resourceInputs["favourite"] = args?.favourite;
            resourceInputs["inboxType"] = args?.inboxType;
            resourceInputs["name"] = args?.name;
            resourceInputs["prefix"] = args?.prefix;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["useDomainPool"] = args?.useDomainPool;
            resourceInputs["useShortAddress"] = args?.useShortAddress;
            resourceInputs["virtualInbox"] = args?.virtualInbox;
            resourceInputs["accountRegion"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["functionsAs"] = undefined /*out*/;
            resourceInputs["localPart"] = undefined /*out*/;
            resourceInputs["readOnly"] = undefined /*out*/;
        } else {
            resourceInputs["accountRegion"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["domainId"] = undefined /*out*/;
            resourceInputs["domainName"] = undefined /*out*/;
            resourceInputs["emailAddress"] = undefined /*out*/;
            resourceInputs["expiresAt"] = undefined /*out*/;
            resourceInputs["expiresIn"] = undefined /*out*/;
            resourceInputs["favourite"] = undefined /*out*/;
            resourceInputs["functionsAs"] = undefined /*out*/;
            resourceInputs["inboxType"] = undefined /*out*/;
            resourceInputs["localPart"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["prefix"] = undefined /*out*/;
            resourceInputs["readOnly"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["useDomainPool"] = undefined /*out*/;
            resourceInputs["useShortAddress"] = undefined /*out*/;
            resourceInputs["virtualInbox"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Inbox.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Inbox resource.
 */
export interface InboxArgs {
    /**
     * A free-text description of the inbox. You can update this property in
     * place. The API cannot clear this property after you set it.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The identifier of a verified custom domain that provides the inbox
     * address. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
     */
    domainId?: pulumi.Input<string | undefined>;
    /**
     * The custom domain that provides the inbox address. The domain must be
     * verified in your MailSlurp account. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
     */
    domainName?: pulumi.Input<string | undefined>;
    /**
     * The full email address of the inbox. When you do not set this
     * property, MailSlurp assigns an address. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
     */
    emailAddress?: pulumi.Input<string | undefined>;
    /**
     * The time when MailSlurp expires the inbox, in RFC 3339 format. You can
     * update this property in place. The API cannot clear this property after
     * you set it.
     */
    expiresAt?: pulumi.Input<string | undefined>;
    /**
     * The lifetime of the inbox in milliseconds. The API does not echo this
     * property, so Pulumi keeps it in the state and does not diff it against
     * the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
     */
    expiresIn?: pulumi.Input<number | undefined>;
    /**
     * If you set this property, MailSlurp marks the inbox as a favourite in
     * the dashboard. You can update this property in place.
     */
    favourite?: pulumi.Input<boolean | undefined>;
    /**
     * The inbox type: `HTTP_INBOX` or `SMTP_INBOX`. A refresh keeps the
     * prior value when the API does not report a type. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
     */
    inboxType?: pulumi.Input<enums.InboxType | undefined>;
    /**
     * The display name of the inbox. You can update this property in place.
     * The API cannot clear this property after you set it.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * A prefix for the local part of the assigned email address. The API
     * does not echo this property, so Pulumi keeps it in the state and does
     * not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
     */
    prefix?: pulumi.Input<string | undefined>;
    /**
     * The tags on the inbox. Use tags to group and find inboxes. You can
     * update this property in place. Set an empty list to clear the tags.
     */
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * If you set this property, MailSlurp assigns the address from the shared
     * domain pool. The API does not echo this property, so Pulumi keeps it in
     * the state and does not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
     */
    useDomainPool?: pulumi.Input<boolean | undefined>;
    /**
     * If you set this property, MailSlurp assigns a short email address to the
     * inbox. The API does not echo this property, so Pulumi keeps it in the
     * state and does not diff it against the API. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
     */
    useShortAddress?: pulumi.Input<boolean | undefined>;
    /**
     * If you set this property, MailSlurp creates a virtual inbox. A virtual
     * inbox receives email but never sends it to real recipients. Use it for
     * safe tests. **Warning:** If you change this property, Pulumi replaces the inbox. The new inbox counts against the 30-day creation quota, and MailSlurp bills it.
     */
    virtualInbox?: pulumi.Input<boolean | undefined>;
}
