// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { EmailTemplateArgs } from "./emailTemplate";
export type EmailTemplate = import("./emailTemplate").EmailTemplate;
export const EmailTemplate: typeof import("./emailTemplate").EmailTemplate = null as any;
utilities.lazyLoad(exports, ["EmailTemplate"], () => require("./emailTemplate"));

export { GetDomainArgs, GetDomainResult, GetDomainOutputArgs } from "./getDomain";
export const getDomain: typeof import("./getDomain").getDomain = null as any;
export const getDomainOutput: typeof import("./getDomain").getDomainOutput = null as any;
utilities.lazyLoad(exports, ["getDomain","getDomainOutput"], () => require("./getDomain"));

export { GetInboxArgs, GetInboxResult, GetInboxOutputArgs } from "./getInbox";
export const getInbox: typeof import("./getInbox").getInbox = null as any;
export const getInboxOutput: typeof import("./getInbox").getInboxOutput = null as any;
utilities.lazyLoad(exports, ["getInbox","getInboxOutput"], () => require("./getInbox"));

export { InboxArgs } from "./inbox";
export type Inbox = import("./inbox").Inbox;
export const Inbox: typeof import("./inbox").Inbox = null as any;
utilities.lazyLoad(exports, ["Inbox"], () => require("./inbox"));

export { InboxForwarderArgs } from "./inboxForwarder";
export type InboxForwarder = import("./inboxForwarder").InboxForwarder;
export const InboxForwarder: typeof import("./inboxForwarder").InboxForwarder = null as any;
utilities.lazyLoad(exports, ["InboxForwarder"], () => require("./inboxForwarder"));

export { InboxRulesetArgs } from "./inboxRuleset";
export type InboxRuleset = import("./inboxRuleset").InboxRuleset;
export const InboxRuleset: typeof import("./inboxRuleset").InboxRuleset = null as any;
utilities.lazyLoad(exports, ["InboxRuleset"], () => require("./inboxRuleset"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { WebhookArgs } from "./webhook";
export type Webhook = import("./webhook").Webhook;
export const Webhook: typeof import("./webhook").Webhook = null as any;
utilities.lazyLoad(exports, ["Webhook"], () => require("./webhook"));


// Export enums:
export * from "./types/enums";

// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "mailslurp:index:EmailTemplate":
                return new EmailTemplate(name, <any>undefined, { urn })
            case "mailslurp:index:Inbox":
                return new Inbox(name, <any>undefined, { urn })
            case "mailslurp:index:InboxForwarder":
                return new InboxForwarder(name, <any>undefined, { urn })
            case "mailslurp:index:InboxRuleset":
                return new InboxRuleset(name, <any>undefined, { urn })
            case "mailslurp:index:Webhook":
                return new Webhook(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("mailslurp", "index", _module)
pulumi.runtime.registerResourcePackage("mailslurp", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:mailslurp") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
