// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A webhook that MailSlurp calls when an event happens. MailSlurp posts the
 * event payload to the URL that you set.
 *
 * You can update every property of the webhook in place. Pulumi never
 * replaces a webhook. A webhook that names no inbox listens to every inbox
 * in the account. If you set the `inboxId` property, the webhook listens to
 * that one inbox.
 *
 * This resource does not carry the `basicAuth` property of the API. The API
 * reports the property as a boolean, so Pulumi cannot compare the user name
 * and the password that it sent. The webhook list of the API also reports
 * both values as plain text. Use the `includeHeaders` property to
 * authenticate the request.
 *
 * ## Example Usage
 * ### A webhook that posts every new email of one inbox to your server
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mailslurp from "pulumi-mailslurp";
 *
 * const alertInbox = new mailslurp.Inbox("alert-inbox", {name: "alert-inbox"});
 * const newEmailHook = new mailslurp.Webhook("new-email-hook", {
 *     eventName: mailslurp.WebhookEventName.NewEmail,
 *     inboxId: alertInbox.id,
 *     name: "new-email-hook",
 *     url: "https://example.com/mailslurp/new-email",
 * });
 * export const webhookId = newEmailHook.id;
 * ```
 */
export class Webhook extends pulumi.CustomResource {
    /**
     * Get an existing Webhook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Webhook {
        return new Webhook(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mailslurp:index:Webhook';

    /**
     * Returns true if the given object is an instance of Webhook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Webhook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Webhook.__pulumiType;
    }

    /**
     * The time when MailSlurp created the webhook.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string | undefined>;
    /**
     * MailSlurp reports whether the webhook is enabled. The API does not
     * document this property, and the value can be empty.
     */
    declare public /*out*/ readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * The event that triggers the webhook.
     */
    declare public readonly eventName: pulumi.Output<enums.WebhookEventName>;
    /**
     * The health of the webhook, as MailSlurp computes it. The value is
     * `HEALTHY` or `UNHEALTHY`. The value changes often, so Pulumi never
     * compares it.
     */
    declare public /*out*/ readonly healthStatus: pulumi.Output<string | undefined>;
    /**
     * MailSlurp reports whether it accepts an insecure SSL certificate on your server.
     */
    declare public readonly ignoreInsecureSslCertificates: pulumi.Output<boolean>;
    /**
     * The inbox that triggers the webhook. An empty value means that every
     * inbox in the account triggers the webhook.
     */
    declare public readonly inboxId: pulumi.Output<string | undefined>;
    /**
     * The HTTP headers that MailSlurp sends with each webhook request. The API
     * names this value `requestHeaders` when it reports it.
     */
    declare public readonly includeHeaders: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The HTTP method that your server must accept. MailSlurp sends `POST`.
     */
    declare public /*out*/ readonly method: pulumi.Output<string>;
    /**
     * The display name of the webhook.
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * The template for the JSON body of the webhook request.
     */
    declare public readonly requestBodyTemplate: pulumi.Output<string | undefined>;
    /**
     * The URL that MailSlurp posts the event payload to.
     */
    declare public readonly url: pulumi.Output<string>;
    /**
     * MailSlurp reports whether it calls your server from its static IP range.
     */
    declare public readonly useStaticIpRange: pulumi.Output<boolean>;

    /**
     * Create a Webhook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WebhookArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.url === undefined && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["eventName"] = args?.eventName;
            resourceInputs["ignoreInsecureSslCertificates"] = args?.ignoreInsecureSslCertificates;
            resourceInputs["inboxId"] = args?.inboxId;
            resourceInputs["includeHeaders"] = args?.includeHeaders ? pulumi.secret(args.includeHeaders) : undefined;
            resourceInputs["name"] = args?.name;
            resourceInputs["requestBodyTemplate"] = args?.requestBodyTemplate;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["url"] = args?.url;
            resourceInputs["useStaticIpRange"] = args?.useStaticIpRange;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["healthStatus"] = undefined /*out*/;
            resourceInputs["method"] = undefined /*out*/;
        } else {
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["eventName"] = undefined /*out*/;
            resourceInputs["healthStatus"] = undefined /*out*/;
            resourceInputs["ignoreInsecureSslCertificates"] = undefined /*out*/;
            resourceInputs["inboxId"] = undefined /*out*/;
            resourceInputs["includeHeaders"] = undefined /*out*/;
            resourceInputs["method"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["requestBodyTemplate"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
            resourceInputs["useStaticIpRange"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["includeHeaders"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Webhook.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Webhook resource.
 */
export interface WebhookArgs {
    /**
     * The event that triggers the webhook. If you do not set this property,
     * MailSlurp sends the `EMAIL_RECEIVED` event.
     */
    eventName?: pulumi.Input<enums.WebhookEventName | undefined>;
    /**
     * If you set this property, MailSlurp accepts an insecure SSL certificate
     * on your server. Use it for a self-signed certificate. The default value
     * is false.
     */
    ignoreInsecureSslCertificates?: pulumi.Input<boolean | undefined>;
    /**
     * The inbox that triggers the webhook. If you do not set this property,
     * every inbox in the account triggers the webhook. You can move the webhook
     * to another inbox in place. You cannot remove this property after you set
     * it, because the API has no value for the account.
     */
    inboxId?: pulumi.Input<string | undefined>;
    /**
     * The HTTP headers that MailSlurp sends with each webhook request. Each key
     * is a header name, and each value is the header value. The provider marks
     * the values as secret. MailSlurp reports the values as plain text, so
     * anyone with the API key can read them.
     */
    includeHeaders?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The display name of the webhook. You can update this property in place.
     * Remove the property to clear the name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * A template for the JSON body of the webhook request. Use `{{variableName}}`
     * markers to insert values from the event payload.
     */
    requestBodyTemplate?: pulumi.Input<string | undefined>;
    /**
     * The tags on the webhook. MailSlurp accepts the tags and never reports
     * them, so Pulumi cannot compare this property. A change to the tags alone
     * plans no update.
     */
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The URL that MailSlurp posts the event payload to. Your server must
     * accept the request. You can update this property in place.
     */
    url: pulumi.Input<string>;
    /**
     * If you set this property, MailSlurp calls your server from its static IP
     * range. The default value is false.
     */
    useStaticIpRange?: pulumi.Input<boolean | undefined>;
}
